// packages/solid/src/theme/useColorScheme.ts
import { createSignal, onCleanup, onMount, type Accessor } from 'solid-js'
import { getColorScheme, watchColorScheme, type ColorScheme } from '@iris-ui-kit/theme'

/**
 * Reactive system color scheme (`'light'` / `'dark'`) accessor from
 * `prefers-color-scheme`. SSR-safe (reports `'light'` until mounted). Wire it to
 * a theme store to auto-follow the system:
 *
 * ```tsx
 * const scheme = useColorScheme()
 * createEffect(() => store.setTheme(scheme() === 'dark' ? 'dark' : 'light'))
 * ```
 */
export function useColorScheme(): Accessor<ColorScheme> {
  const [scheme, setScheme] = createSignal<ColorScheme>(getColorScheme())
  onMount(() => {
    setScheme(getColorScheme())
    onCleanup(watchColorScheme((value) => setScheme(value)))
  })
  return scheme
}

// packages/react/src/theme/useColorScheme.ts
import * as React from 'react'
import { getColorScheme, watchColorScheme, type ColorScheme } from '@iris-ui-kit/theme'

/**
 * Reactive system color scheme (`'light'` / `'dark'`) from
 * `prefers-color-scheme`. Re-renders the host when the OS preference flips.
 * SSR-safe (reports `'light'` until mounted). Wire it to a theme store to
 * auto-follow the system:
 *
 * ```tsx
 * const scheme = useColorScheme()
 * React.useEffect(() => store.setTheme(scheme === 'dark' ? 'dark' : 'light'), [scheme])
 * ```
 */
export function useColorScheme(): ColorScheme {
  const [scheme, setScheme] = React.useState<ColorScheme>(getColorScheme)
  React.useEffect(() => {
    // Re-sync in case the preference changed between render and effect.
    setScheme(getColorScheme())
    return watchColorScheme(setScheme)
  }, [])
  return scheme
}
