// packages/svelte/src/primitives/dragger/IrisDragger.svelte
<script lang="ts">
  import { useDrag } from '../drag/useDrag.svelte'

  export interface IrisDraggerPosition {
    x: number
    y: number
  }

  interface Props {
    value?: IrisDraggerPosition
    disabled?: boolean
    bounds?: { minX?: number; maxX?: number; minY?: number; maxY?: number }
    onValueChange?: (pos: IrisDraggerPosition) => void
    onDragStart?: (pos: IrisDraggerPosition) => void
    onDragEnd?: (pos: IrisDraggerPosition) => void
    children?: import('svelte').Snippet
    handle?: import('svelte').Snippet
    style?: string
    [key: string]: unknown
  }

  let {
    value = { x: 0, y: 0 },
    disabled = false,
    bounds = {},
    onValueChange,
    onDragStart,
    onDragEnd,
    children,
    handle,
    style,
    ...rest
  }: Props = $props()

  let rootEl = $state<HTMLElement | undefined>(undefined)
  let handleEl = $state<HTMLElement | undefined>(undefined)
  let dragging = $state(false)

  let startPos: IrisDraggerPosition = { x: 0, y: 0 }

  function clamp(pos: IrisDraggerPosition): IrisDraggerPosition {
    return {
      x: Math.max(bounds.minX ?? -Infinity, Math.min(bounds.maxX ?? Infinity, pos.x)),
      y: Math.max(bounds.minY ?? -Infinity, Math.min(bounds.maxY ?? Infinity, pos.y)),
    }
  }

  const effectiveHandle = $derived(handleEl ?? rootEl)

  useDrag({
    handle: () => effectiveHandle,
    disabled: () => disabled,
    onStart: () => {
      startPos = { ...value }
      dragging = true
      onDragStart?.(startPos)
    },
    onDrag: ({ dx, dy }) => {
      onValueChange?.(clamp({ x: startPos.x + dx, y: startPos.y + dy }))
    },
    onEnd: () => {
      dragging = false
      onDragEnd?.({ ...value })
    },
  })

  function setRoot(node: HTMLElement): { destroy: () => void } {
    rootEl = node
    return { destroy: () => { rootEl = undefined } }
  }
  function setHandle(node: HTMLElement): { destroy: () => void } {
    handleEl = node
    return { destroy: () => { handleEl = undefined } }
  }
</script>

<div
  {...rest}
  use:setRoot
  data-iris-dragger
  data-state={dragging ? 'dragging' : 'idle'}
  style="position: absolute; left: 0; top: 0; transform: translate3d({value.x}px, {value.y}px, 0); cursor: {handle ? 'default' : disabled ? 'not-allowed' : 'grab'}; touch-action: none;{style ? ' ' + style : ''}"
>
  {#if handle}
    <div
      use:setHandle
      data-iris-dragger-handle
      style="cursor: {disabled ? 'not-allowed' : 'grab'}; touch-action: none"
    >
      {@render handle()}
    </div>
  {/if}
  {@render children?.()}
</div>

// packages/solid/src/primitives/dragger/IrisDragger.tsx
import { createMemo, createSignal, mergeProps, Show, type JSX } from 'solid-js'
import { useDrag } from '../drag/useDrag'

export interface IrisDraggerPosition {
  x: number
  y: number
}

export interface IrisDraggerProps {
  value?: IrisDraggerPosition
  defaultValue?: IrisDraggerPosition
  onChange?: (pos: IrisDraggerPosition) => void
  onDragStart?: (pos: IrisDraggerPosition) => void
  onDragEnd?: (pos: IrisDraggerPosition) => void
  disabled?: boolean
  bounds?: { minX?: number; maxX?: number; minY?: number; maxY?: number }
  /** If provided, only the handle triggers the drag; the rest is non-draggable. */
  handle?: JSX.Element
  children?: JSX.Element
  style?: JSX.CSSProperties
}

/**
 * Make a child element positionable by drag. Position driven by `value` (px from container origin).
 * Solid port of the Vue IrisDragger.
 */
export function IrisDragger(props: IrisDraggerProps): JSX.Element {
  const merged = mergeProps(
    {
      defaultValue: { x: 0, y: 0 } as IrisDraggerPosition,
      disabled: false,
      bounds: {} as { minX?: number; maxX?: number; minY?: number; maxY?: number },
    },
    props,
  )

  const isControlled = (): boolean => props.value !== undefined
  const [internalValue, setInternalValue] = createSignal<IrisDraggerPosition>(merged.defaultValue)
  const currentValue = (): IrisDraggerPosition =>
    isControlled() ? (props.value ?? { x: 0, y: 0 }) : internalValue()

  const clamp = (pos: IrisDraggerPosition): IrisDraggerPosition => ({
    x: Math.max(merged.bounds.minX ?? -Infinity, Math.min(merged.bounds.maxX ?? Infinity, pos.x)),
    y: Math.max(merged.bounds.minY ?? -Infinity, Math.min(merged.bounds.maxY ?? Infinity, pos.y)),
  })

  const setPosition = (pos: IrisDraggerPosition): void => {
    if (!isControlled()) setInternalValue(pos)
    merged.onChange?.(pos)
  }

  const [rootEl, setRootEl] = createSignal<HTMLElement | null | undefined>()
  const [handleEl, setHandleEl] = createSignal<HTMLElement | null | undefined>()
  const [dragging, setDragging] = createSignal(false)
  let startPos: IrisDraggerPosition = { x: 0, y: 0 }

  // If no handle slot, use root element as the drag handle
  const effectiveHandle = createMemo(() => handleEl() ?? rootEl())

  useDrag({
    handle: effectiveHandle,
    disabled: () => merged.disabled,
    onStart: () => {
      startPos = { ...currentValue() }
      setDragging(true)
      merged.onDragStart?.(startPos)
    },
    onDrag: ({ dx, dy }) => {
      setPosition(clamp({ x: startPos.x + dx, y: startPos.y + dy }))
    },
    onEnd: () => {
      setDragging(false)
      merged.onDragEnd?.({ ...currentValue() })
    },
  })

  const hasHandle = (): boolean => !!merged.handle

  return (
    <div
      ref={setRootEl}
      data-iris-dragger=""
      data-state={dragging() ? 'dragging' : 'idle'}
      style={{
        position: 'absolute',
        left: '0',
        top: '0',
        transform: `translate3d(${currentValue().x}px, ${currentValue().y}px, 0)`,
        cursor: hasHandle() ? 'default' : merged.disabled ? 'not-allowed' : 'grab',
        'touch-action': 'none',
        ...(merged.style ?? {}),
      }}
    >
      <Show when={hasHandle()}>
        <div
          ref={setHandleEl}
          data-iris-dragger-handle=""
          style={{
            cursor: merged.disabled ? 'not-allowed' : 'grab',
            'touch-action': 'none',
          }}
        >
          {merged.handle}
        </div>
      </Show>
      {merged.children}
    </div>
  )
}
