// packages/react/src/primitives/dropdown/Dropdown.tsx
import * as React from 'react'
import { createFloatingMachine, type Placement } from '@iris-ui-kit/core'
import { useMachine } from '../../useMachine'
import { DropdownContext } from './context'

export interface IrisDropdownProps {
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  placement?: Placement
  offset?: number
  children?: React.ReactNode
}

/**
 * Dropdown menu root. Composes `createFloatingMachine` (state) with
 * `useFloating` (positioning) used in `IrisDropdownMenu`. The dropdown
 * panel's semantics differ from a popover: it uses `role="menu"`, supports
 * arrow-key navigation, and items auto-close the menu on select.
 *
 * @example
 *   <IrisDropdown placement="bottom-end">
 *     <IrisDropdownTrigger>Actions</IrisDropdownTrigger>
 *     <IrisDropdownMenu>
 *       <IrisDropdownItem onSelect={onCopy}>Copy</IrisDropdownItem>
 *       <IrisDropdownItem onSelect={onDelete}>Delete</IrisDropdownItem>
 *     </IrisDropdownMenu>
 *   </IrisDropdown>
 */
export function IrisDropdown({
  open: openProp,
  defaultOpen = false,
  onOpenChange,
  placement = 'bottom-start',
  offset = 6,
  children,
}: IrisDropdownProps): React.ReactElement {
  const isControlled = openProp !== undefined

  const [state, send] = useMachine(() => createFloatingMachine(defaultOpen ? 'open' : 'closed'))
  const internalOpen = state.value === 'open'

  React.useEffect(() => {
    if (!isControlled) return
    const target = openProp ? 'open' : 'closed'
    if (state.value !== target) {
      send({ type: openProp ? 'OPEN' : 'CLOSE' })
    }
  }, [isControlled, openProp, state.value, send])

  const open = isControlled ? Boolean(openProp) : internalOpen

  const setOpen = React.useCallback(
    (next: boolean) => {
      if (!isControlled) send({ type: next ? 'OPEN' : 'CLOSE' })
      onOpenChange?.(next)
    },
    [isControlled, send, onOpenChange],
  )

  const triggerRef = React.useRef<HTMLElement | null>(null)
  const contentRef = React.useRef<HTMLElement | null>(null)
  const contentId = React.useId()

  const value = React.useMemo(
    () => ({
      open,
      setOpen,
      triggerRef,
      contentRef,
      contentId,
      placement,
      offset,
    }),
    [open, setOpen, contentId, placement, offset],
  )

  return <DropdownContext.Provider value={value}>{children}</DropdownContext.Provider>
}

// packages/solid/src/primitives/dropdown/Dropdown.tsx
import { createEffect, createSignal, createUniqueId, mergeProps, type JSX } from 'solid-js'
import { createFloatingMachine, type Placement } from '@iris-ui-kit/core'
import { useMachine } from '../../useMachine'
import { DropdownContext } from './context'

export interface IrisDropdownProps {
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  placement?: Placement
  offset?: number
  children?: JSX.Element
}

/**
 * Dropdown menu root. Composes `createFloatingMachine` (state) with
 * `useFloating` (positioning, in `IrisDropdownMenu`). `role="menu"` semantics +
 * arrow-key nav + auto-close on select. Solid port of the React/Vue dropdown.
 */
export function IrisDropdown(props: IrisDropdownProps): JSX.Element {
  const merged = mergeProps(
    { defaultOpen: false, placement: 'bottom-start' as Placement, offset: 6 },
    props,
  )
  const isControlled = (): boolean => props.open !== undefined

  const [state, send] = useMachine(() =>
    createFloatingMachine(merged.defaultOpen ? 'open' : 'closed'),
  )
  const internalOpen = (): boolean => state().value === 'open'

  createEffect(() => {
    if (!isControlled()) return
    const target = props.open ? 'open' : 'closed'
    if (state().value !== target) send({ type: props.open ? 'OPEN' : 'CLOSE' })
  })

  const open = (): boolean => (isControlled() ? Boolean(props.open) : internalOpen())
  const setOpen = (next: boolean): void => {
    if (!isControlled()) send({ type: next ? 'OPEN' : 'CLOSE' })
    merged.onOpenChange?.(next)
  }

  const [trigger, setTrigger] = createSignal<HTMLElement | undefined>()
  const [content, setContent] = createSignal<HTMLElement | undefined>()
  const contentId = createUniqueId()

  return (
    <DropdownContext.Provider
      value={{
        open,
        setOpen,
        trigger,
        setTrigger,
        content,
        setContent,
        contentId,
        get placement() {
          return merged.placement
        },
        get offset() {
          return merged.offset
        },
      }}
    >
      {props.children}
    </DropdownContext.Provider>
  )
}
