// packages/svelte/src/primitives/cascader/IrisCascader.svelte
<script lang="ts">
  import { generateId } from '@iris-ui-kit/core'
  import { useI18n } from '../../i18n'
  import IrisVirtualScroll from '../virtual-scroll/IrisVirtualScroll.svelte'

  export interface IrisCascaderNode {
    label: string
    value: string
    disabled?: boolean
    children?: IrisCascaderNode[]
  }

  export type IrisCascaderSize = 'sm' | 'md' | 'lg'

  interface Props {
    options?: IrisCascaderNode[]
    value?: string[]
    placeholder?: string
    disabled?: boolean
    invalid?: boolean
    separator?: string
    size?: IrisCascaderSize
    /**
     * Opt-in: window each open column with the core virtualizer instead of
     * rendering every option. Fixed deterministic sizing (viewport 240px, row
     * height per size, buffer 4). Default false — no behavior change.
     */
    virtual?: boolean
    id?: string
    onValueChange?: (path: string[]) => void
    style?: string
    class?: string
  }

  const SIZE_MAP: Record<
    IrisCascaderSize,
    { padding: string; fontSize: string; minHeight: string }
  > = {
    sm: {
      padding: 'var(--iris-space-xxs, 4px) var(--iris-space-xs, 8px)',
      fontSize: 'var(--iris-font-size-xs, 12px)',
      minHeight: '28px',
    },
    md: {
      padding: 'var(--iris-padding-sm, 6px) var(--iris-padding-md, 12px)',
      fontSize: 'var(--iris-font-size-md, 14px)',
      minHeight: '34px',
    },
    lg: {
      padding: 'var(--iris-space-xs, 8px) var(--iris-padding-md, 12px)',
      fontSize: 'var(--iris-font-size-lg, 16px)',
      minHeight: '40px',
    },
  }

  /** Matches the current `maxHeight: 240` of a column. */
  const CASCADER_COLUMN_VIEWPORT = 240
  /** Fixed row heights, aligned with SIZE_MAP minHeights so rows never clip. */
  const CASCADER_ROW_HEIGHT: Record<IrisCascaderSize, number> = { sm: 28, md: 34, lg: 40 }
  /** Extra rows rendered above and below the visible window. */
  const CASCADER_VIRTUAL_BUFFER = 4

  let {
    options = [],
    value = [],
    placeholder,
    disabled = false,
    invalid = false,
    separator = ' / ',
    size = 'md',
    id,
    onValueChange,
    style,
    class: className,
    virtual = false,
    ...rest
  }: Props = $props()

  const { t } = useI18n()
  const popupId = `${generateId()}-popup`

  let open = $state(false)
  let activePath = $state<string[]>([])
  let containerEl = $state<HTMLElement | undefined>(undefined)

  function pathLabels(nodes: IrisCascaderNode[], path: string[]): string[] {
    const labels: string[] = []
    let level = nodes
    for (const v of path) {
      const node = level.find((n) => n.value === v)
      if (!node) break
      labels.push(node.label)
      level = node.children ?? []
    }
    return labels
  }

  function buildColumns(nodes: IrisCascaderNode[], path: string[]): IrisCascaderNode[][] {
    const cols: IrisCascaderNode[][] = [nodes]
    let level = nodes
    for (const v of path) {
      const node = level.find((n) => n.value === v)
      if (!node || !node.children || node.children.length === 0) break
      level = node.children
      cols.push(level)
    }
    return cols
  }

  const labels = $derived(pathLabels(options, value))
  const display = $derived(labels.join(separator))
  const columns = $derived(buildColumns(options, activePath))

  function toggle() {
    if (disabled) return
    if (!open) activePath = [...value]
    open = !open
  }

  // Trigger keyboard: Escape closes; ArrowDown/Enter open (mirrors React/Vue).
  function onTriggerKeyDown(e: KeyboardEvent) {
    if (e.key === 'Escape' && open) {
      e.preventDefault()
      open = false
    } else if ((e.key === 'ArrowDown' || e.key === 'Enter') && !open) {
      e.preventDefault()
      if (!disabled) {
        activePath = [...value]
        open = true
      }
    }
  }

  function selectOption(colIndex: number, node: IrisCascaderNode) {
    if (node.disabled) return
    const nextPath = [...activePath.slice(0, colIndex), node.value]
    activePath = nextPath
    const hasChildren = !!node.children && node.children.length > 0
    if (!hasChildren) {
      onValueChange?.(nextPath)
      open = false
    }
  }

  function onDocDown(e: MouseEvent) {
    if (open && containerEl && !containerEl.contains(e.target as Node)) open = false
  }

  $effect(() => {
    if (open) document.addEventListener('mousedown', onDocDown)
    else document.removeEventListener('mousedown', onDocDown)
    return () => document.removeEventListener('mousedown', onDocDown)
  })

  // Keep the next-open navigation path aligned with a controlled value update.
  $effect(() => {
    if (!open) activePath = [...value]
  })

  const sz = $derived(SIZE_MAP[size])
  const borderColor = $derived(invalid ? 'var(--iris-danger)' : 'var(--iris-border)')
</script>

<!-- svelte-ignore a11y_click_events_have_key_events a11y_role_supports_aria_props_implicit -->

<div
  bind:this={containerEl}
  data-iris-cascader
  data-disabled={disabled ? '' : undefined}
  style:position="relative"
  style:display="inline-flex"
  {style}
  class={className}
  {...rest}
>
  <button
    type="button"
    role="combobox"
    {id}
    {disabled}
    aria-invalid={invalid ? 'true' : undefined}
    aria-expanded={open}
    aria-controls={popupId}
    aria-haspopup="listbox"
    data-iris-cascader-trigger
    onkeydown={onTriggerKeyDown}
    data-state={open ? 'open' : 'closed'}
    onclick={toggle}
    style:display="inline-flex"
    style:align-items="center"
    style:justify-content="space-between"
    style:gap="var(--iris-space-xs, 8px)"
    style:padding={sz.padding}
    style:font-size={sz.fontSize}
    style:min-height={sz.minHeight}
    style:min-width="160px"
    style:background="var(--iris-background)"
    style:color={value.length > 0 ? 'var(--iris-foreground)' : 'var(--iris-muted)'}
    style:border={`1px solid ${borderColor}`}
    style:border-radius="var(--iris-radius-md, 6px)"
    style:cursor={disabled ? 'not-allowed' : 'pointer'}
    style:font-family="inherit"
  >
    <span style:flex="1" style:text-align="start"
      >{display || (placeholder ?? t('select.placeholder'))}</span
    >
    <span aria-hidden="true" style:font-size="var(--iris-font-size-xs, 12px)"
      >{open ? '▲' : '▼'}</span
    >
  </button>

  {#if open}
    <div
      id={popupId}
      data-iris-cascader-dropdown
      style:position="absolute"
      style:top="calc(100% + 4px)"
      style:left="0"
      style:z-index="50"
      style:display="flex"
      style:background="var(--iris-background)"
      style:border="1px solid var(--iris-border)"
      style:border-radius="var(--iris-radius-md, 6px)"
      style:box-shadow="var(--iris-shadow-lg)"
      style:overflow="hidden"
    >
      {#each columns as col, colIdx (colIdx)}
        {#if colIdx > 0}
          <div style:width="1px" style:background="var(--iris-border)"></div>
        {/if}
        {#if virtual}
          <IrisVirtualScroll
            items={col}
            itemHeight={CASCADER_ROW_HEIGHT[size]}
            height={CASCADER_COLUMN_VIEWPORT}
            buffer={CASCADER_VIRTUAL_BUFFER}
            keyOf={(item) => (item as IrisCascaderNode).value}
            role="listbox"
            aria-label={t('cascader.level', { level: colIdx + 1 })}
            style="min-width: 140px"
          >
            {#snippet item(slotData)}
              {@const node = slotData.item as IrisCascaderNode}
              {@render optionItem(node, colIdx, true)}
            {/snippet}
          </IrisVirtualScroll>
        {:else}
          <ul
            role="listbox"
            aria-label={t('cascader.level', { level: colIdx + 1 })}
            style:min-width="140px"
            style:max-height="240px"
            style:overflow-y="auto"
            style:margin="0"
            style:padding="4px"
            style:list-style="none"
            style:padding-inline-start="0"
            style:margin-block="0"
          >
            {#each col as node (node.value)}
              {@render optionItem(node, colIdx, false)}
            {/each}
          </ul>
        {/if}
      {/each}
    </div>
  {/if}
</div>

<!-- Shared option renderer — used by BOTH the plain and the virtual column
     paths so the a11y attribute surface is structurally identical. When
     virtual, the virtualizer pins each row's height, so the option fills the
     row (height 100% + border-box keeps the padding inside it). -->
{#snippet optionItem(node: IrisCascaderNode, colIdx: number, fill: boolean)}
  {@const isActive = activePath[colIdx] === node.value}
  {@const hasChildren = node.children !== undefined && node.children.length > 0}
  <li
    role="option"
    aria-selected={isActive}
    aria-disabled={node.disabled ? 'true' : undefined}
    data-iris-cascader-item
    data-state={isActive ? 'selected' : 'idle'}
    onclick={() => selectOption(colIdx, node)}
    onkeydown={(event) => {
      if (event.key === 'Enter' || event.key === ' ') {
        event.preventDefault()
        selectOption(colIdx, node)
      }
    }}
    tabindex={node.disabled ? -1 : 0}
    style:display="flex"
    style:align-items="center"
    style:justify-content="space-between"
    style:gap="8px"
    style:padding="var(--iris-space-xs, 8px) var(--iris-padding-md, 12px)"
    style:cursor={node.disabled ? 'not-allowed' : 'pointer'}
    style:border-radius="var(--iris-radius-sm, 4px)"
    style:background={isActive ? 'var(--iris-surface-hover)' : 'transparent'}
    style:color={node.disabled ? 'var(--iris-muted)' : 'var(--iris-foreground)'}
    style:font-size={sz.fontSize}
    style:opacity={node.disabled ? '0.5' : '1'}
    style:height={fill ? '100%' : undefined}
    style:box-sizing={fill ? 'border-box' : undefined}
  >
    <span>{node.label}</span>
    {#if hasChildren}
      <span aria-hidden="true" style:font-size="var(--iris-font-size-xs, 12px)">›</span>
    {/if}
  </li>
{/snippet}

// packages/solid/src/primitives/cascader/IrisCascader.tsx
import {
  createSignal,
  createMemo,
  mergeProps,
  splitProps,
  Show,
  For,
  onCleanup,
  type JSX,
} from 'solid-js'
import { useI18n } from '../../i18n'
import { IrisVirtualScroll } from '../virtual-scroll/IrisVirtualScroll'

export interface IrisCascaderNode {
  label: string
  value: string
  disabled?: boolean
  children?: IrisCascaderNode[]
}

function pathLabels(options: IrisCascaderNode[], path: string[]): string[] {
  const labels: string[] = []
  let level = options
  for (const v of path) {
    const node = level.find((n) => n.value === v)
    if (!node) break
    labels.push(node.label)
    level = node.children ?? []
  }
  return labels
}

function buildColumns(options: IrisCascaderNode[], activePath: string[]): IrisCascaderNode[][] {
  const cols: IrisCascaderNode[][] = [options]
  let level = options
  for (const v of activePath) {
    const node = level.find((n) => n.value === v)
    if (!node || !node.children || node.children.length === 0) break
    level = node.children
    cols.push(level)
  }
  return cols
}

/** Matches the current `maxHeight: 240` of a column. */
const CASCADER_COLUMN_VIEWPORT = 240
/** Fixed row height (md — the solid cascader has no size prop). */
const CASCADER_ROW_HEIGHT = 34
/** Extra rows rendered above and below the visible window. */
const CASCADER_VIRTUAL_BUFFER = 4

export interface IrisCascaderProps {
  options?: IrisCascaderNode[]
  value?: string[]
  defaultValue?: string[]
  placeholder?: string
  disabled?: boolean
  invalid?: boolean
  separator?: string
  onChange?: (path: string[]) => void
  /**
   * Opt-in: window each open column with the core virtualizer instead of
   * rendering every option. Fixed deterministic sizing (viewport 240px, row
   * height 34px, buffer 4). Default false — no behavior change.
   */
  virtual?: boolean
  id?: string
}

/**
 * Cascader: hierarchical multi-level select. Click a branch to drill down;
 * click a leaf to commit the full path.
 * Solid port of the Vue IrisCascader.
 */
export function IrisCascader(props: IrisCascaderProps): JSX.Element {
  const merged = mergeProps(
    {
      options: [] as IrisCascaderNode[],
      defaultValue: [] as string[],
      disabled: false,
      invalid: false,
      separator: ' / ',
      virtual: false,
    },
    props,
  )
  const [local] = splitProps(merged, [
    'options',
    'value',
    'defaultValue',
    'placeholder',
    'disabled',
    'invalid',
    'separator',
    'onChange',
    'virtual',
    'id',
  ])

  const { t } = useI18n()

  const [internalValue, setInternalValue] = createSignal<string[]>(local.defaultValue)
  const [open, setOpen] = createSignal(false)
  const [activePath, setActivePath] = createSignal<string[]>([])

  const currentValue = () => (local.value !== undefined ? local.value : internalValue())

  const displayLabel = createMemo(() => {
    const labels = pathLabels(local.options, currentValue())
    return labels.length > 0 ? labels.join(local.separator) : ''
  })

  const columns = createMemo(() => buildColumns(local.options, activePath()))

  const onTriggerClick = () => {
    if (local.disabled) return
    const next = !open()
    setOpen(next)
    if (next) setActivePath([...currentValue()])
  }

  const onOptionClick = (colIdx: number, node: IrisCascaderNode) => {
    if (node.disabled) return
    const newPath = [...activePath().slice(0, colIdx), node.value]
    setActivePath(newPath)
    const isLeaf = !node.children || node.children.length === 0
    if (isLeaf) {
      if (local.value === undefined) setInternalValue(newPath)
      local.onChange?.(newPath)
      setOpen(false)
    }
  }

  // Shared option renderer — used by BOTH the plain and the virtual column
  // paths so the a11y attribute surface is structurally identical. When
  // virtual, the virtualizer pins each row's height, so the option fills the
  // row (height 100% + border-box keeps the padding inside it).
  const renderOption = (
    colIdx: () => number,
    node: IrisCascaderNode,
    fill: boolean,
  ): JSX.Element => {
    const isActive = () => activePath()[colIdx()] === node.value
    const hasChildren = () => (node.children?.length ?? 0) > 0
    return (
      <li
        role="option"
        aria-selected={isActive()}
        aria-disabled={node.disabled ? 'true' : undefined}
        data-iris-cascader-option={node.value}
        onClick={() => onOptionClick(colIdx(), node)}
        style={{
          display: 'flex',
          'align-items': 'center',
          'justify-content': 'space-between',
          padding: 'var(--iris-space-xs, 8px) var(--iris-space-sm, 12px)',
          'border-radius': 'var(--iris-radius-sm, 4px)',
          cursor: node.disabled ? 'not-allowed' : 'pointer',
          background: isActive() ? 'var(--iris-primary)' : 'transparent',
          color: isActive()
            ? 'var(--iris-primary-foreground, #fff)'
            : node.disabled
              ? 'var(--iris-muted)'
              : 'var(--iris-foreground)',
          opacity: node.disabled ? '0.5' : '1',
          'font-size': 'var(--iris-font-size-md, 14px)',
          ...(fill ? { height: '100%', 'box-sizing': 'border-box' } : {}),
        }}
      >
        <span>{node.label}</span>
        <Show when={hasChildren()}>
          <span aria-hidden="true" style={{ 'margin-left': '8px', opacity: '0.6' }}>
            ›
          </span>
        </Show>
      </li>
    )
  }

  // Close on click outside
  const onDocClick = (e: MouseEvent) => {
    if (!(e.target as HTMLElement).closest('[data-iris-cascader]')) {
      setOpen(false)
    }
  }
  document.addEventListener('click', onDocClick)
  onCleanup(() => document.removeEventListener('click', onDocClick))

  return (
    <div
      data-iris-cascader=""
      data-disabled={local.disabled ? '' : undefined}
      style={{ position: 'relative', display: 'inline-block' }}
    >
      <button
        id={local.id}
        type="button"
        data-iris-cascader-trigger=""
        data-state={open() ? 'open' : 'closed'}
        disabled={local.disabled || undefined}
        aria-invalid={local.invalid ? 'true' : undefined}
        aria-haspopup="listbox"
        aria-expanded={open()}
        onClick={onTriggerClick}
        onKeyDown={(e: KeyboardEvent) => {
          if (e.key === 'Escape' && open()) {
            e.preventDefault()
            setOpen(false)
          } else if ((e.key === 'ArrowDown' || e.key === 'Enter') && !open()) {
            e.preventDefault()
            if (!local.disabled) {
              setOpen(true)
              setActivePath([...currentValue()])
            }
          }
        }}
        style={{
          display: 'inline-flex',
          'align-items': 'center',
          gap: '8px',
          padding: 'var(--iris-padding-sm, 6px) var(--iris-padding-md, 12px)',
          background: 'var(--iris-surface)',
          border: `1px solid ${local.invalid ? 'var(--iris-danger)' : 'var(--iris-border)'}`,
          'border-radius': 'var(--iris-radius-md, 6px)',
          color: displayLabel() ? 'var(--iris-foreground)' : 'var(--iris-muted)',
          'font-size': 'var(--iris-font-size-md, 14px)',
          'font-family': 'inherit',
          cursor: local.disabled ? 'not-allowed' : 'pointer',
          'min-width': '160px',
        }}
      >
        <span style={{ flex: '1', 'text-align': 'start' }}>
          {displayLabel() || (local.placeholder ?? t('select.placeholder'))}
        </span>
        <span aria-hidden="true">▾</span>
      </button>

      <Show when={open()}>
        <div
          data-iris-cascader-dropdown=""
          style={{
            position: 'absolute',
            top: '100%',
            left: '0',
            'z-index': '100',
            'margin-top': '4px',
            display: 'flex',
            background: 'var(--iris-surface)',
            border: '1px solid var(--iris-border)',
            'border-radius': 'var(--iris-radius-md, 6px)',
            'box-shadow': 'var(--iris-shadow-lg)',
            overflow: 'hidden',
          }}
        >
          <For each={columns()}>
            {(col, colIdx) =>
              local.virtual ? (
                <IrisVirtualScroll
                  items={col}
                  itemHeight={CASCADER_ROW_HEIGHT}
                  height={CASCADER_COLUMN_VIEWPORT}
                  buffer={CASCADER_VIRTUAL_BUFFER}
                  keyOf={(node: IrisCascaderNode) => node.value}
                  renderItem={(node: IrisCascaderNode) => renderOption(colIdx, node, true)}
                  role="listbox"
                  data-iris-cascader-column={colIdx()}
                  style={{
                    'min-width': '140px',
                    'border-right':
                      colIdx() < columns().length - 1 ? '1px solid var(--iris-border)' : 'none',
                  }}
                />
              ) : (
                <ul
                  data-iris-cascader-column={colIdx()}
                  role="listbox"
                  style={{
                    'list-style': 'none',
                    margin: '0',
                    padding: '4px',
                    'min-width': '140px',
                    'max-height': '240px',
                    'overflow-y': 'auto',
                    'border-right':
                      colIdx() < columns().length - 1 ? '1px solid var(--iris-border)' : 'none',
                  }}
                >
                  <For each={col}>{(node) => renderOption(colIdx, node, false)}</For>
                </ul>
              )
            }
          </For>
        </div>
      </Show>
    </div>
  )
}
