// packages/solid/src/primitives/date-range-picker/IrisDateRangePicker.tsx
import { createSignal, createMemo, mergeProps, splitProps, Show, type JSX } from 'solid-js'
import { IrisCalendar } from '../calendar/IrisCalendar'
import { startOfDay, safeLocale } from '../calendar/dateUtils'
import { useI18n } from '../../i18n'

function formatDisplay(date: Date | null | undefined, locale?: string): string {
  if (!date) return ''
  return new Intl.DateTimeFormat(safeLocale(locale), { dateStyle: 'medium' }).format(date)
}

export interface IrisDateRange {
  start: Date | null
  end: Date | null
}

export interface IrisDateRangePickerProps {
  value?: IrisDateRange
  defaultValue?: IrisDateRange
  min?: Date
  max?: Date
  weekStartsOn?: number
  locale?: string
  placeholder?: string
  disabled?: boolean
  onChange?: (range: IrisDateRange) => void
}

/**
 * Date range picker: two input buttons + dual calendar panel for [start, end].
 * Solid port of the Vue IrisDateRangePicker.
 */
export function IrisDateRangePicker(props: IrisDateRangePickerProps): JSX.Element {
  const merged = mergeProps(
    {
      defaultValue: { start: null, end: null } as IrisDateRange,
      disabled: false,
      weekStartsOn: 0,
    },
    props,
  )
  const [local] = splitProps(merged, [
    'value',
    'defaultValue',
    'min',
    'max',
    'weekStartsOn',
    'locale',
    'placeholder',
    'disabled',
    'onChange',
  ])

  const { t } = useI18n()

  const [internalValue, setInternalValue] = createSignal<IrisDateRange>(local.defaultValue)
  const [open, setOpen] = createSignal(false)
  const [selecting, setSelecting] = createSignal<'start' | 'end'>('start')

  const currentValue = (): IrisDateRange =>
    local.value !== undefined ? local.value : internalValue()

  const displayStart = createMemo(() => formatDisplay(currentValue().start, local.locale))
  const displayEnd = createMemo(() => formatDisplay(currentValue().end, local.locale))

  const onSelect = (date: Date | null) => {
    if (!date) return
    const d = startOfDay(date)
    const current = currentValue()

    if (selecting() === 'start') {
      const newRange = { start: d, end: current.end && current.end >= d ? current.end : null }
      if (local.value === undefined) setInternalValue(newRange)
      local.onChange?.(newRange)
      setSelecting('end')
    } else {
      let newRange: IrisDateRange
      if (current.start && d < current.start) {
        newRange = { start: d, end: current.start }
      } else {
        newRange = { start: current.start, end: d }
      }
      if (local.value === undefined) setInternalValue(newRange)
      local.onChange?.(newRange)
      setOpen(false)
      setSelecting('start')
    }
  }

  return (
    <div
      data-iris-date-range-picker=""
      style={{ position: 'relative', display: 'inline-flex', gap: '4px', 'align-items': 'center' }}
    >
      <button
        type="button"
        disabled={local.disabled || undefined}
        aria-haspopup="dialog"
        aria-expanded={open()}
        data-iris-date-range-picker-start=""
        data-state={open() && selecting() === 'start' ? 'selecting' : 'idle'}
        onClick={() => {
          if (local.disabled) return
          setSelecting('start')
          setOpen(true)
        }}
        style={{
          padding: '6px 12px',
          background: 'var(--iris-surface)',
          border: '1px solid var(--iris-border)',
          'border-radius': 'var(--iris-radius-md, 6px)',
          color: displayStart() ? 'var(--iris-foreground)' : 'var(--iris-muted)',
          'font-size': '14px',
          'font-family': 'inherit',
          cursor: local.disabled ? 'not-allowed' : 'pointer',
          'min-width': '120px',
        }}
      >
        {displayStart() || (local.placeholder ?? t('dateRangePicker.start'))}
      </button>
      <span aria-hidden="true" style={{ color: 'var(--iris-muted)' }}>
        →
      </span>
      <button
        type="button"
        disabled={local.disabled || undefined}
        aria-haspopup="dialog"
        aria-expanded={open()}
        data-iris-date-range-picker-end=""
        data-state={open() && selecting() === 'end' ? 'selecting' : 'idle'}
        onClick={() => {
          if (local.disabled) return
          setSelecting('end')
          setOpen(true)
        }}
        style={{
          padding: '6px 12px',
          background: 'var(--iris-surface)',
          border: '1px solid var(--iris-border)',
          'border-radius': 'var(--iris-radius-md, 6px)',
          color: displayEnd() ? 'var(--iris-foreground)' : 'var(--iris-muted)',
          'font-size': '14px',
          'font-family': 'inherit',
          cursor: local.disabled ? 'not-allowed' : 'pointer',
          'min-width': '120px',
        }}
      >
        {displayEnd() || (local.placeholder ?? t('dateRangePicker.end'))}
      </button>

      <Show when={open()}>
        <div
          role="dialog"
          data-iris-date-range-picker-panel=""
          style={{
            position: 'absolute',
            top: '100%',
            left: '0',
            'z-index': '100',
            'margin-top': '4px',
            'box-shadow': '0 4px 16px rgba(0,0,0,0.12)',
            'border-radius': 'var(--iris-radius-md, 6px)',
          }}
          onMouseDown={(e) => e.preventDefault()}
        >
          <IrisCalendar
            value={selecting() === 'start' ? currentValue().start : currentValue().end}
            min={local.min}
            max={local.max}
            weekStartsOn={local.weekStartsOn}
            locale={local.locale}
            onChange={onSelect}
          />
        </div>
      </Show>
    </div>
  )
}

// packages/svelte/src/primitives/date-range-picker/IrisDateRangePicker.svelte
<script lang="ts">
  import IrisCalendar from '../calendar/IrisCalendar.svelte'
  import { startOfDay, safeLocale } from '../calendar/dateUtils'
  import { useI18n } from '../../i18n'

  const { t } = useI18n()

  interface DateRange {
    start: Date | null
    end: Date | null
  }

  interface Props {
    value?: DateRange
    min?: Date
    max?: Date
    weekStartsOn?: number
    locale?: string
    disabled?: boolean
    invalid?: boolean
    startPlaceholder?: string
    endPlaceholder?: string
    onValueChange?: (range: DateRange) => void
    style?: string
    class?: string
  }

  let {
    value = { start: null, end: null },
    min,
    max,
    weekStartsOn = 0,
    locale,
    disabled = false,
    invalid = false,
    startPlaceholder,
    endPlaceholder,
    onValueChange,
    style,
    class: className,
    ...rest
  }: Props = $props()

  let open = $state(false)
  // picking = 'start' | 'end'
  let picking = $state<'start' | 'end'>('start')
  let containerEl = $state<HTMLElement | undefined>(undefined)

  function fmt(d: Date | null): string {
    if (!d) return ''
    return new Intl.DateTimeFormat(safeLocale(locale), { dateStyle: 'medium' }).format(d)
  }

  function openPicker(side: 'start' | 'end') {
    if (disabled) return
    picking = side
    open = true
  }

  function onSelect(date: Date | null) {
    if (!date) return
    const d = startOfDay(date)
    if (picking === 'start') {
      const newRange: DateRange = { start: d, end: value.end }
      // If start > end, clear end
      if (newRange.end && d > newRange.end) newRange.end = null
      onValueChange?.(newRange)
      picking = 'end'
    } else {
      let newRange: DateRange
      if (value.start && d < value.start) {
        // Swap
        newRange = { start: d, end: value.start }
      } else {
        newRange = { start: value.start, end: d }
      }
      onValueChange?.(newRange)
      open = false
    }
  }

  function onDocDown(e: MouseEvent) {
    if (open && containerEl && !containerEl.contains(e.target as Node)) open = false
  }

  $effect(() => {
    if (open) {
      document.addEventListener('mousedown', onDocDown)
    } else {
      document.removeEventListener('mousedown', onDocDown)
    }
    return () => document.removeEventListener('mousedown', onDocDown)
  })
</script>

<div
  bind:this={containerEl}
  data-iris-date-range-picker
  style:position="relative"
  style:display="inline-flex"
  style:align-items="center"
  style:gap="4px"
  {style}
  class={className}
  {...rest}
>
  <button
    type="button"
    data-iris-date-range-picker-start
    aria-label={t('dateRangePicker.start')}
    {disabled}
    onclick={() => openPicker('start')}
    style:padding="6px 12px"
    style:background="var(--iris-background)"
    style:color={value.start ? 'var(--iris-foreground)' : 'var(--iris-muted)'}
    style:border={`1px solid ${invalid ? 'var(--iris-danger)' : 'var(--iris-border)'}`}
    style:border-radius="var(--iris-radius-md, 6px)"
    style:cursor={disabled ? 'not-allowed' : 'pointer'}
    style:font-size="14px"
    style:font-family="inherit"
    style:min-height="34px"
    style:min-width="140px"
    >{fmt(value.start) || (startPlaceholder ?? t('dateRangePicker.start'))}</button
  >

  <span aria-hidden="true" style:color="var(--iris-muted)">–</span>

  <button
    type="button"
    data-iris-date-range-picker-end
    aria-label={t('dateRangePicker.end')}
    {disabled}
    onclick={() => openPicker('end')}
    style:padding="6px 12px"
    style:background="var(--iris-background)"
    style:color={value.end ? 'var(--iris-foreground)' : 'var(--iris-muted)'}
    style:border={`1px solid ${invalid ? 'var(--iris-danger)' : 'var(--iris-border)'}`}
    style:border-radius="var(--iris-radius-md, 6px)"
    style:cursor={disabled ? 'not-allowed' : 'pointer'}
    style:font-size="14px"
    style:font-family="inherit"
    style:min-height="34px"
    style:min-width="140px">{fmt(value.end) || (endPlaceholder ?? t('dateRangePicker.end'))}</button
  >

  {#if open}
    <div
      data-iris-date-range-picker-content
      role="dialog"
      aria-modal="true"
      style:position="absolute"
      style:top="calc(100% + 4px)"
      style:left="0"
      style:z-index="50"
    >
      <IrisCalendar
        value={picking === 'start' ? value.start : value.end}
        {min}
        {max}
        {weekStartsOn}
        {locale}
        {disabled}
        onValueChange={onSelect}
        style="border: none;"
      />
    </div>
  {/if}
</div>
