// apps/desktop-os-svelte/src/App.svelte
<script lang="ts">
  import { serializeSession, restoreSession, type WindowSession } from '@iris-ui-kit/core/window'
  import { type VfsState } from '@iris-ui-kit/core/fs'
  import { barInsets } from './os'
  import { useOs } from './os-state.svelte'
  import { wm } from './wm.svelte'
  import { profile } from './profile.svelte'
  import { fs } from './fs.svelte'
  import { getManifest, registerCustomApps, type AppManifest } from './catalog'
  import Desktop from './Desktop.svelte'

  let rootEl: HTMLDivElement | undefined = $state()

  // ── Window-session persistence ─────────────────────────────────────────────
  // Open windows (geometry, state, stacking, focus) survive a reload: restored
  // ONCE after hydrate, then re-saved (debounced) on every WM change. Mirrors the
  // React shell (apps/desktop-os/src/App.tsx). `restored` is a plain (non-reactive)
  // guard so the debounced save can never overwrite the saved session before restore.
  let restored = false

  // ── Virtual file-system persistence ────────────────────────────────────────
  // User files survive a reload: hydrated ONCE from the profile `fs` pref (or
  // seeded with a starter set), then re-saved (debounced) on every fs change.
  // Mirrors the React shell (apps/desktop-os/src/App.tsx). `fsReady` is a plain
  // (non-reactive) guard so the debounced save can't overwrite the saved state
  // before hydrate runs.
  let fsReady = false

  /** Seed the fs from the saved `fs` pref, or a starter set of files. */
  function hydrateFs(): void {
    const saved = profile.getPref<VfsState>('fs')
    if (saved && Array.isArray(saved.folders) && saved.files) {
      fs.store.setState(() => saved)
    } else if (Object.keys(fs.getState().files).length === 0) {
      fs.write(
        '/Documents/Welcome.txt',
        'Welcome to Iris Desktop OS.\n\nThis Files app is a real virtual file system — create folders and text files, rename, delete. It persists to your profile and survives a reload.',
      )
      fs.write(
        '/Documents/notes.md',
        '# Notes\n\n- Backed by @iris-ui-kit/core/fs\n- The same engine drives all four shells.',
      )
      fs.mkdir('/Pictures')
    }
  }

  /** The saved session, filtered to apps that still resolve (removed apps skipped). */
  function knownSession(): WindowSession {
    const raw = profile.getPref<WindowSession>('session')
    if (!Array.isArray(raw)) return []
    // Custom (URL-added) apps live in prefs — register them so getManifest resolves.
    registerCustomApps((profile.getPref<AppManifest[]>('customApps') ?? []) as AppManifest[])
    return raw.filter((e) => Boolean(getManifest(e.appId)))
  }

  // The live OS skin (Win11 / macOS). Its `chrome.vars` are written onto the
  // desktop root inline (replacing the hardcoded Win11 vars in style.css) so a
  // skin switch re-skins everything live, and its `barInsets` drive the WM work
  // area so maximize / snap track the taskbar vs. the menu-bar + dock.
  const osCtx = useOs()
  const chrome = $derived(osCtx.chrome)
  // The chrome's CSS custom properties as a `--key:value;…` inline-style string.
  const skinStyle = $derived(
    Object.entries(chrome.vars)
      .map(([k, v]) => `${k}:${v}`)
      .join(';'),
  )

  // Load the user profile (installed apps + custom web apps + prefs) from storage
  // once at startup. Hydration is async; the desktop renders immediately and the
  // installed/custom apps appear in the launchers when it lands. Once hydrated,
  // restore the saved window session (the work-area effect below has already run
  // synchronously on mount, so restored geometry clamps correctly).
  $effect(() => {
    void profile.hydrate().then(() => {
      if (!fsReady) {
        fsReady = true
        hydrateFs()
      }
      if (restored) return
      restored = true
      if (wm.getState().windows.length === 0) restoreSession(wm, knownSession())
    })
  })

  // Persist the window session (debounced) on every WM change, once restore ran.
  $effect(() => {
    let timer: ReturnType<typeof setTimeout> | undefined
    const unsubscribe = wm.subscribe(() => {
      if (!restored) return
      clearTimeout(timer)
      timer = setTimeout(() => profile.setPref('session', serializeSession(wm.getState())), 400)
    })
    return () => {
      clearTimeout(timer)
      unsubscribe()
    }
  })

  // Persist the virtual file system (debounced) on every fs change, once hydrate
  // ran — so user files (and folder structure) survive a reload.
  $effect(() => {
    let timer: ReturnType<typeof setTimeout> | undefined
    const unsubscribe = fs.subscribe(() => {
      if (!fsReady) return
      clearTimeout(timer)
      timer = setTimeout(() => profile.setPref('fs', fs.getState()), 400)
    })
    return () => {
      clearTimeout(timer)
      unsubscribe()
    }
  })

  // Reserve the top + bottom bars and feed the remaining rectangle to the WM as
  // its work area (drives maximize + snap). Re-measured on resize via a
  // ResizeObserver AND recomputed whenever the chrome (skin) changes — reading
  // `chrome` here makes the `$effect` re-run on every OS switch.
  $effect(() => {
    const el = rootEl
    if (!el) return
    const { top, bottom } = barInsets(chrome)
    const apply = () => {
      const r = el.getBoundingClientRect()
      wm.setWorkArea({
        x: 0,
        y: top,
        width: r.width,
        height: Math.max(240, r.height - top - bottom),
      })
    }
    apply()
    const ro = new ResizeObserver(apply)
    ro.observe(el)
    return () => ro.disconnect()
  })
</script>

<div bind:this={rootEl} class="os-root" style={skinStyle}>
  <Desktop />
</div>

<style>
  .os-root {
    position: fixed;
    inset: 0;
    overflow: hidden;
    font-family: var(--os-font);
    background: var(--os-wallpaper);
  }
</style>

// apps/desktop-os-vue/src/App.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { serializeSession, restoreSession, type WindowSession } from '@iris-ui-kit/core/window'
import { type VfsState } from '@iris-ui-kit/core/fs'
import { wm } from './wm'
import { fs } from './fs'
import { profile } from './profile'
import { getManifest, registerCustomApps, type AppManifest } from './catalog'
import { useOs } from './os-state'
import { barInsets } from './os'
import Desktop from './components/Desktop.vue'

/**
 * The desktop, parameterized by the active OS skin. The skin is a set of CSS
 * custom properties (`--os-*`) applied on the root so the whole shell — and the
 * @iris-ui-kit/vue components inside windows — reads `var(--os-*)`. Switching the OS
 * swaps the variables AND the structural chrome (top menu bar, bottom dock,
 * spotlight, traffic-lights) live; mirrors the React shell, which carries all
 * three (Win11 / macOS / KDE). This Vue build ships Win11 + macOS chrome.
 */
const { chrome } = useOs()

// The root style: position + font + wallpaper, plus the active skin's vars
// spread in so they cascade into the whole shell. Reactive to the OS choice.
const rootStyle = computed<Record<string, string>>(() => ({
  position: 'fixed',
  inset: '0',
  overflow: 'hidden',
  fontFamily: 'var(--os-font)',
  background: 'var(--os-wallpaper)',
  ...chrome.value.vars,
}))

const rootRef = ref<HTMLElement | null>(null)
let ro: ResizeObserver | undefined

// ── Window-session persistence ───────────────────────────────────────────────
// Open windows (geometry, state, stacking, focus) survive a reload: restored ONCE
// after hydrate + work-area are ready, then re-saved (debounced) on every change.
// Mirrors the React shell (apps/desktop-os/src/App.tsx).
const restored = ref(false)
let saveUnsubscribe: (() => void) | undefined
let saveTimer: ReturnType<typeof setTimeout> | undefined

// ── Virtual file-system persistence ──────────────────────────────────────────
// The Files app's contents survive a reload: hydrated ONCE from the profile (or
// seeded with a starter set), then re-saved (debounced) on every change. Mirrors
// the React shell (apps/desktop-os/src/App.tsx).
const fsReady = ref(false)
let fsSaveUnsubscribe: (() => void) | undefined
let fsSaveTimer: ReturnType<typeof setTimeout> | undefined

/** The saved session, filtered to apps that still resolve (removed apps skipped). */
function knownSession(): WindowSession {
  const raw = profile.getPref<WindowSession>('session')
  if (!Array.isArray(raw)) return []
  // Custom (URL-added) apps live in prefs — register them so getManifest resolves.
  registerCustomApps((profile.getPref<AppManifest[]>('customApps') ?? []) as AppManifest[])
  return raw.filter((e) => Boolean(getManifest(e.appId)))
}

/**
 * Restore the saved session ONCE, after hydrate populated prefs and the work area
 * is set (so geometry clamps correctly), then start persisting on every change.
 */
function restoreSessionOnce() {
  if (restored.value) return
  restored.value = true
  if (wm.getState().windows.length === 0) restoreSession(wm, knownSession())
  // Persist (debounced) on every WM change, now that restore has run — so the
  // debounced save can never overwrite the saved session before restore.
  saveUnsubscribe = wm.subscribe(() => {
    clearTimeout(saveTimer)
    saveTimer = setTimeout(() => profile.setPref('session', serializeSession(wm.getState())), 400)
  })
}

/**
 * Hydrate the virtual file system from the profile ONCE (or seed a starter set),
 * then persist it (debounced) on every change — so user files survive reloads.
 * Runs after hydrate has populated prefs, so the saved `fs` pref is available.
 */
function hydrateFsOnce() {
  if (fsReady.value) return
  fsReady.value = true
  const saved = profile.getPref<VfsState>('fs')
  if (saved && Array.isArray(saved.folders) && saved.files) {
    fs.store.setState(() => saved)
  } else if (Object.keys(fs.getState().files).length === 0) {
    fs.write(
      '/Documents/Welcome.txt',
      'Welcome to Iris Desktop OS.\n\nThis Files app is a real virtual file system — create folders and text files, rename, delete. It persists to your profile and survives a reload.',
    )
    fs.write(
      '/Documents/notes.md',
      '# Notes\n\n- Backed by @iris-ui-kit/core/fs\n- The same engine drives all four shells.',
    )
    fs.mkdir('/Pictures')
  }
  // Persist (debounced) on every fs change, now that hydrate has run — so the
  // debounced save can never overwrite the saved state before hydrate.
  fsSaveUnsubscribe = fs.subscribe(() => {
    clearTimeout(fsSaveTimer)
    fsSaveTimer = setTimeout(() => profile.setPref('fs', fs.getState()), 400)
  })
}

// Reserve the top + bottom bars (from the active chrome's insets) and feed the
// remaining rectangle to the WM as its work area (drives maximize + snap).
// Re-measured on resize AND whenever the OS skin changes (different bar heights).
function applyWorkArea() {
  const el = rootRef.value
  if (!el) return
  const { top, bottom } = barInsets(chrome.value)
  const r = el.getBoundingClientRect()
  wm.setWorkArea({
    x: 0,
    y: top,
    width: r.width,
    height: Math.max(240, r.height - top - bottom),
  })
}

onMounted(() => {
  // Set the work area first (sync) so a restored window's geometry clamps right.
  applyWorkArea()
  const el = rootRef.value
  if (el) {
    ro = new ResizeObserver(applyWorkArea)
    ro.observe(el)
  }
  // Restore the persisted profile (incl. the saved OS skin) — the desktop renders
  // immediately and re-skins when hydrate lands — then restore the window session
  // and hydrate the virtual file system.
  void profile.hydrate().then(() => {
    restoreSessionOnce()
    hydrateFsOnce()
  })
})

// Recompute the work area when the OS changes (top-bar appears, bar height differs).
watch(chrome, applyWorkArea)

onUnmounted(() => {
  ro?.disconnect()
  clearTimeout(saveTimer)
  saveUnsubscribe?.()
  clearTimeout(fsSaveTimer)
  fsSaveUnsubscribe?.()
})
</script>

<template>
  <div ref="rootRef" :style="rootStyle">
    <Desktop />
  </div>
</template>
