// apps/ssr-next/app/feedback/page.tsx
import { IrisAlert, IrisBadge, IrisButton, IrisInput } from '@iris-ui-kit/react'

interface FeedbackPageProps {
  searchParams: Promise<Record<string, string | string[] | undefined>>
}

function first(value: string | string[] | undefined): string | undefined {
  return Array.isArray(value) ? value[0] : value
}

export default async function FeedbackPage({ searchParams }: FeedbackPageProps) {
  const params = await searchParams
  const status = first(params.status)
  const hasError = status === 'error'
  const nameError = hasError && first(params.fields)?.split(',').includes('name')
  const messageError = hasError && first(params.fields)?.split(',').includes('message')

  return (
    <main style={{ maxWidth: 880, margin: '0 auto', padding: '40px 24px' }}>
      <header style={{ marginBottom: 28 }}>
        <IrisBadge tone="warning" variant="solid">
          Next.js route handler
        </IrisBadge>
        <h1 style={{ margin: '12px 0 6px', fontSize: 28 }}>Feedback</h1>
        <p style={{ margin: 0, color: 'var(--iris-muted-foreground)' }}>
          This native form remains usable without JavaScript and is validated by a production route
          handler.
        </p>
        <nav aria-label="SSR reference routes" style={{ display: 'flex', gap: 16, marginTop: 16 }}>
          <a href="/">Interactive demo</a>
          <a href="/data">Server data</a>
        </nav>
      </header>

      <form
        action="/api/feedback"
        method="post"
        style={{ display: 'grid', gap: 18, maxWidth: 620 }}
      >
        <div style={{ display: 'grid', gap: 6 }}>
          <label htmlFor="feedback-name" style={{ fontWeight: 600 }}>
            Name
          </label>
          <IrisInput
            id="feedback-name"
            name="name"
            autoComplete="name"
            invalid={Boolean(nameError)}
            aria-describedby={nameError ? 'feedback-name-error' : undefined}
          />
          {nameError ? (
            <span id="feedback-name-error" style={{ color: 'var(--iris-danger)', fontSize: 13 }}>
              Enter at least 2 characters.
            </span>
          ) : null}
        </div>

        <div style={{ display: 'grid', gap: 6 }}>
          <label htmlFor="feedback-message" style={{ fontWeight: 600 }}>
            Message
          </label>
          <textarea
            id="feedback-message"
            name="message"
            rows={5}
            aria-invalid={Boolean(messageError)}
            aria-describedby={messageError ? 'feedback-message-error' : undefined}
            style={{
              padding: 'var(--iris-padding-md)',
              border: '1px solid var(--iris-border)',
              borderRadius: 'var(--iris-radius-md)',
              background: 'var(--iris-background)',
              color: 'var(--iris-foreground)',
              font: 'inherit',
              resize: 'vertical',
            }}
          />
          {messageError ? (
            <span id="feedback-message-error" style={{ color: 'var(--iris-danger)', fontSize: 13 }}>
              Enter at least 10 characters.
            </span>
          ) : null}
        </div>

        <div>
          <IrisButton type="submit">Send feedback</IrisButton>
        </div>

        {status === 'success' ? (
          <IrisAlert tone="success" title="Feedback received" aria-live="polite">
            Thanks — your feedback was validated on the server.
          </IrisAlert>
        ) : null}
        {hasError ? (
          <IrisAlert tone="danger" title="Please check the form" aria-live="assertive">
            Name and message are required.
          </IrisAlert>
        ) : null}
      </form>
    </main>
  )
}

// apps/ssr-solidstart/src/routes/feedback.tsx
import { IrisAlert, IrisBadge, IrisButton, IrisInput } from '@iris-ui-kit/solid'
import { useLocation, useSubmission } from '@solidjs/router'
import { createMemo, Show } from 'solid-js'
import { submitFeedback, type FeedbackResult } from '../demo-server'

const controlStyle = {
  width: '100%',
  padding: 'var(--iris-padding-md)',
  border: '1px solid var(--iris-border)',
  'border-radius': 'var(--iris-radius-md)',
  background: 'var(--iris-background)',
  color: 'var(--iris-foreground)',
  font: 'inherit',
  resize: 'vertical',
} as const

function feedbackFromSearch(search: string): FeedbackResult | undefined {
  const params = new URLSearchParams(search)
  const status = params.get('status')
  if (status === 'success') {
    const name = params.get('name') ?? 'there'
    return {
      ok: true,
      message: `Thanks, ${name}. Your feedback was validated on the server.`,
    }
  }
  if (status !== 'error') return undefined

  const fields = new Set((params.get('fields') ?? '').split(','))
  const errors: Record<string, string> = {}
  if (fields.has('name')) errors.name = 'Enter at least 2 characters.'
  if (fields.has('message')) errors.message = 'Enter at least 10 characters.'
  return { ok: false, message: 'Name and message are required.', errors }
}

function describedBy(error: string | undefined, id: string): string | undefined {
  return error ? id : undefined
}

function SubmitButton(props: { pending: boolean }) {
  return (
    <IrisButton type="submit" loading={props.pending} disabled={props.pending}>
      {props.pending ? 'Sending feedback…' : 'Send feedback'}
    </IrisButton>
  )
}

function FeedbackAlert(props: { feedback: FeedbackResult }) {
  return (
    <IrisAlert
      tone={props.feedback.ok ? 'success' : 'danger'}
      title={props.feedback.ok ? 'Feedback received' : 'Please check the form'}
      aria-live={props.feedback.ok ? 'polite' : 'assertive'}
    >
      {props.feedback.message}
    </IrisAlert>
  )
}

export default function FeedbackPage() {
  const location = useLocation()
  const submission = useSubmission(submitFeedback)
  const result = createMemo(
    () => (submission.result as FeedbackResult | undefined) ?? feedbackFromSearch(location.search),
  )
  const initialName = () => new URLSearchParams(location.search).get('name') ?? ''
  const errors = () => result()?.errors ?? {}
  const nameError = () => errors().name
  const messageError = () => errors().message

  return (
    <>
      <header style={{ 'margin-bottom': '28px' }}>
        <IrisBadge tone="warning" variant="solid">
          SolidStart action
        </IrisBadge>
        <h1 style={{ margin: '12px 0 6px', 'font-size': '28px' }}>Feedback</h1>
        <p style={{ margin: 0, color: 'var(--iris-muted-foreground)' }}>
          The form posts through a native SolidStart server action and progressively enhances after
          hydration.
        </p>
      </header>

      <form
        action={submitFeedback}
        method="post"
        style={{ display: 'grid', gap: '18px', 'max-width': '620px' }}
      >
        <div style={{ display: 'grid', gap: '6px' }}>
          <label for="feedback-name" style={{ 'font-weight': 600 }}>
            Name
          </label>
          <IrisInput
            id="feedback-name"
            name="name"
            autocomplete="name"
            value={initialName()}
            invalid={Boolean(nameError())}
            ariaDescribedby={describedBy(nameError(), 'feedback-name-error')}
            style={{ width: '100%' }}
          />
          <Show when={nameError()}>
            {(error) => (
              <span
                id="feedback-name-error"
                style={{ color: 'var(--iris-danger)', 'font-size': '13px' }}
              >
                {error()}
              </span>
            )}
          </Show>
        </div>

        <div style={{ display: 'grid', gap: '6px' }}>
          <label for="feedback-message" style={{ 'font-weight': 600 }}>
            Message
          </label>
          <textarea
            id="feedback-message"
            name="message"
            rows={5}
            aria-invalid={Boolean(messageError())}
            aria-describedby={describedBy(messageError(), 'feedback-message-error')}
            style={controlStyle}
          />
          <Show when={messageError()}>
            {(error) => (
              <span
                id="feedback-message-error"
                style={{ color: 'var(--iris-danger)', 'font-size': '13px' }}
              >
                {error()}
              </span>
            )}
          </Show>
        </div>

        <div>
          <SubmitButton pending={Boolean(submission.pending)} />
        </div>

        <Show when={submission.pending}>
          <p role="status" aria-live="polite" style={{ margin: 0 }}>
            Sending your feedback…
          </p>
        </Show>
        <Show when={result()}>{(feedback) => <FeedbackAlert feedback={feedback()} />}</Show>
        <Show when={submission.error}>
          <IrisAlert tone="danger" title="Server error" aria-live="assertive">
            The server could not accept the feedback.
          </IrisAlert>
        </Show>
      </form>
    </>
  )
}
