// packages/svelte/src/primitives/watermark/IrisWatermark.svelte
<script lang="ts">
  import { mergeStyle } from '../../internal/style'

  const TILE_COUNT = 72

  let {
    content,
    rotate = -22,
    fontSize = 16,
    color = 'var(--iris-muted)',
    opacity = 0.15,
    gap = 24,
    style,
    children,
    ...rest
  } = $props()

  const tiles = $derived(Array.from({ length: TILE_COUNT }, (_, i) => i))
</script>

<div
  {...rest}
  data-iris-watermark
  style={mergeStyle('position: relative', style)}
>
  {@render children?.()}
  <div
    data-iris-watermark-overlay
    aria-hidden="true"
    style="position: absolute; inset: 0; overflow: hidden; pointer-events: none; user-select: none; display: flex; flex-wrap: wrap; align-content: flex-start; gap: {gap}px; opacity: {opacity}"
  >
    {#each tiles as i (i)}
      <span
        data-iris-watermark-tile
        style="transform: rotate({rotate}deg); font-size: {fontSize}px; color: {color}; white-space: nowrap; line-height: 1"
      >
        {content}
      </span>
    {/each}
  </div>
</div>

// packages/solid/src/primitives/watermark/IrisWatermark.tsx
import { For, mergeProps, splitProps, type JSX } from 'solid-js'

const TILE_COUNT = 72

export interface IrisWatermarkProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /** Watermark text, tiled across the area. */
  content: string
  /** Rotation of each tile in degrees. */
  rotate?: number
  fontSize?: number
  color?: string
  /** Overlay opacity (0–1). */
  opacity?: number
  /** Spacing between tiles in px. */
  gap?: number
  children?: JSX.Element
}

/**
 * Watermark: overlays tiled, rotated text over its slot content — for
 * confidential or branded surfaces. The overlay is aria-hidden,
 * non-selectable, and pointer-events: none.
 */
export function IrisWatermark(props: IrisWatermarkProps): JSX.Element {
  const merged = mergeProps(
    {
      rotate: -22,
      fontSize: 16,
      color: 'var(--iris-muted)',
      opacity: 0.15,
      gap: 24,
    },
    props,
  )
  const [local, rest] = splitProps(merged, [
    'content',
    'rotate',
    'fontSize',
    'color',
    'opacity',
    'gap',
    'style',
    'children',
  ])

  return (
    <div
      {...rest}
      data-iris-watermark=""
      style={{
        position: 'relative',
        ...((local.style as JSX.CSSProperties) ?? {}),
      }}
    >
      {local.children}
      <div
        data-iris-watermark-overlay=""
        aria-hidden="true"
        style={{
          position: 'absolute',
          inset: '0',
          overflow: 'hidden',
          'pointer-events': 'none',
          'user-select': 'none',
          display: 'flex',
          'flex-wrap': 'wrap',
          'align-content': 'flex-start',
          gap: `${local.gap}px`,
          opacity: String(local.opacity),
        }}
      >
        <For each={Array.from({ length: TILE_COUNT }, (_, i) => i)}>
          {(_i) => (
            <span
              data-iris-watermark-tile=""
              style={{
                transform: `rotate(${local.rotate}deg)`,
                'font-size': `${local.fontSize}px`,
                color: local.color,
                'white-space': 'nowrap',
                'line-height': '1',
              }}
            >
              {local.content}
            </span>
          )}
        </For>
      </div>
    </div>
  )
}
