// packages/solid/src/primitives/tree/IrisTree.tsx
import {
  createSignal,
  createEffect,
  createMemo,
  mergeProps,
  splitProps,
  Show,
  For,
  type JSX,
} from 'solid-js'
import { createTreeSelection, type TreeSelectionNode } from '@iris-ui/core'
import { useStore } from '../../useStore'
import { useI18n } from '../../i18n'

export interface IrisTreeNode {
  id: string
  label: string
  children?: IrisTreeNode[]
  isLeaf?: boolean
  disabled?: boolean
}

export type IrisTreeSelectionMode = 'none' | 'single' | 'multi'

export interface IrisTreeProps {
  nodes?: IrisTreeNode[]
  selectedIds?: string[]
  defaultSelectedIds?: string[]
  expandedIds?: string[]
  defaultExpandedIds?: string[]
  selectionMode?: IrisTreeSelectionMode
  /**
   * Show a checkbox per node with parent/child cascade + indeterminate
   * (tri-state) propagation, independent of `selectionMode`. Driven by the
   * framework-agnostic `createTreeSelection`.
   */
  checkable?: boolean
  /** Initially checked node ids (uncontrolled; reconciled through the cascade). */
  defaultChecked?: string[]
  /** Notified with the fully-reconciled checked node ids on every check change. */
  onCheckedChange?: (checked: string[]) => void
  disabled?: boolean
  onSelect?: (ids: string[]) => void
  onExpand?: (ids: string[]) => void
  /** Accessible name for the tree container. Defaults to the localized "Tree". */
  ariaLabel?: string
}

function IrisTreeNodeItem(nodeProps: {
  node: IrisTreeNode
  depth: number
  expanded: () => boolean
  selected: () => boolean
  active: () => boolean
  checked: () => boolean
  indeterminate: () => boolean
  checkable: boolean
  disabled: boolean
  onToggleExpand: () => void
  onSelect: () => void
  onActivate: () => void
  onCheck: () => void
  children?: JSX.Element
}): JSX.Element {
  const hasChildren = () => (nodeProps.node.children?.length ?? 0) > 0
  const isLeaf = () => nodeProps.node.isLeaf || (!hasChildren() && !nodeProps.node.children)
  const isDisabled = () => nodeProps.disabled || nodeProps.node.disabled

  // `indeterminate` is a DOM *property*, not an attribute — set it imperatively
  // and keep it in sync with the reactive tri-state from the cascade engine.
  let checkboxEl: HTMLInputElement | undefined
  createEffect(() => {
    if (checkboxEl) checkboxEl.indeterminate = nodeProps.indeterminate()
  })

  return (
    <li
      role="treeitem"
      aria-selected={nodeProps.selected()}
      aria-expanded={!isLeaf() ? nodeProps.expanded() : undefined}
      aria-level={nodeProps.depth + 1}
      aria-disabled={isDisabled() ? 'true' : undefined}
      tabindex={nodeProps.active() ? 0 : -1}
      data-iris-tree-node={nodeProps.node.id}
      data-depth={nodeProps.depth}
      data-state={nodeProps.selected() ? 'selected' : nodeProps.active() ? 'active' : 'idle'}
      onFocus={() => nodeProps.onActivate()}
    >
      <div
        data-iris-tree-node-row=""
        onClick={() => {
          if (isDisabled()) return
          nodeProps.onActivate()
          if (!isLeaf()) nodeProps.onToggleExpand()
          nodeProps.onSelect()
        }}
        style={{
          display: 'flex',
          'align-items': 'center',
          gap: '4px',
          padding: `4px 8px 4px ${nodeProps.depth * 20 + 8}px`,
          cursor: isDisabled() ? 'not-allowed' : 'pointer',
          opacity: isDisabled() ? '0.5' : '1',
          background: nodeProps.selected()
            ? 'var(--iris-primary-ghost, rgba(59,130,246,0.1))'
            : 'transparent',
          'border-radius': 'var(--iris-radius-sm, 4px)',
        }}
      >
        <Show when={!isLeaf()}>
          <span
            data-iris-tree-expand=""
            style={{
              'font-size': '10px',
              transition: 'transform 150ms',
              transform: nodeProps.expanded() ? 'rotate(90deg)' : 'none',
              'user-select': 'none',
            }}
          >
            ▶
          </span>
        </Show>
        <Show when={nodeProps.checkable}>
          <input
            ref={(el) => {
              checkboxEl = el
            }}
            type="checkbox"
            data-iris-tree-checkbox={nodeProps.node.id}
            checked={nodeProps.checked()}
            aria-checked={nodeProps.indeterminate() ? 'mixed' : nodeProps.checked()}
            aria-label={nodeProps.node.label}
            disabled={isDisabled() || undefined}
            onClick={(e) => e.stopPropagation()}
            onChange={() => {
              if (!isDisabled()) nodeProps.onCheck()
            }}
          />
        </Show>
        <span style={{ 'font-size': '14px', color: 'var(--iris-foreground)' }}>
          {nodeProps.node.label}
        </span>
      </div>
      <Show when={nodeProps.expanded() && !isLeaf()}>
        <ul
          role="group"
          data-iris-tree-children=""
          style={{ 'list-style': 'none', margin: '0', padding: '0' }}
        >
          {nodeProps.children}
        </ul>
      </Show>
    </li>
  )
}

/**
 * Tree view: expandable nodes, checkable mode, single/multi-select.
 * Solid port of the Vue IrisTree.
 *
 * Checkable mode renders a checkbox per node with parent/child cascade and
 * indeterminate (tri-state) propagation, driven by the framework-agnostic
 * `createTreeSelection` from `@iris-ui/core` (no cascade logic lives here).
 */
export function IrisTree(props: IrisTreeProps): JSX.Element {
  const { t } = useI18n()
  const merged = mergeProps(
    {
      nodes: [] as IrisTreeNode[],
      defaultSelectedIds: [] as string[],
      defaultExpandedIds: [] as string[],
      selectionMode: 'single' as IrisTreeSelectionMode,
      checkable: false,
      disabled: false,
    },
    props,
  )
  const [local] = splitProps(merged, [
    'nodes',
    'selectedIds',
    'defaultSelectedIds',
    'expandedIds',
    'defaultExpandedIds',
    'selectionMode',
    'checkable',
    'defaultChecked',
    'onCheckedChange',
    'disabled',
    'onSelect',
    'onExpand',
    'ariaLabel',
  ])

  const [internalSelected, setInternalSelected] = createSignal<string[]>(local.defaultSelectedIds)
  const [internalExpanded, setInternalExpanded] = createSignal<string[]>(local.defaultExpandedIds)

  const selectedIds = () => local.selectedIds ?? internalSelected()
  const expandedIds = () => local.expandedIds ?? internalExpanded()

  // Checkable mode: flatten the FULL tree (every node, including collapsed and
  // not-yet-rendered children) into `{ key, parentKey, disabled }` so the
  // cascade is correct even for collapsed branches, and drive it with the core
  // `createTreeSelection`. No cascade logic lives in this adapter.
  const checkNodes = (): TreeSelectionNode[] => {
    const out: TreeSelectionNode[] = []
    const walk = (ns: IrisTreeNode[], parentKey: string | undefined) => {
      for (const node of ns) {
        out.push({ key: node.id, parentKey, disabled: node.disabled })
        if (node.children && node.children.length > 0) walk(node.children, node.id)
      }
    }
    walk(local.nodes, undefined)
    return out
  }

  const checkModel = createTreeSelection({
    nodes: checkNodes(),
    defaultChecked: local.defaultChecked,
    onChange: (keys) => local.onCheckedChange?.(keys),
  })
  // Bridge the model's store into Solid reactivity so checkbox rows re-render on
  // every check change — the same store-binding the rest of the package uses.
  const checkState = useStore(checkModel.selection.store)
  const isChecked = (id: string): boolean => {
    checkState() // track the store so derived check state stays reactive
    return checkModel.isChecked(id)
  }
  const isIndeterminate = (id: string): boolean => {
    checkState()
    return checkModel.isIndeterminate(id)
  }

  const toggleExpand = (id: string) => {
    const current = expandedIds()
    const next = current.includes(id) ? current.filter((x) => x !== id) : [...current, id]
    if (!local.expandedIds) setInternalExpanded(next)
    local.onExpand?.(next)
  }

  const selectNode = (id: string) => {
    if (local.selectionMode === 'none') return
    const current = selectedIds()
    let next: string[]
    if (local.selectionMode === 'multi') {
      next = current.includes(id) ? current.filter((x) => x !== id) : [...current, id]
    } else {
      next = current.includes(id) ? [] : [id]
    }
    if (!local.selectedIds) setInternalSelected(next)
    local.onSelect?.(next)
  }

  // Flattened list of the currently-VISIBLE nodes (depth-first, respecting
  // expansion) — the linear order keyboard navigation moves through. Mirrors the
  // React/Vue/Svelte adapters so arrow-key behavior is identical across all four.
  interface FlatNode {
    node: IrisTreeNode
    depth: number
    parentId: string | null
    hasChildren: boolean
  }
  const flat = createMemo<FlatNode[]>(() => {
    const out: FlatNode[] = []
    const expandedNow = expandedIds()
    const walk = (ns: IrisTreeNode[], depth: number, parentId: string | null): void => {
      for (const node of ns) {
        const kids = node.children ?? []
        const hasChildren = !node.isLeaf && kids.length > 0
        out.push({ node, depth, parentId, hasChildren })
        if (hasChildren && expandedNow.includes(node.id)) walk(kids, depth + 1, node.id)
      }
    }
    walk(local.nodes, 0, null)
    return out
  })

  // Roving focus: exactly one node is the keyboard target (tabindex=0). Seed it to
  // the first visible node and keep it valid as the visible set changes.
  const [activeId, setActiveId] = createSignal<string | null>(null)
  createEffect(() => {
    const list = flat()
    const cur = activeId()
    if (!cur || !list.some((f) => f.node.id === cur)) {
      setActiveId(list[0]?.node.id ?? null)
    }
  })

  const moveActive = (delta: 1 | -1): void => {
    const list = flat()
    if (list.length === 0) return
    const cur = activeId()
    const idx = cur ? list.findIndex((f) => f.node.id === cur) : -1
    let next = idx + delta
    if (next < 0) next = 0
    if (next >= list.length) next = list.length - 1
    setActiveId(list[next]!.node.id)
  }

  // WAI-ARIA tree keyboard pattern (container-level handler reads the active node,
  // so it works regardless of which item bubbled the event):
  //   ↑/↓ move · → expand or into-first-child · ← collapse or to-parent ·
  //   Home/End first/last · Enter/Space (de)select.
  const onKeyDown = (e: KeyboardEvent): void => {
    if (local.disabled) return
    const cur = activeId()
    if (!cur) return
    const list = flat()
    const current = list.find((f) => f.node.id === cur)
    if (!current) return
    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault()
        moveActive(1)
        break
      case 'ArrowUp':
        e.preventDefault()
        moveActive(-1)
        break
      case 'ArrowRight':
        e.preventDefault()
        if (current.hasChildren) {
          if (expandedIds().includes(cur)) moveActive(1)
          else toggleExpand(cur)
        }
        break
      case 'ArrowLeft':
        e.preventDefault()
        if (current.hasChildren && expandedIds().includes(cur)) toggleExpand(cur)
        else if (current.parentId) setActiveId(current.parentId)
        break
      case 'Home':
        e.preventDefault()
        setActiveId(list[0]!.node.id)
        break
      case 'End':
        e.preventDefault()
        setActiveId(list[list.length - 1]!.node.id)
        break
      case 'Enter':
      case ' ':
        e.preventDefault()
        selectNode(cur)
        break
    }
  }

  const renderNodes = (nodes: IrisTreeNode[], depth: number): JSX.Element => (
    <For each={nodes}>
      {(node) => (
        <IrisTreeNodeItem
          node={node}
          depth={depth}
          expanded={() => expandedIds().includes(node.id)}
          selected={() => selectedIds().includes(node.id)}
          active={() => activeId() === node.id}
          checked={() => isChecked(node.id)}
          indeterminate={() => isIndeterminate(node.id)}
          checkable={local.checkable}
          disabled={local.disabled}
          onToggleExpand={() => toggleExpand(node.id)}
          onSelect={() => selectNode(node.id)}
          onActivate={() => setActiveId(node.id)}
          onCheck={() => checkModel.toggle(node.id)}
        >
          {node.children && node.children.length > 0
            ? renderNodes(node.children, depth + 1)
            : undefined}
        </IrisTreeNodeItem>
      )}
    </For>
  )

  return (
    <ul
      data-iris-tree=""
      role="tree"
      aria-label={local.ariaLabel ?? t('tree.label')}
      data-disabled={local.disabled ? '' : undefined}
      tabindex={-1}
      onKeyDown={onKeyDown}
      style={{ 'list-style': 'none', margin: '0', padding: '0' }}
    >
      {renderNodes(local.nodes, 0)}
    </ul>
  )
}

// packages/svelte/src/primitives/tree/IrisTree.svelte
<script lang="ts">
  import { createTreeSelection, type TreeSelectionNode } from '@iris-ui/core'
  import { useI18n } from '../../i18n'
  import type { IrisTreeNode, IrisTreeSelectionMode } from './types'

  interface FlatNode {
    node: IrisTreeNode
    depth: number
    parentId: string | null
    hasChildren: boolean
  }

  interface Props {
    nodes?: IrisTreeNode[]
    expanded?: string[]
    defaultExpanded?: string[]
    selected?: string[]
    defaultSelected?: string[]
    selectionMode?: IrisTreeSelectionMode
    /**
     * Show a checkbox per node with parent/child cascade + indeterminate
     * (tri-state) propagation, independent of `selectionMode`. Driven by the
     * framework-agnostic `createTreeSelection`.
     */
    checkable?: boolean
    /** Initially checked node ids (uncontrolled; reconciled through the cascade). */
    defaultChecked?: string[]
    /** Notified with the fully-reconciled checked node ids on every check change. */
    onCheckedChange?: (checked: string[]) => void
    ariaLabel?: string
    loading?: boolean
    error?: boolean
    onExpandedChange?: (ids: string[]) => void
    onSelectedChange?: (ids: string[]) => void
    onExpand?: (id: string) => void
    onCollapse?: (id: string) => void
    onSelect?: (id: string, node: IrisTreeNode) => void
    style?: string
    class?: string
  }

  let {
    nodes = [],
    expanded: expandedProp,
    defaultExpanded = [],
    selected: selectedProp,
    defaultSelected = [],
    selectionMode = 'single',
    checkable = false,
    defaultChecked,
    onCheckedChange,
    ariaLabel,
    loading = false,
    error = false,
    onExpandedChange,
    onSelectedChange,
    onExpand,
    onCollapse,
    onSelect,
    style,
    class: className,
    ...rest
  }: Props = $props()

  const { t } = useI18n()

  const isExpandedControlled = $derived(expandedProp !== undefined)
  const isSelectedControlled = $derived(selectedProp !== undefined)

  // svelte-ignore state_referenced_locally
  let internalExpanded = $state<Set<string>>(new Set(defaultExpanded))
  // svelte-ignore state_referenced_locally
  let internalSelected = $state<Set<string>>(new Set(defaultSelected))

  // Lazy children cache
  let childrenCache = $state<Map<string, IrisTreeNode[]>>(new Map())
  let loadingNodes = $state<Set<string>>(new Set())

  const expandedSet = $derived(
    isExpandedControlled ? new Set(expandedProp ?? []) : internalExpanded,
  )

  const selectedSet = $derived(
    isSelectedControlled ? new Set(selectedProp ?? []) : internalSelected,
  )

  let activeId = $state<string | null>(null)

  // Build flat list of visible nodes
  function flatten(nodeList: IrisTreeNode[], depth: number, parentId: string | null): FlatNode[] {
    const out: FlatNode[] = []
    for (const node of nodeList) {
      const cachedChildren = childrenCache.get(node.id)
      const resolvedChildren = cachedChildren ?? node.children
      const hasChildren = node.isLeaf
        ? false
        : resolvedChildren
          ? resolvedChildren.length > 0
          : !!node.loadChildren
      out.push({ node, depth, parentId, hasChildren })
      if (hasChildren && expandedSet.has(node.id)) {
        out.push(...flatten(resolvedChildren ?? [], depth + 1, node.id))
      }
    }
    return out
  }

  const flat = $derived(flatten(nodes, 0, null))

  // Checkable mode: flatten the FULL tree (every node, not just the visible
  // ones) into `{ key, parentKey, disabled }` so the cascade is correct even
  // for collapsed branches, and drive it with the core `createTreeSelection`.
  function flattenCheckNodes(
    nodeList: IrisTreeNode[],
    parentKey: string | undefined,
  ): TreeSelectionNode[] {
    const out: TreeSelectionNode[] = []
    for (const node of nodeList) {
      out.push({ key: node.id, parentKey, disabled: node.disabled })
      const kids = node.children ?? childrenCache.get(node.id)
      if (kids && kids.length > 0) out.push(...flattenCheckNodes(kids, node.id))
    }
    return out
  }

  const checkNodes = $derived(flattenCheckNodes(nodes, undefined))

  // Rebuild the cascade model when the tree shape changes; `defaultChecked`
  // re-seeds then. The model owns its checked-set store.
  const checkModel = $derived(
    createTreeSelection({
      nodes: checkNodes,
      defaultChecked,
      onChange: (keys) => onCheckedChange?.(keys),
    }),
  )

  // Re-render when the checked set changes. Mirror the model's store into local
  // reactive state (re-subscribing whenever the model is rebuilt); reading
  // `checkedKeys` inside the `{#each}` makes `isChecked`/`isIndeterminate`
  // reactive.
  // svelte-ignore state_referenced_locally
  let checkedKeys = $state<string[]>(checkModel.selection.get())
  $effect(() => {
    const model = checkModel
    checkedKeys = model.selection.get()
    return model.selection.store.subscribe((v) => {
      checkedKeys = v
    })
  })

  // Resolve check state through the model. `keys` is the reactive checked-set
  // snapshot — passing it in makes these reads re-run when the set changes.
  function checkChecked(id: string, keys: string[]): boolean {
    void keys
    return checkModel.isChecked(id)
  }
  function checkIndeterminate(id: string, keys: string[]): boolean {
    void keys
    return checkModel.isIndeterminate(id)
  }

  // `indeterminate` is a DOM property, not an attribute. Set it via an action
  // whose `update` re-runs whenever the passed boolean changes.
  function setIndeterminate(el: HTMLInputElement, value: boolean) {
    el.indeterminate = value
    return {
      update(next: boolean) {
        el.indeterminate = next
      },
    }
  }

  function setExpanded(ids: string[]) {
    if (!isExpandedControlled) internalExpanded = new Set(ids)
    onExpandedChange?.(ids)
  }

  function setSelected(ids: string[]) {
    if (!isSelectedControlled) internalSelected = new Set(ids)
    onSelectedChange?.(ids)
  }

  function toggleExpand(node: IrisTreeNode) {
    const exp = expandedSet
    if (exp.has(node.id)) {
      const next = new Set(exp)
      next.delete(node.id)
      setExpanded([...next])
      onCollapse?.(node.id)
    } else {
      const next = new Set(exp)
      next.add(node.id)
      setExpanded([...next])
      onExpand?.(node.id)

      // Lazy loading
      if (node.loadChildren && !childrenCache.has(node.id)) {
        const ls = new Set(loadingNodes)
        ls.add(node.id)
        loadingNodes = ls
        node.loadChildren().then((children) => {
          const cache = new Map(childrenCache)
          cache.set(node.id, children)
          childrenCache = cache
          const ls2 = new Set(loadingNodes)
          ls2.delete(node.id)
          loadingNodes = ls2
        })
      }
    }
  }

  function selectNode(node: IrisTreeNode) {
    if (node.disabled || selectionMode === 'none') return
    const sel = selectedSet
    if (selectionMode === 'single') {
      setSelected([node.id])
    } else {
      const next = new Set(sel)
      if (next.has(node.id)) next.delete(node.id)
      else next.add(node.id)
      setSelected([...next])
    }
    onSelect?.(node.id, node)
  }

  function onKeyDown(e: KeyboardEvent, fn: FlatNode, idx: number) {
    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault()
        if (flat[idx + 1]) activeId = flat[idx + 1].node.id
        break
      case 'ArrowUp':
        e.preventDefault()
        if (flat[idx - 1]) activeId = flat[idx - 1].node.id
        break
      case 'ArrowRight':
        e.preventDefault()
        if (fn.hasChildren && !expandedSet.has(fn.node.id)) toggleExpand(fn.node)
        else if (fn.hasChildren && flat[idx + 1]) activeId = flat[idx + 1].node.id
        break
      case 'ArrowLeft':
        e.preventDefault()
        if (fn.hasChildren && expandedSet.has(fn.node.id)) toggleExpand(fn.node)
        else if (fn.parentId) activeId = fn.parentId
        break
      case 'Home':
        e.preventDefault()
        if (flat[0]) activeId = flat[0].node.id
        break
      case 'End':
        e.preventDefault()
        if (flat[flat.length - 1]) activeId = flat[flat.length - 1].node.id
        break
      case 'Enter':
      case ' ':
        e.preventDefault()
        selectNode(fn.node)
        break
    }
  }
</script>

<div
  role="tree"
  aria-label={ariaLabel ?? t('tree.label')}
  data-iris-tree
  style:display="flex"
  style:flex-direction="column"
  {style}
  class={className}
  {...rest}
>
  {#if loading}
    <div
      data-iris-state="loading"
      style:padding="12px"
      style:color="var(--iris-muted)"
      style:font-size="14px"
    >
      {t('tree.loading')}
    </div>
  {:else if error}
    <div
      data-iris-state="error"
      style:padding="12px"
      style:color="var(--iris-danger)"
      style:font-size="14px"
    >
      {t('tree.error')}
    </div>
  {:else if nodes.length === 0}
    <div
      data-iris-state="empty"
      style:padding="12px"
      style:color="var(--iris-muted)"
      style:font-size="14px"
    >
      {t('tree.empty')}
    </div>
  {:else}
    {#each flat as fn, idx (fn.node.id)}
      {@const isExpanded = expandedSet.has(fn.node.id)}
      {@const isSelected = selectedSet.has(fn.node.id)}
      {@const isFocused = activeId === fn.node.id}
      {@const isChecked = checkChecked(fn.node.id, checkedKeys)}
      {@const isIndeterminate = checkIndeterminate(fn.node.id, checkedKeys)}
      <div
        role="treeitem"
        aria-expanded={fn.hasChildren ? isExpanded : undefined}
        aria-selected={selectionMode !== 'none' ? isSelected : undefined}
        aria-disabled={fn.node.disabled ? 'true' : undefined}
        aria-level={fn.depth + 1}
        tabindex={isFocused || (idx === 0 && !activeId) ? 0 : -1}
        data-iris-tree-item
        data-state={isSelected ? 'selected' : 'idle'}
        onkeydown={(e) => onKeyDown(e, fn, idx)}
        onfocus={() => {
          activeId = fn.node.id
        }}
        onclick={() => {
          activeId = fn.node.id
          selectNode(fn.node)
        }}
        style:display="flex"
        style:align-items="center"
        style:gap="4px"
        style:padding="4px 8px"
        style:padding-left={`${8 + fn.depth * 16}px`}
        style:cursor={fn.node.disabled ? 'default' : 'pointer'}
        style:border-radius="var(--iris-radius-sm, 4px)"
        style:background={isSelected ? 'var(--iris-surface-hover)' : 'transparent'}
        style:color={fn.node.disabled ? 'var(--iris-muted)' : 'var(--iris-foreground)'}
        style:font-size="14px"
        style:outline={isFocused ? '2px solid var(--iris-primary)' : 'none'}
        style:outline-offset="1px"
      >
        {#if fn.hasChildren}
          <button
            type="button"
            aria-hidden="true"
            tabindex={-1}
            onclick={(e) => {
              e.stopPropagation()
              toggleExpand(fn.node)
            }}
            style:width="16px"
            style:height="16px"
            style:display="inline-flex"
            style:align-items="center"
            style:justify-content="center"
            style:border="none"
            style:background="transparent"
            style:color="var(--iris-muted)"
            style:cursor="pointer"
            style:padding="0"
            style:font-size="10px"
            style:flex-shrink="0">{isExpanded ? '▼' : '▶'}</button
          >
        {:else}
          <span style:width="16px" style:flex-shrink="0"></span>
        {/if}
        {#if checkable}
          <input
            type="checkbox"
            data-iris-tree-checkbox
            checked={isChecked}
            aria-checked={isIndeterminate ? 'mixed' : isChecked}
            aria-label={fn.node.label}
            disabled={fn.node.disabled}
            use:setIndeterminate={isIndeterminate}
            onclick={(e) => e.stopPropagation()}
            onchange={() => checkModel.toggle(fn.node.id)}
            style:cursor={fn.node.disabled ? 'not-allowed' : 'pointer'}
            style:flex-shrink="0"
          />
        {/if}
        {#if loadingNodes.has(fn.node.id)}
          <span aria-hidden="true" style:color="var(--iris-muted)" style:font-size="11px">…</span>
        {/if}
        <span>{fn.node.label}</span>
      </div>
    {/each}
  {/if}
</div>
