// apps/ssr-next/app/page.tsx
import { Demo } from './Demo'

// This page is a SERVER COMPONENT (note: no 'use client' directive). It runs on
// the server during `next build` / request time and renders a CLIENT component
// (`Demo`). The fact that a Server Component can import @iris-ui-kit/react's client
// components transitively — without a manual wrapper — exercises the package's
// `'use client'` boundary that tsup injects into every entry.
export default function Page() {
  return (
    <main style={{ maxWidth: 880, margin: '0 auto', padding: '40px 24px' }}>
      <header style={{ marginBottom: 24 }}>
        <h1 style={{ margin: '0 0 4px', fontSize: 24 }}>Iris UI · SSR / RSC smoke</h1>
        <p style={{ margin: 0, color: 'var(--iris-muted-foreground, #666)' }}>
          Server Component (<code>app/page.tsx</code>) rendering a client island (
          <code>app/Demo.tsx</code>) built from <code>@iris-ui-kit/react</code>. A successful{' '}
          <code>next build</code> is the SSR/RSC-compat proof.
        </p>
      </header>
      <Demo />
    </main>
  )
}

// apps/ssr-nuxt/app.vue
<template>
  <Html lang="en">
    <Body>
      <main style="max-width: 880px; margin: 0 auto; padding: 40px 24px">
        <header style="margin-bottom: 24px">
          <h1 style="margin: 0 0 4px; font-size: 24px">Iris UI · Nuxt 3 SSR smoke</h1>
          <p style="margin: 0; color: var(--iris-muted-foreground, #666)">
            Server-rendered page (<code>app.vue</code>) containing a client island
            (<code>Demo.client.vue</code>) built from <code>@iris-ui-kit/vue</code>. A successful
            <code>nuxi build</code> is the SSR-compat proof.
          </p>
        </header>
        <DemoClient />
      </main>
    </Body>
  </Html>
</template>

<script setup lang="ts">
// Server component — no client reactivity. The import below auto-resolves
// components/Demo.client.vue (the `.client` suffix marks it as a client island).
// Nuxt renders it on the server and hydrates it in the browser.
</script>
