// packages/solid/src/primitives/table/useTableSort.ts
import { createSignal, createMemo, type Accessor } from 'solid-js'
import { compareValues } from '@iris-ui-kit/core'
import type { IrisTableColumn, IrisTableSortState } from './types'

type MaybeAccessor<T> = T | Accessor<T>

export interface UseTableSortOptions<Row> {
  leafColumns: MaybeAccessor<IrisTableColumn<Row>[]>
  sort?: MaybeAccessor<IrisTableSortState | null | undefined>
  defaultSort?: IrisTableSortState | null
  onSortChange?: (next: IrisTableSortState | null) => void
}

export interface UseTableSortResult<Row> {
  sortState: Accessor<IrisTableSortState | null>
  cycleSort: (col: IrisTableColumn<Row>) => void
  setSort: (next: IrisTableSortState | null) => void
  sortComparator: Accessor<((a: Row, b: Row) => number) | null>
  sortedData: Accessor<Row[]>
}

/**
 * Solid primitive for table sort state management.
 * Handles controlled/uncontrolled sort, comparator generation, and sorted data.
 */
export function useTableSort<Row extends Record<string, unknown>>(
  data: Accessor<Row[]>,
  options: UseTableSortOptions<Row>,
): UseTableSortResult<Row> {
  const read = <T>(value: MaybeAccessor<T>): T =>
    typeof value === 'function' ? (value as Accessor<T>)() : value
  const columns = (): IrisTableColumn<Row>[] => read(options.leafColumns)
  const sortProp = (): IrisTableSortState | null | undefined =>
    options.sort === undefined ? undefined : read(options.sort)

  const [internalSort, setInternalSort] = createSignal<IrisTableSortState | null>(
    options.defaultSort ?? null,
  )
  const sortControlled = () => sortProp() !== undefined
  const sortState: Accessor<IrisTableSortState | null> = createMemo(() =>
    sortControlled() ? (sortProp() ?? null) : internalSort(),
  )

  const sortComparator = createMemo<((a: Row, b: Row) => number) | null>(() => {
    const s = sortState()
    if (!s) return null
    const col = columns().find((c) => c.key === s.key)
    if (!col) return null
    const dir = s.direction === 'asc' ? 1 : -1
    const sorter =
      col.sorter ?? ((a: Row, b: Row) => compareValues(getCellValue(a, col), getCellValue(b, col)))
    return (a, b) => sorter(a, b) * dir
  })

  const sortedData = createMemo<Row[]>(() => {
    const compare = sortComparator()
    if (!compare) return data()
    return [...data()].sort(compare)
  })

  function setSort(next: IrisTableSortState | null): void {
    if (!sortControlled()) setInternalSort(next)
    options.onSortChange?.(next)
  }

  function cycleSort(col: IrisTableColumn<Row>): void {
    if (!col.sortable) return
    const s = sortState()
    if (!s || s.key !== col.key) {
      setSort({ key: col.key, direction: 'asc' })
      return
    }
    if (s.direction === 'asc') {
      setSort({ key: col.key, direction: 'desc' })
      return
    }
    setSort(null)
  }

  return {
    sortState,
    cycleSort,
    setSort,
    sortComparator,
    sortedData,
  }
}

/** Get the value for a column from a row (handles dataIndex fallback). */
function getCellValue<Row extends Record<string, unknown>>(
  row: Row,
  column: IrisTableColumn<Row>,
): unknown {
  const key = (column.dataIndex ?? column.key) as keyof Row
  return row[key]
}

// packages/react/src/primitives/table/useTableSort.ts
import * as React from 'react'
import { compareValues } from '@iris-ui-kit/core'
import type { IrisTableColumn, IrisTableSortState } from './types'

/**
 * Options for {@link useTableSort}.
 */
export interface UseTableSortOptions<Row> {
  /** Flat list of leaf columns (no grouping wrapper). */
  leafColumns: IrisTableColumn<Row>[]
  /** Controlled sort state. */
  sort?: IrisTableSortState | null
  /** Default sort (uncontrolled). */
  defaultSort?: IrisTableSortState | null
  /** Called when the sort changes. */
  onSortChange?: (next: IrisTableSortState | null) => void
}

/**
 * Result of {@link useTableSort}.
 */
export interface UseTableSortResult<Row> {
  /** Current sort state (controlled if a `sort` prop was provided, else internal). */
  sortState: IrisTableSortState | null
  /** Cycle a column: asc → desc → none. */
  cycleSort: (col: IrisTableColumn<Row>) => void
  /** Directly set the sort state. */
  setSort: (next: IrisTableSortState | null) => void
  /** Memoized comparator derived from the current sort. Null when no sort is active. */
  sortComparator: ((a: Row, b: Row) => number) | null
  /** Sorted data using the active comparator. Falls back to the original data. */
  sortedData: Row[]
}

/**
 * Extract and manage table sort state, comparator, and sorted data.
 *
 * Handles both controlled (`sort` prop) and uncontrolled (`defaultSort`) modes.
 * Produces a memoized comparator from the sort column's `sorter` or a default
 * value-based comparator, and a stable sorted copy of the data.
 *
 * @example
 * ```tsx
 * const { sortState, cycleSort, sortedData } = useTableSort({
 *   leafColumns,
 *   sort: props.sort,
 *   defaultSort: props.defaultSort,
 *   onSortChange: props.onSortChange,
 * })
 * ```
 */
export function useTableSort<Row extends Record<string, unknown>>(
  data: Row[],
  options: UseTableSortOptions<Row>,
): UseTableSortResult<Row> {
  const { leafColumns, sort: sortProp, defaultSort, onSortChange } = options

  // Internal state for uncontrolled mode
  const sortControlled = sortProp !== undefined
  const [sortInternal, setSortInternal] = React.useState<IrisTableSortState | null>(
    defaultSort ?? null,
  )
  const sortState = sortControlled ? (sortProp ?? null) : sortInternal

  // Memoized comparator
  const sortComparator = React.useMemo<((a: Row, b: Row) => number) | null>(() => {
    if (!sortState) return null
    const col = leafColumns.find((c) => c.key === sortState.key)
    if (!col) return null
    const dir = sortState.direction === 'asc' ? 1 : -1
    const sorter =
      col.sorter ?? ((a: Row, b: Row) => compareValues(getCellValue(a, col), getCellValue(b, col)))
    return (a, b) => sorter(a, b) * dir
  }, [leafColumns, sortState])

  // Sorted data
  const sortedData = React.useMemo(() => {
    if (!sortComparator) return data
    return [...data].sort(sortComparator)
  }, [data, sortComparator])

  const setSort = React.useCallback(
    (next: IrisTableSortState | null) => {
      if (!sortControlled) setSortInternal(next)
      onSortChange?.(next)
    },
    [sortControlled, onSortChange],
  )

  const cycleSort = React.useCallback(
    (col: IrisTableColumn<Row>) => {
      if (!col.sortable) return
      if (!sortState || sortState.key !== col.key) {
        setSort({ key: col.key, direction: 'asc' })
        return
      }
      if (sortState.direction === 'asc') {
        setSort({ key: col.key, direction: 'desc' })
        return
      }
      setSort(null)
    },
    [sortState, setSort],
  )

  return {
    sortState,
    cycleSort,
    setSort,
    sortComparator,
    sortedData,
  }
}

/** Get the value for a column from a row (handles dataIndex fallback). */
function getCellValue<Row extends Record<string, unknown>>(
  row: Row,
  column: IrisTableColumn<Row>,
): unknown {
  const key = (column.dataIndex ?? column.key) as keyof Row
  return row[key]
}
