// packages/solid/src/primitives/dropdown/Dropdown.tsx
import { createEffect, createSignal, createUniqueId, mergeProps, type JSX } from 'solid-js'
import { createFloatingMachine, type Placement } from '@iris-ui-kit/core'
import { useMachine } from '../../useMachine'
import { DropdownContext } from './context'

export interface IrisDropdownProps {
  open?: boolean
  defaultOpen?: boolean
  onOpenChange?: (open: boolean) => void
  placement?: Placement
  offset?: number
  children?: JSX.Element
}

/**
 * Dropdown menu root. Composes `createFloatingMachine` (state) with
 * `useFloating` (positioning, in `IrisDropdownMenu`). `role="menu"` semantics +
 * arrow-key nav + auto-close on select. Solid port of the React/Vue dropdown.
 */
export function IrisDropdown(props: IrisDropdownProps): JSX.Element {
  const merged = mergeProps(
    { defaultOpen: false, placement: 'bottom-start' as Placement, offset: 6 },
    props,
  )
  const isControlled = (): boolean => props.open !== undefined

  const [state, send] = useMachine(() =>
    createFloatingMachine(merged.defaultOpen ? 'open' : 'closed'),
  )
  const internalOpen = (): boolean => state().value === 'open'

  createEffect(() => {
    if (!isControlled()) return
    const target = props.open ? 'open' : 'closed'
    if (state().value !== target) send({ type: props.open ? 'OPEN' : 'CLOSE' })
  })

  const open = (): boolean => (isControlled() ? Boolean(props.open) : internalOpen())
  const setOpen = (next: boolean): void => {
    if (!isControlled()) send({ type: next ? 'OPEN' : 'CLOSE' })
    merged.onOpenChange?.(next)
  }

  const [trigger, setTrigger] = createSignal<HTMLElement | undefined>()
  const [content, setContent] = createSignal<HTMLElement | undefined>()
  const contentId = createUniqueId()

  return (
    <DropdownContext.Provider
      value={{
        open,
        setOpen,
        trigger,
        setTrigger,
        content,
        setContent,
        contentId,
        get placement() {
          return merged.placement
        },
        get offset() {
          return merged.offset
        },
      }}
    >
      {props.children}
    </DropdownContext.Provider>
  )
}

// packages/svelte/src/primitives/dropdown/Dropdown.svelte
<script lang="ts">
  import { createFloatingMachine } from '@iris-ui-kit/core'
  import { toMachine } from '../../useMachine'
  import { setDropdownContext, type DropdownContextValue } from './context'
  import type { IrisDropdownProps } from './types'

  let {
    open: openProp,
    defaultOpen = false,
    onOpenChange,
    placement = 'bottom-start',
    offset = 6,
    children,
  }: IrisDropdownProps = $props()

  const isControlled = $derived(openProp !== undefined)

  // svelte-ignore state_referenced_locally — initial machine state; controlled changes sync below.
  const { state: machineState, send } = toMachine(
    createFloatingMachine(defaultOpen ? 'open' : 'closed'),
  )
  const internalOpen = $derived($machineState.value === 'open')

  // Keep the machine in sync with a controlled `open` prop.
  $effect(() => {
    if (!isControlled) return
    const target = openProp ? 'open' : 'closed'
    if ($machineState.value !== target) send({ type: openProp ? 'OPEN' : 'CLOSE' })
  })

  const open = $derived(isControlled ? Boolean(openProp) : internalOpen)
  function setOpen(next: boolean): void {
    if (!isControlled) send({ type: next ? 'OPEN' : 'CLOSE' })
    onOpenChange?.(next)
  }

  let triggerEl = $state<HTMLElement | undefined>(undefined)
  let contentEl = $state<HTMLElement | undefined>(undefined)
  const contentId = $props.id()

  setDropdownContext({
    get open() {
      return open
    },
    setOpen,
    get trigger() {
      return triggerEl
    },
    setTrigger: (el) => {
      triggerEl = el
    },
    get content() {
      return contentEl
    },
    setContent: (el) => {
      contentEl = el
    },
    contentId,
    get placement() {
      return placement
    },
    get offset() {
      return offset
    },
  } satisfies DropdownContextValue)
</script>

{@render children?.()}
