// packages/svelte/src/primitives/empty-state/IrisEmptyState.svelte
<script lang="ts">
  import { styleToString, mergeStyle } from '../../internal/style'

  let {
    title = '',
    description = '',
    style,
    children,
    icon,
    titleSlot,
    descriptionSlot,
    action,
    ...rest
  } = $props()

  const containerStyle = styleToString({
    display: 'flex',
    'flex-direction': 'column',
    'align-items': 'center',
    'justify-content': 'center',
    gap: '12px',
    padding: '32px 16px',
    'text-align': 'center',
    color: 'var(--iris-foreground)',
  })
</script>

<div {...rest} role="status" data-iris-empty-state style={mergeStyle(containerStyle, style)}>
  {#if icon}
    <div
      data-iris-empty-state-icon
      style="display: flex; align-items: center; justify-content: center; width: 48px; height: 48px; border-radius: var(--iris-radius-lg, 12px); background: var(--iris-surface); color: var(--iris-muted); opacity: 0.9; font-size: var(--iris-font-size-2xl, 20px); line-height: 1"
    >
      {@render icon()}
    </div>
  {/if}
  {#if title || titleSlot}
    <div
      data-iris-empty-state-title
      style="font-weight: 600; font-size: var(--iris-font-size-lg, 16px)"
    >
      {#if titleSlot}
        {@render titleSlot()}
      {:else}
        {title}
      {/if}
    </div>
  {/if}
  {#if description || descriptionSlot}
    <div
      data-iris-empty-state-description
      style="color: var(--iris-muted); font-size: var(--iris-font-size-md, 14px); max-width: 380px"
    >
      {#if descriptionSlot}
        {@render descriptionSlot()}
      {:else}
        {description}
      {/if}
    </div>
  {/if}
  {#if action}
    <div data-iris-empty-state-action style="margin-top: 4px">
      {@render action()}
    </div>
  {/if}
  {@render children?.()}
</div>

// packages/solid/src/primitives/empty-state/IrisEmptyState.tsx
import { mergeProps, Show, splitProps, type JSX } from 'solid-js'

export interface IrisEmptyStateProps extends JSX.HTMLAttributes<HTMLDivElement> {
  title?: string
  description?: string
  icon?: JSX.Element
  action?: JSX.Element
  children?: JSX.Element
}

/**
 * Placeholder shown when a list / table / page has no content.
 * Centered column layout with optional icon, title, description, and action slot.
 */
export function IrisEmptyState(props: IrisEmptyStateProps): JSX.Element {
  const merged = mergeProps({ title: '', description: '' }, props)
  const [local, rest] = splitProps(merged, [
    'title',
    'description',
    'icon',
    'action',
    'style',
    'children',
  ])

  return (
    <div
      {...rest}
      role="status"
      data-iris-empty-state=""
      style={{
        display: 'flex',
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        gap: '12px',
        padding: '32px 16px',
        'text-align': 'center',
        color: 'var(--iris-foreground)',
        ...((local.style as JSX.CSSProperties) ?? {}),
      }}
    >
      <Show when={local.icon}>
        <div
          data-iris-empty-state-icon=""
          style={{
            display: 'flex',
            'align-items': 'center',
            'justify-content': 'center',
            width: '48px',
            height: '48px',
            'border-radius': 'var(--iris-radius-lg, 12px)',
            background: 'var(--iris-surface)',
            color: 'var(--iris-muted)',
            opacity: '0.9',
            'font-size': 'var(--iris-font-size-2xl, 20px)',
            'line-height': '1',
          }}
        >
          {local.icon}
        </div>
      </Show>
      <Show when={local.title || local.children}>
        <div
          data-iris-empty-state-title=""
          style={{ 'font-weight': '600', 'font-size': 'var(--iris-font-size-lg, 16px)' }}
        >
          {local.children ?? local.title}
        </div>
      </Show>
      <Show when={local.description}>
        <div
          data-iris-empty-state-description=""
          style={{
            color: 'var(--iris-muted)',
            'font-size': 'var(--iris-font-size-md, 14px)',
            'max-width': '380px',
          }}
        >
          {local.description}
        </div>
      </Show>
      <Show when={local.action}>
        <div data-iris-empty-state-action="" style={{ 'margin-top': '4px' }}>
          {local.action}
        </div>
      </Show>
    </div>
  )
}
