// packages/react/src/skins/SkinProvider.tsx
import { createContext, useContext, useEffect, useRef, type ReactNode } from 'react'
import { injectGlobalStyles } from '@iris-ui-kit/theme'
import {
  applySkin,
  type ApplySkinResult,
  type ResolvedSkin,
  type SkinEngine,
} from '@iris-ui-kit/skins'
import { useStore } from '../useStore'

interface IrisSkinContextValue {
  engine: SkinEngine
  current: ResolvedSkin
}

const IrisSkinContext = createContext<IrisSkinContextValue | null>(null)

export interface SkinProviderProps {
  engine: SkinEngine
  target?: HTMLElement | null
  /** CSP nonce for the injected global stylesheet. */
  cspNonce?: string
  children?: ReactNode
}

/**
 * Renderless provider mirroring `<ThemeProvider>`: subscribes to the skin
 * engine's store, applies the resolved skin's CSS vars to `target` (or
 * `document.documentElement`), reverts on unmount. Zero skin logic — all of it
 * lives in `@iris-ui-kit/skins`. Client boundary (tsup prepends `'use client'`).
 */
export function SkinProvider({ engine, target = null, cspNonce, children }: SkinProviderProps) {
  const current = useStore(engine.store)
  const appliedRef = useRef<ApplySkinResult | null>(null)

  useEffect(() => {
    injectGlobalStyles(cspNonce)
    const el = target ?? document.documentElement
    appliedRef.current?.revert()
    appliedRef.current = applySkin(current, el)
    return () => {
      appliedRef.current?.revert()
      appliedRef.current = null
    }
  }, [current, target])

  return <IrisSkinContext.Provider value={{ engine, current }}>{children}</IrisSkinContext.Provider>
}

export function useSkinContext(): IrisSkinContextValue {
  const ctx = useContext(IrisSkinContext)
  if (!ctx) throw new Error('[iris-ui] useSkin(): no <SkinProvider> ancestor found')
  return ctx
}

/** Non-throwing read for skin-aware primitives that may render standalone. */
export function useSkinOptional(): ResolvedSkin | undefined {
  return useContext(IrisSkinContext)?.current
}

// packages/solid/src/skins/SkinProvider.tsx
import {
  createContext,
  createEffect,
  onCleanup,
  useContext,
  type Accessor,
  type JSX,
} from 'solid-js'
import { injectGlobalStyles } from '@iris-ui-kit/theme'
import { applySkin, type ResolvedSkin, type SkinEngine } from '@iris-ui-kit/skins'
import { useStore } from '../useStore'

interface IrisSkinContextValue {
  engine: SkinEngine
  current: Accessor<ResolvedSkin>
}

const IrisSkinContext = createContext<IrisSkinContextValue>()

export interface SkinProviderProps {
  engine: SkinEngine
  target?: HTMLElement | null
  /** CSP nonce for the injected global stylesheet. */
  cspNonce?: string
  children?: JSX.Element
}

/**
 * Renderless provider mirroring `<ThemeProvider>`: subscribes to the skin
 * engine's store, applies the resolved skin's CSS vars to `target` (or
 * `document.documentElement`), reverts on change/unmount. Zero skin logic — all
 * of it lives in `@iris-ui-kit/skins`.
 */
export function SkinProvider(props: SkinProviderProps): JSX.Element {
  const current = useStore(props.engine.store)

  createEffect(() => {
    injectGlobalStyles(props.cspNonce)
    const el = props.target ?? document.documentElement
    const applied = applySkin(current(), el)
    onCleanup(() => applied.revert())
  })

  return (
    <IrisSkinContext.Provider value={{ engine: props.engine, current }}>
      {props.children}
    </IrisSkinContext.Provider>
  )
}

export function useSkinContext(): IrisSkinContextValue {
  const ctx = useContext(IrisSkinContext)
  if (!ctx) throw new Error('[iris-ui] useSkin(): no <SkinProvider> ancestor found')
  return ctx
}

/** Non-throwing read for skin-aware primitives that may render standalone. */
export function useSkinOptional(): Accessor<ResolvedSkin> | undefined {
  return useContext(IrisSkinContext)?.current
}
