// packages/solid/src/primitives/image/IrisImage.tsx
import { createSignal, mergeProps, Show, splitProps, type JSX } from 'solid-js'
import { useI18n } from '../../i18n'

export interface IrisImageProps extends Omit<
  JSX.ImgHTMLAttributes<HTMLImageElement>,
  'src' | 'alt'
> {
  src: string
  alt?: string
  width?: number | string
  height?: number | string
  /** Shown when the image fails to load. */
  fallback?: string
  /** Enable the click-to-zoom preview overlay. */
  preview?: boolean
}

/**
 * Image with graceful error fallback and optional click-to-zoom preview overlay.
 * Lazy-loaded by default.
 */
export function IrisImage(props: IrisImageProps): JSX.Element {
  const merged = mergeProps({ alt: '', preview: true }, props)
  const [local, rest] = splitProps(merged, [
    'src',
    'alt',
    'width',
    'height',
    'fallback',
    'preview',
    'style',
  ])

  const { t } = useI18n()

  const [errored, setErrored] = createSignal(false)
  const [open, setOpen] = createSignal(false)

  const shownSrc = () => (errored() && local.fallback ? local.fallback : local.src)
  const canPreview = () => local.preview && !errored()

  const onKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Escape') setOpen(false)
  }

  return (
    <>
      <img
        {...rest}
        data-iris-image=""
        data-errored={errored() ? 'true' : undefined}
        src={shownSrc()}
        alt={local.alt}
        width={local.width}
        height={local.height}
        loading="lazy"
        onError={() => {
          if (!errored()) setErrored(true)
        }}
        onClick={() => {
          if (canPreview()) setOpen(true)
        }}
        style={{
          display: 'inline-block',
          'object-fit': 'cover',
          cursor: canPreview() ? 'zoom-in' : undefined,
          ...((local.style as JSX.CSSProperties) ?? {}),
        }}
      />
      <Show when={open()}>
        <div
          data-iris-image-preview=""
          role="dialog"
          aria-modal="true"
          aria-label={local.alt || t('image.preview')}
          onClick={() => setOpen(false)}
          onKeyDown={onKeyDown}
          style={{
            position: 'fixed',
            inset: '0',
            'z-index': '1000',
            display: 'flex',
            'align-items': 'center',
            'justify-content': 'center',
            background: 'rgba(0,0,0,0.7)',
            cursor: 'zoom-out',
          }}
        >
          <img
            data-iris-image-preview-img=""
            src={shownSrc()}
            alt={local.alt}
            style={{ 'max-width': '90vw', 'max-height': '90vh', 'object-fit': 'contain' }}
          />
          <button
            type="button"
            data-iris-image-preview-close=""
            aria-label={t('dialog.close')}
            onClick={(e) => {
              e.stopPropagation()
              setOpen(false)
            }}
            style={{
              position: 'absolute',
              'inset-block-start': '16px',
              'inset-inline-end': '16px',
              width: '36px',
              height: '36px',
              'border-radius': '50%',
              border: 'none',
              background: 'rgba(0,0,0,0.5)',
              color: 'var(--iris-primary-foreground, #fff)',
              'font-size': 'var(--iris-font-size-2xl, 20px)',
              'line-height': '1',
              cursor: 'pointer',
            }}
          >
            ×
          </button>
        </div>
      </Show>
    </>
  )
}

// packages/svelte/src/primitives/image/IrisImage.svelte
<script lang="ts">
  import { mergeStyle } from '../../internal/style'
  import { useI18n } from '../../i18n'

  const { t } = useI18n()

  let {
    src,
    alt = '',
    width = undefined as number | string | undefined,
    height = undefined as number | string | undefined,
    fallback = undefined as string | undefined,
    preview = true,
    style,
    ...rest
  } = $props()

  // svelte-ignore state_referenced_locally
  let errored = $state(false)
  // svelte-ignore state_referenced_locally
  let open = $state(false)

  const shownSrc = $derived(errored && fallback ? fallback : src)
  const canPreview = $derived(preview && !errored)

  function handleError() {
    if (!errored) errored = true
  }

  function handleClick() {
    if (canPreview) open = true
  }

  function handleClose() {
    open = false
  }

  $effect(() => {
    errored = false
  })

  $effect(() => {
    if (!open) return
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') open = false
    }
    document.addEventListener('keydown', onKey)
    return () => document.removeEventListener('keydown', onKey)
  })
</script>

<img
  {...rest}
  data-iris-image
  data-errored={errored ? 'true' : undefined}
  {src}
  {alt}
  {width}
  {height}
  loading="lazy"
  onerror={handleError}
  onclick={handleClick}
  style={mergeStyle(
    `display: inline-block; object-fit: cover${canPreview ? '; cursor: zoom-in' : ''}`,
    style,
  )}
/>

{#if open}
  <div
    data-iris-image-preview
    role="dialog"
    aria-modal="true"
    aria-label={alt || t('image.preview')}
    tabindex="-1"
    onclick={handleClose}
    onkeydown={(e) => {
      if (e.key === 'Escape') handleClose()
    }}
    style="position: fixed; inset: 0; z-index: 1000; display: flex; align-items: center; justify-content: center; background: rgba(0,0,0,0.7); cursor: zoom-out"
  >
    <img
      data-iris-image-preview-img
      src={shownSrc}
      {alt}
      style="max-width: 90vw; max-height: 90vh; object-fit: contain"
    />
    <button
      type="button"
      data-iris-image-preview-close
      aria-label={t('dialog.close')}
      onclick={(e) => {
        e.stopPropagation()
        handleClose()
      }}
      style="position: absolute; inset-block-start: 16px; inset-inline-end: 16px; width: 36px; height: 36px; border-radius: 50%; border: none; background: rgba(0,0,0,0.5); color: var(--iris-primary-foreground, #fff); font-size: var(--iris-font-size-2xl, 20px); line-height: 1; cursor: pointer"
    >
      ×
    </button>
  </div>
{/if}
