// packages/svelte/src/primitives/breadcrumb/BreadcrumbItem.svelte
<script lang="ts">
  import { styleToString, mergeStyle } from '../../internal/style'
  import type { IrisBreadcrumbItemProps } from './types'

  let { href, current = false, style, children, ...rest }: IrisBreadcrumbItemProps = $props()

  const crumbStyle = $derived(
    styleToString({
      color: current ? 'var(--iris-muted)' : 'var(--iris-primary)',
      'text-decoration': 'none',
      cursor: current ? 'default' : href ? 'pointer' : 'default',
    }),
  )
</script>

<li data-iris-breadcrumb-item>
  {#if href && !current}
    <a {...rest} data-iris-breadcrumb-crumb {href} style={mergeStyle(crumbStyle, style)}>
      {@render children?.()}
    </a>
  {:else}
    <span
      {...rest}
      data-iris-breadcrumb-crumb
      aria-current={current ? 'page' : undefined}
      style={mergeStyle(crumbStyle, style)}
    >
      {@render children?.()}
    </span>
  {/if}
</li>

// packages/react/src/primitives/breadcrumb/BreadcrumbItem.tsx
import * as React from 'react'

export interface IrisBreadcrumbItemProps extends React.HTMLAttributes<HTMLElement> {
  href?: string
  /** Internal: set by parent `IrisBreadcrumb` when this is the last item. */
  isCurrent?: boolean
  children?: React.ReactNode
}

/**
 * A single breadcrumb crumb. Renders an `<a>` when `href` is given and the
 * crumb is not the last one; otherwise a `<span>`. The `isCurrent` flag is
 * set automatically by the parent `IrisBreadcrumb` based on position.
 */
export const IrisBreadcrumbItem = React.forwardRef<HTMLElement, IrisBreadcrumbItemProps>(
  function IrisBreadcrumbItem({ href, isCurrent = false, style, children, ...rest }, ref) {
    const baseStyle: React.CSSProperties = {
      color: isCurrent ? 'var(--iris-muted)' : 'var(--iris-primary)',
      textDecoration: 'none',
      cursor: isCurrent ? 'default' : href ? 'pointer' : 'default',
    }

    const common = {
      ...rest,
      'aria-current': isCurrent ? ('page' as const) : undefined,
      'data-iris-breadcrumb-crumb': '',
      style: { ...baseStyle, ...style },
    }

    if (href && !isCurrent) {
      return (
        <a {...common} ref={ref as React.Ref<HTMLAnchorElement>} href={href}>
          {children}
        </a>
      )
    }
    return (
      <span {...common} ref={ref as React.Ref<HTMLSpanElement>}>
        {children}
      </span>
    )
  },
)
