// packages/svelte/src/primitives/scroll-area/IrisScrollArea.svelte
<script lang="ts">
  import { mergeStyle } from '../../internal/style'

  type Axis = 'vertical' | 'horizontal' | 'both'

  interface Props {
    maxHeight?: number | string
    maxWidth?: number | string
    axis?: Axis
    style?: string
    children?: import('svelte').Snippet
    [key: string]: unknown
  }

  let { maxHeight, maxWidth, axis = 'vertical', style, children, ...rest }: Props = $props()

  const OVERFLOW: Record<Axis, string> = {
    vertical: 'overflow-y: auto; overflow-x: hidden;',
    horizontal: 'overflow-x: auto; overflow-y: hidden;',
    both: 'overflow: auto;',
  }

  function px(v: number | string | undefined): string {
    if (v === undefined) return ''
    return typeof v === 'number' ? `${v}px` : v
  }

  const baseStyle = $derived(
    [
      OVERFLOW[axis],
      maxHeight ? `max-height: ${px(maxHeight)};` : '',
      maxWidth ? `max-width: ${px(maxWidth)};` : '',
      'outline: none;',
    ]
      .filter(Boolean)
      .join(' '),
  )
</script>

<div
  {...rest}
  data-iris-scroll-area
  data-axis={axis}
  tabindex={0}
  style={mergeStyle(baseStyle, style)}
>
  {@render children?.()}
</div>

// packages/solid/src/primitives/scroll-area/IrisScrollArea.tsx
import { mergeProps, splitProps, type JSX } from 'solid-js'

export type IrisScrollAreaAxis = 'vertical' | 'horizontal' | 'both'

const OVERFLOW: Record<IrisScrollAreaAxis, JSX.CSSProperties> = {
  vertical: { 'overflow-y': 'auto', 'overflow-x': 'hidden' },
  horizontal: { 'overflow-x': 'auto', 'overflow-y': 'hidden' },
  both: { overflow: 'auto' },
}

const px = (v: number | string | undefined): string | undefined =>
  typeof v === 'number' ? `${v}px` : v

export interface IrisScrollAreaProps {
  maxHeight?: number | string
  maxWidth?: number | string
  axis?: IrisScrollAreaAxis
  children?: JSX.Element
  style?: JSX.CSSProperties | string
  class?: string
  [key: string]: unknown
}

/** Solid port of IrisScrollArea — keyboard-focusable scroll container. */
export function IrisScrollArea(props: IrisScrollAreaProps): JSX.Element {
  const merged = mergeProps({ axis: 'vertical' as IrisScrollAreaAxis }, props)
  const [local, rest] = splitProps(merged, ['maxHeight', 'maxWidth', 'axis', 'children', 'style'])

  return (
    <div
      {...rest}
      data-iris-scroll-area=""
      data-axis={local.axis}
      tabIndex={0}
      style={{
        ...OVERFLOW[local.axis],
        'max-height': px(local.maxHeight),
        'max-width': px(local.maxWidth),
        outline: 'none',
        ...((typeof local.style === 'object' ? local.style : {}) as JSX.CSSProperties),
      }}
    >
      {local.children}
    </div>
  )
}
