// packages/svelte/src/primitives/toggle-group/IrisToggleGroup.svelte
<script lang="ts">
  import { createSelectionModel } from '@iris-ui-kit/core'
  import { toStore } from '../../useStore'
  import { styleToString, mergeStyle } from '../../internal/style'
  import { setToggleGroupContext } from './context'
  import type { ToggleGroupType, ToggleGroupOrientation, ToggleGroupVariant } from './context'

  interface Props {
    type?: ToggleGroupType
    value?: string | string[] | null
    orientation?: ToggleGroupOrientation
    size?: 'sm' | 'md' | 'lg'
    variant?: ToggleGroupVariant
    disabled?: boolean
    style?: string
    children?: import('svelte').Snippet
    onchange?: (value: string | string[] | null) => void
    [key: string]: unknown
  }

  let {
    type = 'single',
    value = undefined,
    orientation = 'horizontal',
    size = 'md',
    variant = 'outline',
    disabled = false,
    style,
    children,
    onchange,
    ...rest
  }: Props = $props()

  // Plain non-reactive array for focus movement registration
  interface ItemReg {
    value: string
    getEl: () => HTMLElement | null
  }
  const itemRegistry: ItemReg[] = []

  // Selection logic (single/multiple toggle, dedup) is single-sourced in the
  // core selection model; this component only maps its union value shape
  // (string | string[] | null) to/from the model's flat key array — mirroring
  // the React ToggleGroup reference.
  const toKeys = (v: string | string[] | null | undefined): string[] =>
    v == null ? [] : Array.isArray(v) ? v : [v]
  const fromKeys = (keys: string[]): string | string[] | null =>
    type === 'multiple' ? keys : (keys[0] ?? null)

  // Controlled when a `value` prop is supplied. Controlled groups RENDER from
  // the prop (true controlled semantics): a press emits onchange but the active
  // items only change when the parent writes `value` back; uncontrolled renders
  // from the model store.
  const isControlled = $derived(value !== undefined)

  // svelte-ignore state_referenced_locally — initial seed; controlled changes sync below.
  const model = createSelectionModel<string>({
    mode: type === 'multiple' ? 'multiple' : 'single',
    defaultSelected: toKeys(value),
    onChange: (keys) => onchange?.(fromKeys(keys)),
  })
  const selectedKeys = toStore(model.store)

  // Controlled: mirror the prop into the model without re-emitting onchange.
  $effect(() => {
    if (isControlled) model.sync(toKeys(value))
  })

  // Render the selection from the prop when controlled, the model store otherwise.
  const displaySelected = $derived(isControlled ? toKeys(value) : $selectedKeys)

  function isActive(v: string): boolean {
    return displaySelected.includes(v)
  }

  function toggle(v: string) {
    if (disabled) return
    // Re-base on the prop so the emitted next value is computed against what the
    // parent holds (not a prior, possibly-rejected, optimistic value).
    if (isControlled) model.sync(toKeys(value))
    model.toggle(v)
  }

  function registerItem(v: string, getEl: () => HTMLElement | null) {
    if (!itemRegistry.find((it) => it.value === v)) itemRegistry.push({ value: v, getEl })
  }

  function unregisterItem(v: string) {
    const idx = itemRegistry.findIndex((it) => it.value === v)
    if (idx >= 0) itemRegistry.splice(idx, 1)
  }

  function moveFocus(from: string, delta: 1 | -1 | 'home' | 'end') {
    if (itemRegistry.length === 0) return
    const idx = itemRegistry.findIndex((it) => it.value === from)
    let next: number
    if (delta === 'home') next = 0
    else if (delta === 'end') next = itemRegistry.length - 1
    else next = (idx + delta + itemRegistry.length) % itemRegistry.length
    itemRegistry[next]?.getEl()?.focus()
  }

  setToggleGroupContext({
    get type() {
      return type
    },
    get orientation() {
      return orientation
    },
    get size() {
      return size
    },
    get variant() {
      return variant
    },
    get disabled() {
      return disabled
    },
    isActive,
    toggle,
    registerItem,
    unregisterItem,
    moveFocus,
  })

  const rootStyle = $derived(
    styleToString({
      display: 'inline-flex',
      'flex-direction': orientation === 'horizontal' ? 'row' : 'column',
      'border-radius': 'var(--iris-radius-md, 6px)',
      overflow: 'hidden',
      background: variant === 'outline' ? 'transparent' : 'var(--iris-surface)',
      border: variant === 'outline' ? '1px solid var(--iris-border)' : '1px solid transparent',
    }),
  )
</script>

<div
  {...rest}
  role={type === 'single' ? 'radiogroup' : 'group'}
  aria-orientation={orientation}
  aria-disabled={disabled ? 'true' : undefined}
  data-iris-toggle-group
  data-iris-toggle-group-type={type}
  data-iris-toggle-group-orientation={orientation}
  data-iris-toggle-group-size={size}
  style={mergeStyle(rootStyle, style)}
>
  {@render children?.()}
</div>

// packages/solid/src/primitives/toggle-group/IrisToggleGroup.tsx
import {
  createEffect,
  mergeProps,
  onCleanup,
  onMount,
  splitProps,
  useContext,
  type JSX,
} from 'solid-js'
import { createSelectionModel } from '@iris-ui-kit/core'
import { useStore } from '../../useStore'
import {
  ToggleGroupCtx,
  type IrisToggleGroupType,
  type IrisToggleGroupOrientation,
  type IrisToggleGroupVariant,
} from './context'

// ── IrisToggleGroup ────────────────────────────────────────────────────────

export interface IrisToggleGroupProps {
  type?: IrisToggleGroupType
  value?: string | string[] | null
  defaultValue?: string | string[] | null
  orientation?: IrisToggleGroupOrientation
  size?: 'sm' | 'md' | 'lg'
  variant?: IrisToggleGroupVariant
  disabled?: boolean
  onChange?: (value: string | string[] | null) => void
  children?: JSX.Element
  style?: JSX.CSSProperties | string
  class?: string
  [key: string]: unknown
}

/** Solid port of IrisToggleGroup — segmented single/multi toggle. */
export function IrisToggleGroup(props: IrisToggleGroupProps): JSX.Element {
  const merged = mergeProps(
    {
      type: 'single' as IrisToggleGroupType,
      orientation: 'horizontal' as IrisToggleGroupOrientation,
      size: 'md' as 'sm' | 'md' | 'lg',
      variant: 'outline' as IrisToggleGroupVariant,
      disabled: false,
    },
    props,
  )
  const [local, rest] = splitProps(merged, [
    'type',
    'value',
    'defaultValue',
    'orientation',
    'size',
    'variant',
    'disabled',
    'onChange',
    'children',
    'style',
  ])

  // Selection logic (single/multiple toggle, dedup) lives in the core model;
  // this component only maps its value shape (string | string[] | null) to/from
  // the model's flat key array.
  const isMulti = local.type === 'multiple'
  const toKeys = (v: string | string[] | null | undefined): string[] =>
    v == null ? [] : Array.isArray(v) ? v : [v]
  const fromKeys = (keys: string[]): string | string[] | null =>
    isMulti ? keys : (keys[0] ?? null)

  const model = createSelectionModel<string>({
    mode: isMulti ? 'multiple' : 'single',
    defaultSelected: toKeys(
      local.value !== undefined ? local.value : (local.defaultValue ?? (isMulti ? [] : null)),
    ),
    onChange: (keys) => local.onChange?.(fromKeys(keys)),
  })
  const selected = useStore(model.store)

  // Controlled: mirror the prop into the model without re-emitting onChange.
  const isControlled = (): boolean => local.value !== undefined
  createEffect(() => {
    if (isControlled()) model.sync(toKeys(local.value))
  })

  // Controlled groups RENDER from the prop (true controlled semantics): a press
  // emits onChange but the active items only change when the parent writes
  // `value` back; uncontrolled renders from the model store.
  const displaySelected = (): string[] => (isControlled() ? toKeys(local.value) : selected())

  const items: { value: string; el: () => HTMLElement | undefined }[] = []

  const isActive = (value: string): boolean => displaySelected().includes(value)

  const toggle = (value: string): void => {
    if (local.disabled) return
    // Re-base on the prop so the emitted next value is computed against what the
    // parent holds (not a prior, possibly-rejected, optimistic value).
    if (isControlled()) model.sync(toKeys(local.value))
    model.toggle(value)
  }

  const registerItem = (value: string, el: () => HTMLElement | undefined): void => {
    if (!items.find((it) => it.value === value)) items.push({ value, el })
  }

  const unregisterItem = (value: string): void => {
    const idx = items.findIndex((it) => it.value === value)
    if (idx >= 0) items.splice(idx, 1)
  }

  const moveFocus = (from: string, delta: 1 | -1 | 'home' | 'end'): void => {
    if (items.length === 0) return
    const idx = items.findIndex((it) => it.value === from)
    let next: number
    if (delta === 'home') next = 0
    else if (delta === 'end') next = items.length - 1
    else next = (idx + delta + items.length) % items.length
    items[next]?.el()?.focus()
  }

  return (
    <ToggleGroupCtx.Provider
      value={{
        get type() {
          return local.type
        },
        get orientation() {
          return local.orientation
        },
        get size() {
          return local.size
        },
        get variant() {
          return local.variant
        },
        get disabled() {
          return local.disabled
        },
        isActive,
        toggle,
        registerItem,
        unregisterItem,
        moveFocus,
      }}
    >
      <div
        {...rest}
        role={local.type === 'single' ? 'radiogroup' : 'group'}
        aria-orientation={local.orientation}
        aria-disabled={local.disabled ? 'true' : undefined}
        data-iris-toggle-group=""
        data-iris-toggle-group-type={local.type}
        data-iris-toggle-group-orientation={local.orientation}
        data-iris-toggle-group-size={local.size}
        style={{
          display: 'inline-flex',
          'flex-direction': local.orientation === 'horizontal' ? 'row' : 'column',
          'border-radius': 'var(--iris-radius-md, 6px)',
          overflow: 'hidden',
          background: local.variant === 'outline' ? 'transparent' : 'var(--iris-surface)',
          border:
            local.variant === 'outline' ? '1px solid var(--iris-border)' : '1px solid transparent',
          ...((typeof local.style === 'object' ? local.style : {}) as JSX.CSSProperties),
        }}
      >
        {local.children}
      </div>
    </ToggleGroupCtx.Provider>
  )
}

// ── IrisToggleGroupItem ────────────────────────────────────────────────────

const SIZE_PADDING: Record<'sm' | 'md' | 'lg', string> = {
  sm: '4px 10px',
  md: '6px 14px',
  lg: '8px 18px',
}
const SIZE_FONT: Record<'sm' | 'md' | 'lg', string> = {
  sm: '12px',
  md: '13px',
  lg: '14px',
}

export interface IrisToggleGroupItemProps {
  value: string
  disabled?: boolean
  children?: JSX.Element
  style?: JSX.CSSProperties | string
  class?: string
  [key: string]: unknown
}

export function IrisToggleGroupItem(props: IrisToggleGroupItemProps): JSX.Element {
  const [local, rest] = splitProps(props, ['value', 'disabled', 'children', 'style'])
  const ctx = useContext(ToggleGroupCtx)
  if (!ctx) throw new Error('IrisToggleGroupItem must be used inside <IrisToggleGroup>')

  let elRef: HTMLButtonElement | undefined

  onMount(() => ctx.registerItem(local.value, () => elRef))
  onCleanup(() => ctx.unregisterItem(local.value))

  const isActive = (): boolean => ctx.isActive(local.value)
  const isDisabled = (): boolean => !!(local.disabled || ctx.disabled)
  const isSingle = (): boolean => ctx.type === 'single'

  const onClick = (): void => {
    if (isDisabled()) return
    ctx.toggle(local.value)
  }

  const onKeyDown = (e: KeyboardEvent): void => {
    if (isDisabled()) return
    switch (e.key) {
      case ' ':
      case 'Enter':
        e.preventDefault()
        ctx.toggle(local.value)
        break
      case 'ArrowRight':
      case 'ArrowDown':
        e.preventDefault()
        ctx.moveFocus(local.value, 1)
        break
      case 'ArrowLeft':
      case 'ArrowUp':
        e.preventDefault()
        ctx.moveFocus(local.value, -1)
        break
      case 'Home':
        e.preventDefault()
        ctx.moveFocus(local.value, 'home')
        break
      case 'End':
        e.preventDefault()
        ctx.moveFocus(local.value, 'end')
        break
    }
  }

  return (
    <button
      {...rest}
      ref={(el) => {
        elRef = el
      }}
      type="button"
      role={isSingle() ? 'radio' : undefined}
      aria-checked={isSingle() ? (isActive() ? 'true' : 'false') : undefined}
      aria-pressed={isSingle() ? undefined : isActive() ? 'true' : 'false'}
      aria-disabled={isDisabled() ? 'true' : undefined}
      disabled={isDisabled() || undefined}
      tabIndex={isActive() ? 0 : -1}
      data-iris-toggle-group-item=""
      data-state={isActive() ? 'on' : 'off'}
      onClick={onClick}
      onKeyDown={onKeyDown}
      style={{
        display: 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        gap: '6px',
        padding: SIZE_PADDING[ctx.size],
        'font-size': SIZE_FONT[ctx.size],
        'font-family': 'inherit',
        'font-weight': '500',
        'line-height': '1',
        background: isActive() ? 'var(--iris-primary)' : 'transparent',
        color: isActive() ? 'var(--iris-primary-foreground, #fff)' : 'var(--iris-foreground)',
        border: 'none',
        cursor: isDisabled() ? 'not-allowed' : 'pointer',
        opacity: isDisabled() ? 0.5 : 1,
        transition: 'background-color 120ms ease, color 120ms ease',
        ...((typeof local.style === 'object' ? local.style : {}) as JSX.CSSProperties),
      }}
    >
      {local.children}
    </button>
  )
}
