// packages/solid/src/floating/useFloating.ts
import { createEffect, createSignal, onCleanup, type Accessor } from 'solid-js'
import {
  autoUpdate,
  computePosition,
  arrow as arrowMiddleware,
  flip as flipMiddleware,
  offset as offsetMiddleware,
  shift as shiftMiddleware,
  size as sizeMiddleware,
  type Middleware,
  type Placement,
  type Strategy,
} from '@floating-ui/dom'
import type { JSX } from 'solid-js'

export interface UseFloatingOptions {
  /** Element the floating panel is positioned relative to. */
  anchor: Accessor<HTMLElement | undefined | null>
  /** The floating element itself. */
  floating: Accessor<HTMLElement | undefined | null>
  /** Whether the floating element is visible. Controls the `autoUpdate` lifecycle. */
  open: Accessor<boolean>
  placement?: Placement
  strategy?: Strategy
  offset?: number
  flip?: boolean
  shift?: boolean
  /**
   * Constrain the floating element to the available viewport space — sets
   * `maxWidth`/`maxHeight` (minus 8px padding) on it so a long dropdown/popover
   * never overflows the screen (pair with `overflow:auto` for scroll). Off by
   * default. Pass a number to override the viewport padding.
   */
  size?: boolean | number
  middleware?: Middleware[]
  /**
   * Optional accessor returning the arrow element inside the floating panel.
   * When provided, `arrowX`, `arrowY`, `arrowSide` in the return are populated.
   */
  arrow?: Accessor<HTMLElement | null | undefined>
}

export interface UseFloatingReturn {
  finalPlacement: Accessor<Placement>
  /** Ready-to-bind inline style accessor for the floating element. */
  floatingStyles: Accessor<JSX.CSSProperties>
  arrowX: Accessor<number | undefined>
  arrowY: Accessor<number | undefined>
  /** Side of the floating element the arrow is on ('bottom' placement → 'top'). */
  arrowSide: Accessor<'top' | 'right' | 'bottom' | 'left' | undefined>
}

/**
 * Reactive Floating UI integration for Solid. Subscribes `autoUpdate` while
 * `open()` is true and both elements exist; tears it down on close / unmount.
 * Pure positioning — no rendering, focus, or dismiss behavior (those live in
 * the consuming primitive). Solid port of the React/Vue `useFloating`.
 */
export function useFloating(options: UseFloatingOptions): UseFloatingReturn {
  const placement = (): Placement => options.placement ?? 'bottom'
  const strategy = (): Strategy => options.strategy ?? 'absolute'

  const [x, setX] = createSignal(0)
  const [y, setY] = createSignal(0)
  const [finalPlacement, setFinalPlacement] = createSignal<Placement>(placement())
  const [arrowX, setArrowX] = createSignal<number | undefined>()
  const [arrowY, setArrowY] = createSignal<number | undefined>()
  // True once the first positioning cycle lands. Until then the panel stays
  // `visibility: hidden` so it never flashes at the viewport origin (0,0).
  const [positioned, setPositioned] = createSignal(false)

  const buildMiddleware = (): Middleware[] => {
    const mw: Middleware[] = []
    if (options.offset !== undefined) mw.push(offsetMiddleware(options.offset))
    if (options.flip !== false) mw.push(flipMiddleware())
    if (options.shift !== false) mw.push(shiftMiddleware({ padding: 8 }))
    if (options.size) {
      const padding = typeof options.size === 'number' ? options.size : 8
      mw.push(
        sizeMiddleware({
          padding,
          apply({ availableWidth, availableHeight, elements }) {
            Object.assign(elements.floating.style, {
              maxWidth: `${Math.max(0, Math.floor(availableWidth))}px`,
              maxHeight: `${Math.max(0, Math.floor(availableHeight))}px`,
            })
          },
        }),
      )
    }
    const arrowEl = options.arrow?.()
    if (arrowEl) mw.push(arrowMiddleware({ element: arrowEl }))
    if (options.middleware) mw.push(...options.middleware)
    return mw
  }

  // Monotonic token bumped on each new positioning cycle and on cleanup, so a
  // computePosition() that resolves after this effect tore down (close/unmount
  // or a newer cycle) drops its result instead of applying stale coordinates.
  let epoch = 0

  createEffect(() => {
    if (!options.open()) return
    const a = options.anchor()
    const f = options.floating()
    if (!a || !f) return
    setPositioned(false)
    const update = (): void => {
      const token = ++epoch
      void computePosition(a, f, {
        placement: placement(),
        strategy: strategy(),
        middleware: buildMiddleware(),
      }).then((result) => {
        if (token !== epoch) return
        setX(result.x)
        setY(result.y)
        setPositioned(true)
        setFinalPlacement(result.placement)
        const arrowData = result.middlewareData.arrow as { x?: number; y?: number } | undefined
        setArrowX(arrowData?.x)
        setArrowY(arrowData?.y)
      })
    }
    const cleanup = autoUpdate(a, f, update)
    onCleanup(() => {
      epoch++
      cleanup()
    })
  })

  const OPPOSITE: Record<string, 'top' | 'right' | 'bottom' | 'left'> = {
    top: 'bottom',
    bottom: 'top',
    left: 'right',
    right: 'left',
  }
  const arrowSide = (): 'top' | 'right' | 'bottom' | 'left' | undefined =>
    OPPOSITE[finalPlacement().split('-')[0]]

  const floatingStyles = (): JSX.CSSProperties => ({
    position: strategy(),
    top: '0',
    left: '0',
    transform: `translate3d(${Math.round(x())}px, ${Math.round(y())}px, 0)`,
    width: 'max-content',
    // Hidden until the first positioning cycle lands — prevents a flash at
    // the viewport origin. visibility (not display:none) keeps the panel
    // measurable so Floating UI can compute its real coordinates.
    visibility: positioned() ? 'visible' : 'hidden',
  })

  return { finalPlacement, floatingStyles, arrowX, arrowY, arrowSide }
}

// packages/react/src/floating/useFloating.ts
import * as React from 'react'
import {
  autoUpdate,
  computePosition,
  arrow as arrowMiddleware,
  flip as flipMiddleware,
  offset as offsetMiddleware,
  shift as shiftMiddleware,
  size as sizeMiddleware,
  type Middleware,
  type Placement,
  type Strategy,
} from '@floating-ui/dom'

export interface UseFloatingOptions {
  /** Element the floating panel is positioned relative to. */
  anchor: React.RefObject<HTMLElement | null>
  /** The floating element itself. */
  floating: React.RefObject<HTMLElement | null>
  /** Whether the floating element is visible. Controls `autoUpdate` lifecycle. */
  open: boolean
  /** Default placement. Floating UI may flip it if `flip` is true. */
  placement?: Placement
  /** CSS position strategy. */
  strategy?: Strategy
  /** Pixel offset between anchor and floating element. */
  offset?: number
  /** Flip to the opposite side when the requested side overflows. Default `true`. */
  flip?: boolean
  /** Shift along the cross-axis to stay in view. Default `true`. */
  shift?: boolean
  /**
   * Constrain the floating element to the available viewport space — sets
   * `maxWidth`/`maxHeight` (minus 8px padding) on it so a long dropdown/popover
   * never overflows the screen (pair with `overflow:auto` for scroll). Off by
   * default. Pass a number to override the viewport padding.
   */
  size?: boolean | number
  /** Extra Floating UI middleware to append. */
  middleware?: Middleware[]
  /**
   * Optional ref to an arrow element inside the floating panel. When provided,
   * `arrowX`, `arrowY`, and `arrowSide` in the return value are populated by the
   * `@floating-ui/dom` arrow middleware so you can position the caret CSS.
   */
  arrow?: React.RefObject<HTMLElement | null>
}

export interface UseFloatingReturn {
  x: number
  y: number
  strategy: Strategy
  finalPlacement: Placement
  /** Ready-to-bind inline style object for the floating element. */
  floatingStyles: React.CSSProperties
  /** Trigger a manual recompute. Usually not needed — `autoUpdate` handles scroll/resize. */
  update: () => Promise<void>
  /** Arrow x offset (px from floating start edge). Present when `arrow` option is set. */
  arrowX: number | undefined
  /** Arrow y offset (px from floating start edge). Present when `arrow` option is set. */
  arrowY: number | undefined
  /**
   * The side of the floating element the arrow is on — use as the CSS property
   * to apply `bottom: 0` / `top: 0` etc. to the arrow element.
   * E.g. `'bottom'` placement → arrow is on `'top'` of the floating element.
   */
  arrowSide: 'top' | 'right' | 'bottom' | 'left' | undefined
}

/**
 * Reactive Floating UI integration for React. Subscribes `autoUpdate`
 * whenever `open === true` and both refs are populated; tears it down on
 * close, unmount, or ref clearing.
 *
 * Pure positioning — does NOT render anything, does NOT manage focus,
 * does NOT handle dismiss behavior. Those concerns live in the consuming
 * primitive (Popover, Tooltip, Dialog, Menu, …).
 */
export function useFloating(options: UseFloatingOptions): UseFloatingReturn {
  const {
    anchor,
    floating,
    open,
    placement = 'bottom',
    strategy = 'absolute',
    offset,
    flip = true,
    shift = true,
    size = false,
    middleware: extraMiddleware,
    arrow,
  } = options

  const [x, setX] = React.useState(0)
  const [y, setY] = React.useState(0)
  const [finalPlacement, setFinalPlacement] = React.useState<Placement>(placement)
  // True once the first positioning cycle lands. Until then the panel stays
  // `visibility: hidden` so it never flashes at the viewport origin (0,0)
  // before its real coordinates arrive.
  const [positioned, setPositioned] = React.useState(false)
  const [arrowX, setArrowX] = React.useState<number | undefined>()
  const [arrowY, setArrowY] = React.useState<number | undefined>()

  const middleware = React.useMemo<Middleware[]>(() => {
    const mw: Middleware[] = []
    if (offset !== undefined) mw.push(offsetMiddleware(offset))
    if (flip) mw.push(flipMiddleware())
    if (shift) mw.push(shiftMiddleware({ padding: 8 }))
    if (size) {
      const padding = typeof size === 'number' ? size : 8
      mw.push(
        sizeMiddleware({
          padding,
          apply({ availableWidth, availableHeight, elements }) {
            Object.assign(elements.floating.style, {
              maxWidth: `${Math.max(0, Math.floor(availableWidth))}px`,
              maxHeight: `${Math.max(0, Math.floor(availableHeight))}px`,
            })
          },
        }),
      )
    }
    if (arrow?.current) mw.push(arrowMiddleware({ element: arrow.current }))
    if (extraMiddleware) mw.push(...extraMiddleware)
    return mw
  }, [offset, flip, shift, size, extraMiddleware, arrow])

  // Hold the latest middleware in a ref so `update` always sees current value
  // without being re-created (which would churn the autoUpdate subscription).
  const middlewareRef = React.useRef(middleware)
  middlewareRef.current = middleware

  // Monotonic token bumped on every new positioning cycle and on teardown.
  // `computePosition` is async; without this guard a result that resolves
  // after the panel closed/unmounted (or after a newer update started) would
  // apply stale coordinates and call setState on an unmounted component.
  const epochRef = React.useRef(0)

  const update = React.useCallback(async () => {
    const a = anchor.current
    const f = floating.current
    if (!a || !f) return
    const token = ++epochRef.current
    const result = await computePosition(a, f, {
      placement,
      strategy,
      middleware: middlewareRef.current,
    })
    // A newer update() started, or the effect tore down, while awaiting — drop.
    if (token !== epochRef.current) return
    setX(result.x)
    setY(result.y)
    setPositioned(true)
    setFinalPlacement(result.placement)
    const arrowData = result.middlewareData.arrow as { x?: number; y?: number } | undefined
    setArrowX(arrowData?.x)
    setArrowY(arrowData?.y)
  }, [anchor, floating, placement, strategy])

  React.useEffect(() => {
    if (!open) return
    const a = anchor.current
    const f = floating.current
    if (!a || !f) return
    // Fresh open → hide until the first computePosition cycle completes.
    setPositioned(false)
    const cleanup = autoUpdate(a, f, () => {
      void update()
    })
    return () => {
      // Invalidate any in-flight update() so its late result never lands.
      epochRef.current++
      cleanup()
    }
  }, [open, anchor, floating, update])

  const floatingStyles = React.useMemo<React.CSSProperties>(
    () => ({
      position: strategy,
      top: 0,
      left: 0,
      transform: `translate3d(${Math.round(x)}px, ${Math.round(y)}px, 0)`,
      width: 'max-content',
      // Hidden until the first positioning cycle lands — prevents a flash at
      // the viewport origin. `visibility` (not `display:none`) keeps the panel
      // measurable so Floating UI can compute its real coordinates.
      visibility: positioned ? undefined : 'hidden',
    }),
    [strategy, x, y, positioned],
  )

  const OPPOSITE: Record<string, 'top' | 'right' | 'bottom' | 'left'> = {
    top: 'bottom',
    bottom: 'top',
    left: 'right',
    right: 'left',
  }
  const arrowSide = OPPOSITE[finalPlacement.split('-')[0]] as
    'top' | 'right' | 'bottom' | 'left' | undefined

  return { x, y, strategy, finalPlacement, floatingStyles, update, arrowX, arrowY, arrowSide }
}
