// packages/solid/src/FormContractHarness.tsx
import { IrisForm } from './form/IrisForm'
import { useForm } from './form/useForm'
import { useField } from './form/useField'

function NameField() {
  const field = useField<string>('name')
  return (
    <div data-iris-form-field="">
      <input
        aria-label="name"
        data-iris-input=""
        value={field.value() ?? ''}
        onInput={(e) => field.setValue((e.target as HTMLInputElement).value)}
        onBlur={() => field.setTouched(true)}
      />
      {field.error() && <span data-iris-form-error="">{field.error()}</span>}
    </div>
  )
}

export function FormContractHarness() {
  const form = useForm({
    initialValues: { name: '' },
    validators: { name: (v: string) => (v ? undefined : 'Required') },
  })
  return (
    <IrisForm form={form.form}>
      <NameField />
    </IrisForm>
  )
}

// packages/svelte/src/FormContractHarness.svelte
<script lang="ts">
  import { IrisForm, useForm } from './form'
  import type { FormStore, FormValues } from '@iris-ui/core'

  const form = useForm({
    initialValues: { name: '' },
    validators: { name: (v: string) => (v ? undefined : 'Required') },
  })
  const store = form.form as unknown as FormStore<FormValues>
  const state = $state(store.getState())

  store.subscribe((s) => {
    Object.assign(state, s)
  })

  function onInput(e: Event) {
    store.setFieldValue('name', (e.target as HTMLInputElement).value)
  }
</script>

<IrisForm form={store}>
  <div data-iris-form-field="">
    <input
      aria-label="name"
      data-iris-input=""
      value={state.values.name as string}
      oninput={onInput}
    />
    {#if state.errors.name}
      <span data-iris-form-error="">{state.errors.name}</span>
    {/if}
  </div>
</IrisForm>
