// packages/solid/src/primitives/menu/IrisMenuItem.tsx
import { splitProps, type JSX } from 'solid-js'
import { useMenuContext } from './context'

export interface IrisMenuItemProps extends JSX.HTMLAttributes<HTMLDivElement> {
  disabled?: boolean
  /** Close the root menu after selection (default true). */
  closeOnSelect?: boolean
  children?: JSX.Element
}

/**
 * An individual menu item. Calls `closeRoot` after being selected unless
 * selection is canceled or `closeOnSelect={false}`. Solid port of the Vue
 * IrisMenuItem.
 */
export function IrisMenuItem(props: IrisMenuItemProps): JSX.Element {
  const ctx = useMenuContext('IrisMenuItem')
  const [local, others] = splitProps(props, ['disabled', 'closeOnSelect', 'onClick', 'children'])

  const select = (event: MouseEvent | KeyboardEvent, suppressNativeDefault = false): void => {
    if (local.disabled) {
      if (suppressNativeDefault) event.preventDefault()
      return
    }
    if (typeof local.onClick === 'function')
      local.onClick(
        event as unknown as MouseEvent & { currentTarget: HTMLDivElement; target: Element },
      )
    const selectionCanceled = event.defaultPrevented
    if (suppressNativeDefault) event.preventDefault()
    if (local.closeOnSelect !== false && !selectionCanceled) ctx.closeRoot()
  }

  const handleClick: JSX.EventHandler<HTMLDivElement, MouseEvent> = (e) => {
    select(e)
  }

  const handleKeyDown: JSX.EventHandler<HTMLDivElement, KeyboardEvent> = (e) => {
    if (e.key === 'Enter' || e.key === ' ') select(e, true)
  }

  return (
    <div
      {...(others as JSX.HTMLAttributes<HTMLDivElement>)}
      role="menuitem"
      tabindex={local.disabled ? -1 : 0}
      aria-disabled={local.disabled ? 'true' : undefined}
      data-iris-menu-item=""
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      style={{
        padding: 'var(--iris-padding-sm, 6px) var(--iris-padding-md, 12px)',
        'font-size': 'var(--iris-font-size-md, 14px)',
        'border-radius': 'var(--iris-radius-sm, 4px)',
        cursor: local.disabled ? 'not-allowed' : 'pointer',
        color: local.disabled ? 'var(--iris-muted)' : 'var(--iris-foreground)',
        outline: 'none',
        ...((others.style as JSX.CSSProperties) ?? {}),
      }}
    >
      {local.children}
    </div>
  )
}

export type IrisMenuSeparatorProps = JSX.HTMLAttributes<HTMLDivElement>

/** Visual separator between menu items. */
export function IrisMenuSeparator(props: IrisMenuSeparatorProps): JSX.Element {
  return (
    <div
      {...props}
      role="separator"
      data-iris-menu-separator=""
      style={{
        height: '1px',
        background: 'var(--iris-border)',
        margin: '4px 0',
        ...((props.style as JSX.CSSProperties) ?? {}),
      }}
    />
  )
}

// packages/svelte/src/primitives/menu/IrisMenuItem.svelte
<script lang="ts">
  import { getMenuContext } from './context'

  interface Props {
    disabled?: boolean
    closeOnSelect?: boolean
    onclick?: (e: MouseEvent) => void
    children?: import('svelte').Snippet
    [key: string]: unknown
  }

  let { disabled = false, closeOnSelect = true, onclick, children, ...rest }: Props = $props()
  const ctx = getMenuContext('IrisMenuItem')

  function select(e: MouseEvent | KeyboardEvent, suppressNativeDefault = false): void {
    if (disabled) {
      if (suppressNativeDefault) e.preventDefault()
      return
    }
    onclick?.(e as MouseEvent)
    const selectionCanceled = e.defaultPrevented
    if (suppressNativeDefault) e.preventDefault()
    // Close the whole tree — a leaf inside a submenu collapses everything
    // (matches React/Solid), unless selection is canceled or opted out. At the
    // root, closeRoot === setOpen(false).
    if (closeOnSelect && !selectionCanceled) ctx.closeRoot()
  }

  function handleClick(e: MouseEvent): void {
    select(e)
  }
</script>

<div
  role="menuitem"
  tabindex={disabled ? -1 : 0}
  aria-disabled={disabled ? 'true' : undefined}
  data-iris-menu-item
  data-disabled={disabled ? '' : undefined}
  {...rest}
  onclick={handleClick}
  onkeydown={(e) => {
    if (e.key === 'Enter' || e.key === ' ') {
      select(e, true)
    }
  }}
  style="padding: var(--iris-padding-sm, 4px) var(--iris-padding-md, 8px); cursor: {disabled
    ? 'not-allowed'
    : 'pointer'}; border-radius: var(--iris-radius-sm, 3px); color: {disabled
    ? 'var(--iris-muted)'
    : 'var(--iris-foreground)'}; outline: none; {(rest.style as string) ?? ''}"
>
  {@render children?.()}
</div>
