// packages/solid/src/primitives/command-palette/IrisCommandPalette.tsx
import {
  createSignal,
  createMemo,
  createEffect,
  mergeProps,
  splitProps,
  Show,
  For,
  onCleanup,
  type JSX,
} from 'solid-js'
import { firstEnabledIndex, nextEnabledIndex } from '@iris-ui-kit/core'
import { type IrisCommandItem, defaultFilter } from './types'
import { useI18n } from '../../i18n'
import { useFocusTrap } from '../../modal-utils'

export interface IrisCommandPaletteProps {
  open?: boolean
  defaultOpen?: boolean
  items?: IrisCommandItem[]
  placeholder?: string
  emptyText?: string
  /** Custom fuzzy-match scorer; return null to exclude. Defaults to `defaultFilter`. */
  filter?: (query: string, item: IrisCommandItem) => number | null
  onOpenChange?: (open: boolean) => void
  onSelect?: (item: IrisCommandItem) => void
}

/**
 * Command palette: modal search dialog with grouped results + keyboard navigation.
 * Solid port of the Vue IrisCommandPalette.
 */
export function IrisCommandPalette(props: IrisCommandPaletteProps): JSX.Element {
  const { t } = useI18n()
  const merged = mergeProps(
    {
      defaultOpen: false,
      items: [] as IrisCommandItem[],
    },
    props,
  )
  const [local] = splitProps(merged, [
    'open',
    'defaultOpen',
    'items',
    'placeholder',
    'emptyText',
    'filter',
    'onOpenChange',
    'onSelect',
  ])

  const [internalOpen, setInternalOpen] = createSignal(local.defaultOpen)
  const [query, setQuery] = createSignal('')
  const [activeIdx, setActiveIdx] = createSignal(0)

  const open = () => (local.open !== undefined ? local.open : internalOpen())
  const setOpen = (v: boolean) => {
    if (local.open === undefined) setInternalOpen(v)
    local.onOpenChange?.(v)
  }

  const filterFn = () => local.filter ?? defaultFilter
  const filtered = createMemo(() => {
    const q = query()
    const score = filterFn()
    const results = local.items
      .map((item) => ({ item, score: score(q, item) }))
      .filter((r) => r.score !== null)
      .sort((a, b) => (a.score ?? 0) - (b.score ?? 0))
    return results.map((r) => r.item)
  })

  // Group the filtered items
  const grouped = createMemo(() => {
    const groups = new Map<string, IrisCommandItem[]>()
    for (const item of filtered()) {
      const key = item.group ?? ''
      if (!groups.has(key)) groups.set(key, [])
      groups.get(key)!.push(item)
    }
    return Array.from(groups.entries())
  })

  const flatItems = createMemo(() => filtered())

  const select = (item: IrisCommandItem) => {
    if (item.disabled) return
    item.action?.()
    local.onSelect?.(item)
    setOpen(false)
    setQuery('')
  }

  const isEnabled = (i: number): boolean => !flatItems()[i]?.disabled

  // Reset active idx to the first ENABLED item when the filtered list changes.
  createEffect(() => {
    const items = filtered()
    const first = firstEnabledIndex(items.length, (i) => !items[i]?.disabled)
    setActiveIdx(first >= 0 ? first : 0)
  })

  // Reset query + active index when the palette (re)opens, matching React/Vue/Svelte.
  let wasOpen = false
  createEffect(() => {
    const o = open()
    if (o && !wasOpen) {
      setQuery('')
      setActiveIdx(0)
    }
    wasOpen = o
  })

  // Trap Tab focus inside the panel and restore focus to the previously-focused
  // element on close (matches React/Vue, which use the same focus-trap).
  let panelEl: HTMLDivElement | undefined
  useFocusTrap({ container: () => panelEl, active: open })

  // Global keyboard shortcut: Cmd/Ctrl+K to open
  const onDocKeyDown = (e: KeyboardEvent) => {
    if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
      e.preventDefault()
      setOpen(!open())
      if (!open()) setQuery('')
    }
    if (e.key === 'Escape' && open()) {
      e.preventDefault()
      setOpen(false)
      setQuery('')
    }
  }

  document.addEventListener('keydown', onDocKeyDown)
  onCleanup(() => document.removeEventListener('keydown', onDocKeyDown))

  const onInputKeyDown = (e: KeyboardEvent) => {
    const items = flatItems()
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      // Skip disabled rows and wrap at the ends (mirrors React/Vue/Svelte).
      setActiveIdx((i) => nextEnabledIndex(i, 1, items.length, isEnabled, true))
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      setActiveIdx((i) => nextEnabledIndex(i, -1, items.length, isEnabled, true))
    } else if (e.key === 'Enter') {
      e.preventDefault()
      const item = items[activeIdx()]
      if (item) select(item)
    } else if (e.key === 'Escape') {
      e.preventDefault()
      setOpen(false)
      setQuery('')
    }
  }

  return (
    <Show when={open()}>
      <div
        data-iris-command-palette=""
        data-state="open"
        role="dialog"
        aria-modal="true"
        aria-label={t('commandPalette.label')}
        style={{
          position: 'fixed',
          inset: '0',
          display: 'flex',
          'align-items': 'flex-start',
          'justify-content': 'center',
          'padding-top': '15vh',
          background: 'var(--iris-backdrop, rgba(0, 0, 0, 0.5))',
          'z-index': '1000',
        }}
        onClick={(e) => {
          if (e.target === e.currentTarget) {
            setOpen(false)
            setQuery('')
          }
        }}
      >
        <div
          ref={panelEl}
          data-iris-command-palette-panel=""
          style={{
            width: '100%',
            'max-width': '560px',
            background: 'var(--iris-surface)',
            border: '1px solid var(--iris-border)',
            'border-radius': 'var(--iris-radius-lg, 8px)',
            'box-shadow': 'var(--iris-shadow-lg)',
            overflow: 'hidden',
          }}
        >
          {/* Search input */}
          <div style={{ padding: '12px', 'border-bottom': '1px solid var(--iris-border)' }}>
            <input
              type="text"
              data-iris-command-palette-input=""
              placeholder={local.placeholder ?? t('commandPalette.placeholder')}
              value={query()}
              onInput={(e) => setQuery(e.currentTarget.value)}
              onKeyDown={onInputKeyDown}
              autofocus
              style={{
                width: '100%',
                padding: '8px 12px',
                background: 'transparent',
                border: 'none',
                outline: 'none',
                'font-size': 'var(--iris-font-size-lg, 16px)',
                color: 'var(--iris-foreground)',
                'font-family': 'inherit',
              }}
            />
          </div>

          {/* Results */}
          <div
            data-iris-command-palette-results=""
            role="listbox"
            style={{
              'max-height': '320px',
              'overflow-y': 'auto',
              padding: '4px',
            }}
          >
            <Show
              when={flatItems().length > 0}
              fallback={
                <div
                  style={{
                    padding: '20px',
                    'text-align': 'center',
                    color: 'var(--iris-muted)',
                    'font-size': 'var(--iris-font-size-md, 14px)',
                  }}
                >
                  {local.emptyText ?? t('commandPalette.empty')}
                </div>
              }
            >
              <For each={grouped()}>
                {([group, items]) => (
                  <div data-iris-command-palette-group="">
                    <Show when={group}>
                      <div
                        style={{
                          padding:
                            'var(--iris-padding-sm, 6px) var(--iris-space-xs, 8px) var(--iris-space-xxs, 4px)',
                          'font-size': 'var(--iris-font-size-xs, 12px)',
                          'font-weight': '600',
                          color: 'var(--iris-muted)',
                          'text-transform': 'uppercase',
                          'letter-spacing': 'var(--iris-font-letter-spacing-wide, 0.04em)',
                        }}
                      >
                        {group}
                      </div>
                    </Show>
                    <For each={items}>
                      {(item) => {
                        const isActive = () =>
                          flatItems().indexOf(item) === activeIdx() && !item.disabled

                        return (
                          <div
                            role="option"
                            aria-selected={isActive()}
                            aria-disabled={item.disabled ? 'true' : undefined}
                            data-iris-command-palette-item={item.id}
                            data-active={isActive() ? 'true' : undefined}
                            onClick={() => select(item)}
                            onMouseEnter={() => setActiveIdx(flatItems().indexOf(item))}
                            style={{
                              display: 'flex',
                              'align-items': 'center',
                              gap: '8px',
                              padding: 'var(--iris-space-xs, 8px) var(--iris-space-sm, 12px)',
                              'border-radius': 'var(--iris-radius-sm, 4px)',
                              background: isActive() ? 'var(--iris-primary)' : 'transparent',
                              color: isActive()
                                ? 'var(--iris-primary-foreground)'
                                : item.disabled
                                  ? 'var(--iris-muted)'
                                  : 'var(--iris-foreground)',
                              cursor: item.disabled ? 'not-allowed' : 'pointer',
                              opacity: item.disabled ? '0.5' : '1',
                              'font-size': 'var(--iris-font-size-md, 14px)',
                            }}
                          >
                            <Show when={item.icon}>
                              <span
                                aria-hidden="true"
                                style={{ 'font-size': 'var(--iris-font-size-lg, 16px)' }}
                              >
                                {item.icon}
                              </span>
                            </Show>
                            <span style={{ flex: '1' }}>{item.label}</span>
                            <Show when={item.shortcut}>
                              <kbd
                                style={{
                                  'font-size': 'var(--iris-font-size-xs, 12px)',
                                  padding: 'var(--iris-space-xxs, 4px) var(--iris-space-xxs, 4px)',
                                  background: 'rgba(0,0,0,0.1)',
                                  'border-radius': '3px',
                                  opacity: '0.7',
                                }}
                              >
                                {item.shortcut}
                              </kbd>
                            </Show>
                          </div>
                        )
                      }}
                    </For>
                  </div>
                )}
              </For>
            </Show>
          </div>
        </div>
      </div>
    </Show>
  )
}

// packages/svelte/src/primitives/command-palette/IrisCommandPalette.svelte
<script lang="ts">
  import { portal } from '../../internal/portal'
  import { useI18n } from '../../i18n'
  import { useFocusTrap } from '../modal-utils/useFocusTrap.svelte'
  import type { IrisCommandItem } from './types'
  import { defaultFilter } from './types'

  interface Props {
    open?: boolean
    items?: IrisCommandItem[]
    placeholder?: string
    emptyText?: string
    filter?: (query: string, item: IrisCommandItem) => number | null
    onOpenChange?: (open: boolean) => void
    onSelect?: (item: IrisCommandItem) => void
  }

  let {
    open = false,
    items = [],
    placeholder,
    emptyText,
    filter = defaultFilter,
    onOpenChange,
    onSelect,
  }: Props = $props()

  const { t } = useI18n()

  const resolvedPlaceholder = $derived(placeholder ?? t('commandPalette.placeholder'))

  let query = $state('')
  let activeIndex = $state(0)
  let inputEl = $state<HTMLInputElement | undefined>(undefined)
  let panelEl = $state<HTMLElement | undefined>(undefined)

  // Trap Tab focus inside the panel and restore focus to the previously-focused
  // element on close (matches React/Vue, which use the same focus-trap).
  useFocusTrap({ container: () => panelEl, active: () => open })

  $effect(() => {
    if (open) {
      query = ''
      activeIndex = 0
      requestAnimationFrame(() => inputEl?.focus())
    }
  })

  $effect(() => {
    void query
    activeIndex = 0
  })

  type Row = { kind: 'header'; label: string } | { kind: 'item'; item: IrisCommandItem }

  const matches = $derived(
    (() => {
      const result: { item: IrisCommandItem; score: number }[] = []
      for (const item of items) {
        const score = filter(query, item)
        if (score !== null) result.push({ item, score })
      }
      return result.sort((a, b) => a.score - b.score)
    })(),
  )

  const rows = $derived<Row[]>(
    (() => {
      const out: Row[] = []
      let currentGroup: string | undefined = undefined
      for (const m of matches) {
        const g = m.item.group
        if (g !== currentGroup) {
          if (g) out.push({ kind: 'header', label: g })
          currentGroup = g
        }
        out.push({ kind: 'item', item: m.item })
      }
      return out
    })(),
  )

  const enabledItems = $derived(
    rows.filter(
      (r): r is { kind: 'item'; item: IrisCommandItem } => r.kind === 'item' && !r.item.disabled,
    ),
  )

  function close() {
    onOpenChange?.(false)
  }

  function selectItem(item: IrisCommandItem) {
    if (item.disabled) return
    item.action?.()
    onSelect?.(item)
    close()
  }

  function onKeyDown(e: KeyboardEvent) {
    const ei = enabledItems
    switch (e.key) {
      case 'Escape':
        e.preventDefault()
        close()
        break
      case 'ArrowDown':
        e.preventDefault()
        activeIndex = (activeIndex + 1) % Math.max(1, ei.length)
        break
      case 'ArrowUp':
        e.preventDefault()
        activeIndex = (activeIndex - 1 + Math.max(1, ei.length)) % Math.max(1, ei.length)
        break
      case 'Enter':
        e.preventDefault()
        if (ei[activeIndex]) selectItem(ei[activeIndex].item)
        break
    }
  }

  function onBackdropClick(e: MouseEvent) {
    if (e.target === e.currentTarget) close()
  }
</script>

{#if open}
  <div
    use:portal
    data-iris-command-palette-backdrop
    role="presentation"
    onclick={onBackdropClick}
    onkeydown={onKeyDown}
    style:position="fixed"
    style:inset="0"
    style:z-index="100"
    style:display="flex"
    style:align-items="flex-start"
    style:justify-content="center"
    style:padding-top="15vh"
    style:background="rgba(0,0,0,0.4)"
  >
    <div
      bind:this={panelEl}
      data-iris-command-palette
      role="dialog"
      aria-modal="true"
      aria-label={t('commandPalette.label')}
      style:background="var(--iris-background)"
      style:border="1px solid var(--iris-border)"
      style:border-radius="var(--iris-radius-lg, 8px)"
      style:box-shadow="var(--iris-shadow-xl)"
      style:width="min(560px, 90vw)"
      style:overflow="hidden"
      style:display="flex"
      style:flex-direction="column"
    >
      <!-- Search input -->
      <div style:padding="12px 16px" style:border-bottom="1px solid var(--iris-border)">
        <input
          bind:this={inputEl}
          bind:value={query}
          type="text"
          placeholder={resolvedPlaceholder}
          data-iris-command-palette-input
          style:width="100%"
          style:border="none"
          style:outline="none"
          style:background="transparent"
          style:color="var(--iris-foreground)"
          style:font-size="16px"
          style:font-family="inherit"
        />
      </div>

      <!-- Results -->
      <div
        data-iris-command-palette-list
        role="listbox"
        style:overflow-y="auto"
        style:max-height="360px"
        style:padding="4px"
      >
        {#if rows.length === 0}
          <div
            data-iris-command-palette-empty
            style:padding="24px"
            style:text-align="center"
            style:color="var(--iris-muted)"
            style:font-size="14px"
          >
            {emptyText ?? t('commandPalette.empty')}
          </div>
        {:else}
          {#each rows as row, i (row.kind === 'item' ? row.item.id : `header-${i}`)}
            {#if row.kind === 'header'}
              <div
                data-iris-command-palette-group
                style="padding: var(--iris-padding-sm, 6px) var(--iris-space-xs, 8px) var(--iris-space-xxs, 4px); font-size: var(--iris-font-size-xs, 12px); font-weight: 600; color: var(--iris-muted); text-transform: uppercase; letter-spacing: 0.05em"
              >
                {row.label}
              </div>
            {:else}
              {@const eiIdx = enabledItems.findIndex((x) => x.item.id === row.item.id)}
              {@const isActive = eiIdx === activeIndex && !row.item.disabled}
              <button
                type="button"
                role="option"
                aria-selected={isActive}
                aria-disabled={row.item.disabled ? 'true' : undefined}
                data-iris-command-palette-item
                data-state={isActive ? 'active' : 'idle'}
                onclick={() => selectItem(row.item)}
                style:width="100%"
                style:display="flex"
                style:align-items="center"
                style:gap="8px"
                style:padding="8px 12px"
                style:border="none"
                style:border-radius="var(--iris-radius-sm, 4px)"
                style:background={isActive ? 'var(--iris-surface-hover)' : 'transparent'}
                style:color={row.item.disabled ? 'var(--iris-muted)' : 'var(--iris-foreground)'}
                style:cursor={row.item.disabled ? 'not-allowed' : 'pointer'}
                style:text-align="start"
                style:font-size="14px"
                style:font-family="inherit"
                style:opacity={row.item.disabled ? '0.5' : '1'}
              >
                {#if row.item.icon}
                  <span aria-hidden="true">{row.item.icon}</span>
                {/if}
                <span style:flex="1">{row.item.label}</span>
                {#if row.item.shortcut}
                  <kbd
                    style:font-size="11px"
                    style:padding="var(--iris-space-xxs, 4px) var(--iris-padding-sm, 6px)"
                    style:border="1px solid var(--iris-border)"
                    style:border-radius="3px"
                    style:background="var(--iris-surface)"
                    style:color="var(--iris-muted)">{row.item.shortcut}</kbd
                  >
                {/if}
              </button>
            {/if}
          {/each}
        {/if}
      </div>
    </div>
  </div>
{/if}
