// packages/svelte/src/primitives/card/IrisCard.svelte
<script lang="ts">
  import { styleToString, mergeStyle } from '../../internal/style'

  type CardVariant = 'elevated' | 'outline' | 'subtle'
  type CardPadding = 'none' | 'sm' | 'md' | 'lg'

  const PADDING_MAP: Record<CardPadding, string> = {
    none: '0',
    sm: '12px',
    md: 'var(--iris-padding-md, 16px)',
    lg: '24px',
  }

  let {
    variant = 'elevated' as CardVariant,
    padding = 'md' as CardPadding,
    hover = false,
    style,
    children,
    header,
    footer,
    ...rest
  } = $props()

  const containerStyle = $derived(() => {
    const base = {
      display: 'flex',
      'flex-direction': 'column',
      background: 'var(--iris-background)',
      color: 'var(--iris-foreground)',
      'border-radius': 'var(--iris-radius-md, 8px)',
      overflow: 'hidden',
      transition: hover ? 'transform 160ms ease, box-shadow 160ms ease' : 'none',
    }
    const v = variant as CardVariant
    if (v === 'elevated')
      return { ...base, 'box-shadow': '0 1px 2px rgba(0,0,0,.05), 0 4px 12px rgba(0,0,0,.06)' }
    if (v === 'outline') return { ...base, border: '1px solid var(--iris-border)' }
    // subtle
    return { ...base, background: 'var(--iris-surface)' }
  })

  const sectionPadding = $derived(PADDING_MAP[padding as CardPadding] ?? PADDING_MAP.md)
</script>

<div
  {...rest}
  data-iris-card
  data-iris-card-variant={variant}
  data-iris-card-padding={padding}
  data-iris-card-hover={hover ? 'true' : undefined}
  style={mergeStyle(styleToString(containerStyle()), style)}
>
  {#if header}
    <div
      data-iris-card-header
      style="padding: {sectionPadding}; border-bottom: 1px solid var(--iris-border); font-weight: 600"
    >
      {@render header()}
    </div>
  {/if}
  {#if children}
    <div data-iris-card-body style="padding: {sectionPadding}; flex: 1">
      {@render children()}
    </div>
  {/if}
  {#if footer}
    <div
      data-iris-card-footer
      style="padding: {sectionPadding}; border-top: 1px solid var(--iris-border)"
    >
      {@render footer()}
    </div>
  {/if}
</div>

// packages/solid/src/primitives/card/IrisCard.tsx
import { mergeProps, Show, splitProps, type JSX } from 'solid-js'

export type IrisCardVariant = 'elevated' | 'outline' | 'subtle'
export type IrisCardPadding = 'none' | 'sm' | 'md' | 'lg'

const PADDING_MAP: Record<IrisCardPadding, string> = {
  none: '0',
  sm: '12px',
  md: 'var(--iris-padding-md, 16px)',
  lg: '24px',
}

export interface IrisCardProps extends JSX.HTMLAttributes<HTMLDivElement> {
  variant?: IrisCardVariant
  padding?: IrisCardPadding
  hover?: boolean
  header?: JSX.Element
  footer?: JSX.Element
  children?: JSX.Element
}

function containerStyle(variant: IrisCardVariant, hover: boolean): JSX.CSSProperties {
  const base: JSX.CSSProperties = {
    display: 'flex',
    'flex-direction': 'column',
    background: 'var(--iris-background)',
    color: 'var(--iris-foreground)',
    'border-radius': 'var(--iris-radius-md, 8px)',
    overflow: 'hidden',
    transition: hover ? 'transform 160ms ease, box-shadow 160ms ease' : 'none',
  }
  if (variant === 'elevated')
    return { ...base, 'box-shadow': '0 1px 2px rgba(0,0,0,.05), 0 4px 12px rgba(0,0,0,.06)' }
  if (variant === 'outline') return { ...base, border: '1px solid var(--iris-border)' }
  return { ...base, background: 'var(--iris-surface)' }
}

/**
 * Card surface with three visual variants: elevated (default), outline, subtle.
 * Slots: header, default body, footer.
 */
export function IrisCard(props: IrisCardProps): JSX.Element {
  const merged = mergeProps(
    { variant: 'elevated' as IrisCardVariant, padding: 'md' as IrisCardPadding, hover: false },
    props,
  )
  const [local, rest] = splitProps(merged, [
    'variant',
    'padding',
    'hover',
    'header',
    'footer',
    'style',
    'children',
  ])

  const sectionPadding = () => PADDING_MAP[local.padding]

  return (
    <div
      {...rest}
      data-iris-card=""
      data-iris-card-variant={local.variant}
      data-iris-card-padding={local.padding}
      data-iris-card-hover={local.hover ? 'true' : undefined}
      style={{
        ...containerStyle(local.variant, local.hover),
        ...((local.style as JSX.CSSProperties) ?? {}),
      }}
    >
      <Show when={local.header}>
        <div
          data-iris-card-header=""
          style={{
            padding: sectionPadding(),
            'border-bottom': '1px solid var(--iris-border)',
            'font-weight': '600',
          }}
        >
          {local.header}
        </div>
      </Show>
      <Show when={local.children}>
        <div data-iris-card-body="" style={{ padding: sectionPadding(), flex: '1' }}>
          {local.children}
        </div>
      </Show>
      <Show when={local.footer}>
        <div
          data-iris-card-footer=""
          style={{
            padding: sectionPadding(),
            'border-top': '1px solid var(--iris-border)',
          }}
        >
          {local.footer}
        </div>
      </Show>
    </div>
  )
}
