// packages/solid/src/primitives/tag-input/IrisTagInput.tsx
import { createSignal, For, mergeProps, splitProps, type JSX } from 'solid-js'
import { useI18n } from '../../i18n'

export interface IrisTagInputProps {
  value?: string[]
  defaultValue?: string[]
  placeholder?: string
  disabled?: boolean
  invalid?: boolean
  max?: number
  allowDuplicates?: boolean
  id?: string
  ariaDescribedby?: string
  onChange?: (tags: string[]) => void
  style?: JSX.CSSProperties | string
  class?: string
}

/** Solid port of IrisTagInput — text + removable tags; Enter/comma creates tags. */
export function IrisTagInput(props: IrisTagInputProps): JSX.Element {
  const merged = mergeProps({ allowDuplicates: false }, props)
  const [local, rest] = splitProps(merged, [
    'value',
    'defaultValue',
    'placeholder',
    'disabled',
    'invalid',
    'max',
    'allowDuplicates',
    'id',
    'ariaDescribedby',
    'onChange',
    'style',
  ])

  const { t } = useI18n()

  const isControlled = (): boolean => local.value !== undefined
  const [internal, setInternal] = createSignal<string[]>(local.defaultValue ?? [])
  const current = (): string[] => (isControlled() ? (local.value as string[]) : internal())

  const [inputText, setInputText] = createSignal('')
  const [focused, setFocused] = createSignal(false)

  const canAdd = (txt: string, list: string[]): boolean =>
    !!txt &&
    (local.allowDuplicates || !list.includes(txt)) &&
    (!local.max || list.length < local.max)

  const updateTags = (next: string[]): void => {
    if (!isControlled()) setInternal(next)
    local.onChange?.(next)
  }

  const addTag = (): void => {
    const txt = inputText().trim()
    if (txt && canAdd(txt, current())) updateTags([...current(), txt])
    setInputText('')
  }

  const removeAt = (i: number): void => {
    if (local.disabled) return
    updateTags(current().filter((_, k) => k !== i))
  }

  const onInput = (e: Event): void => {
    const raw = (e.target as HTMLInputElement).value
    if (raw.includes(',')) {
      const parts = raw.split(',')
      const last = parts.pop() ?? ''
      let next = current()
      for (const p of parts) {
        const txt = p.trim()
        if (canAdd(txt, next)) next = [...next, txt]
      }
      if (next !== current()) updateTags(next)
      setInputText(last)
    } else {
      setInputText(raw)
    }
  }

  const onKeyDown = (e: KeyboardEvent): void => {
    if (e.key === 'Enter') {
      e.preventDefault()
      addTag()
    } else if (e.key === 'Backspace' && inputText() === '' && current().length > 0) {
      e.preventDefault()
      removeAt(current().length - 1)
    }
  }

  const borderColor = (): string =>
    local.invalid ? 'var(--iris-danger)' : focused() ? 'var(--iris-primary)' : 'var(--iris-border)'

  return (
    <div
      {...rest}
      data-iris-tag-input=""
      data-state={local.invalid ? 'invalid' : focused() ? 'focused' : 'idle'}
      style={{
        display: 'flex',
        'flex-wrap': 'wrap',
        'align-items': 'center',
        gap: 'var(--iris-space-xs, 8px)',
        padding: '4px 8px',
        'min-height': '34px',
        background: 'var(--iris-background)',
        border: `1px solid ${borderColor()}`,
        'border-radius': 'var(--iris-radius-md, 6px)',
        opacity: local.disabled ? 0.6 : 1,
        'box-shadow': focused()
          ? '0 0 0 3px color-mix(in srgb, var(--iris-primary) 18%, transparent)'
          : 'none',
        transition: 'border-color 120ms ease, box-shadow 120ms ease',
        ...((typeof local.style === 'object' ? local.style : {}) as JSX.CSSProperties),
      }}
    >
      <For each={current()}>
        {(tag, i) => (
          <span
            data-iris-tag-input-tag=""
            data-value={tag}
            style={{
              display: 'inline-flex',
              'align-items': 'center',
              gap: '4px',
              padding: 'var(--iris-space-xxs, 4px) var(--iris-padding-sm, 6px)',
              'font-size': 'var(--iris-font-size-sm, 13px)',
              background: 'var(--iris-surface)',
              border: '1px solid var(--iris-border)',
              'border-radius': 'var(--iris-radius-sm, 4px)',
              color: 'var(--iris-foreground)',
            }}
          >
            {tag}
            <button
              type="button"
              data-iris-tag-input-remove=""
              aria-label={t('tagInput.remove', { tag })}
              disabled={local.disabled}
              onClick={() => removeAt(i())}
              style={{
                border: 'none',
                background: 'transparent',
                color: 'var(--iris-muted)',
                cursor: local.disabled ? 'not-allowed' : 'pointer',
                'font-size': 'var(--iris-font-size-md, 14px)',
                'line-height': '1',
                padding: '0',
              }}
            >
              ×
            </button>
          </span>
        )}
      </For>
      <input
        id={local.id}
        type="text"
        data-iris-tag-input-field=""
        value={inputText()}
        placeholder={current().length === 0 ? local.placeholder : undefined}
        disabled={local.disabled}
        aria-invalid={local.invalid ? 'true' : undefined}
        aria-describedby={local.ariaDescribedby}
        onInput={onInput}
        onKeyDown={onKeyDown}
        onFocus={() => setFocused(true)}
        onBlur={() => setFocused(false)}
        style={{
          flex: '1',
          'min-width': '80px',
          border: 'none',
          outline: 'none',
          background: 'transparent',
          color: 'var(--iris-foreground)',
          'font-family': 'inherit',
          'font-size': 'var(--iris-font-size-md, 14px)',
          padding: 'var(--iris-space-xxs, 4px) 0',
        }}
      />
    </div>
  )
}

// packages/svelte/src/primitives/tag-input/IrisTagInput.svelte
<script lang="ts">
  import { styleToString, mergeStyle } from '../../internal/style'
  import { useI18n } from '../../i18n'

  const { t } = useI18n()

  interface Props {
    value?: string[]
    placeholder?: string
    disabled?: boolean
    invalid?: boolean
    max?: number
    allowDuplicates?: boolean
    id?: string
    ariaDescribedby?: string
    style?: string
    onchange?: (tags: string[]) => void
    [key: string]: unknown
  }

  let {
    value = [],
    placeholder,
    disabled = false,
    invalid = false,
    max,
    allowDuplicates = false,
    id,
    ariaDescribedby,
    style,
    onchange,
    ...rest
  }: Props = $props()

  let inputText = $state('')
  let focused = $state(false)

  function canAdd(txt: string, list: string[]) {
    return !!txt && (allowDuplicates || !list.includes(txt)) && (!max || list.length < max)
  }

  function addTag() {
    const txt = inputText.trim()
    if (txt && canAdd(txt, value)) {
      onchange?.([...value, txt])
    }
    inputText = ''
  }

  function removeAt(i: number) {
    if (disabled) return
    onchange?.(value.filter((_, k) => k !== i))
  }

  function handleInput(e: Event) {
    const target = e.target as HTMLInputElement
    const raw = target.value
    if (raw.includes(',')) {
      const parts = raw.split(',')
      const last = parts.pop() ?? ''
      let next = value
      for (const p of parts) {
        const txt = p.trim()
        if (!txt) continue
        if (canAdd(txt, next)) next = [...next, txt]
      }
      if (next !== value) onchange?.(next)
      inputText = last
      target.value = last
    } else {
      inputText = raw
    }
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter') {
      e.preventDefault()
      addTag()
    } else if (e.key === 'Backspace' && inputText === '' && value.length > 0) {
      e.preventDefault()
      removeAt(value.length - 1)
    }
  }

  const wrapperStyle = $derived.by(() => {
    const borderColor = invalid
      ? 'var(--iris-danger)'
      : focused
        ? 'var(--iris-primary)'
        : 'var(--iris-border)'
    return styleToString({
      display: 'flex',
      'flex-wrap': 'wrap',
      'align-items': 'center',
      gap: 'var(--iris-space-xs, 8px)',
      padding: '4px 8px',
      'min-height': '34px',
      background: 'var(--iris-background)',
      border: `1px solid ${borderColor}`,
      'border-radius': 'var(--iris-radius-md, 6px)',
      opacity: disabled ? '0.6' : '1',
      'box-shadow': focused
        ? '0 0 0 3px color-mix(in srgb, var(--iris-primary) 18%, transparent)'
        : 'none',
      transition: 'border-color 120ms ease, box-shadow 120ms ease',
    })
  })

  const tagStyle = styleToString({
    display: 'inline-flex',
    'align-items': 'center',
    gap: '4px',
    padding: 'var(--iris-space-xxs, 4px) var(--iris-padding-sm, 6px)',
    'font-size': 'var(--iris-font-size-sm, 13px)',
    background: 'var(--iris-surface)',
    border: '1px solid var(--iris-border)',
    'border-radius': 'var(--iris-radius-sm, 4px)',
    color: 'var(--iris-foreground)',
  })
</script>

<div
  {...rest}
  data-iris-tag-input
  data-state={invalid ? 'invalid' : focused ? 'focused' : 'idle'}
  style={mergeStyle(wrapperStyle, style)}
>
  {#each value as tag, i (tag + '-' + i)}
    <span data-iris-tag-input-tag data-value={tag} style={tagStyle}>
      {tag}
      <button
        type="button"
        data-iris-tag-input-remove
        aria-label={t('tagInput.remove', { tag })}
        {disabled}
        onclick={() => removeAt(i)}
        style="border: none; background: transparent; color: var(--iris-muted); cursor: {disabled
          ? 'not-allowed'
          : 'pointer'}; font-size: var(--iris-font-size-md, 14px); line-height: 1; padding: 0;"
        >×</button
      >
    </span>
  {/each}
  <input
    {id}
    type="text"
    data-iris-tag-input-field
    value={inputText}
    placeholder={value.length === 0 ? placeholder : undefined}
    {disabled}
    aria-invalid={invalid ? 'true' : undefined}
    aria-describedby={ariaDescribedby}
    oninput={handleInput}
    onkeydown={handleKeyDown}
    onfocus={() => {
      focused = true
    }}
    onblur={() => {
      focused = false
    }}
    style="flex: 1; min-width: 80px; border: none; outline: none; background: transparent; color: var(--iris-foreground); font-family: inherit; font-size: var(--iris-font-size-md, 14px); padding: var(--iris-space-xxs, 4px) 0;"
  />
</div>
