// apps/playground/src/sections/ChartsShowcase.vue
<template>
  <div style="display: flex; flex-direction: column; gap: 24px">
    <section class="section">
      <h2 class="section-title">Charts</h2>
      <p style="color: var(--iris-muted); font-size: 14px; margin: 0 0 16px">
        Token-themed SVG charts from <code>@iris-ui-kit/plugin-charts</code>. Charts inherit the
        active theme via CSS variables — try switching skins.
      </p>

      <div
        style="
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(340px, 1fr));
          gap: 16px;
        "
      >
        <div class="card" style="padding: 16px">
          <div style="font-weight: 600; font-size: 14px; margin-bottom: 8px">Line Chart</div>
          <IrisLineChart :data="lineData" :width="320" :height="150" area />
        </div>

        <div class="card" style="padding: 16px">
          <div style="font-weight: 600; font-size: 14px; margin-bottom: 8px">Bar Chart</div>
          <IrisBarChart :data="barData" :width="320" :height="150" />
        </div>

        <div class="card" style="padding: 16px">
          <div style="font-weight: 600; font-size: 14px; margin-bottom: 8px">Sparkline</div>
          <div style="font-size: 24px; font-weight: 700; font-variant-numeric: tabular-nums">
            {{ lineData[lineData.length - 1]?.toFixed(1) }}
            <span style="font-size: 14px; color: var(--iris-muted); margin-inline-start: 8px">
              {{ lineData[lineData.length - 1]! > lineData[0]! ? '▲' : '▼' }}
            </span>
          </div>
          <IrisSparkline :data="lineData" :width="320" :height="50" />
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { IrisLineChart, IrisBarChart, IrisSparkline } from '@iris-ui-kit/plugin-charts/vue'

function randomData(count: number): number[] {
  let val = 50
  const data: number[] = []
  for (let i = 0; i < count; i++) {
    val += Math.random() * 10 - 5
    data.push(Math.max(0, val))
  }
  return data
}

const lineData = randomData(30)
const barData = [62, 85, 43, 91, 58]
</script>

// apps/playground-react/src/sections/ChartsShowcase.tsx
import { useState } from 'react'
import { IrisLineChart, IrisBarChart, IrisSparkline } from '@iris-ui-kit/plugin-charts/react'
import { IrisButton, IrisCard } from '@iris-ui-kit/react'

function generateRandomData(count: number): number[] {
  let val = 50
  const data: number[] = []
  for (let i = 0; i < count; i++) {
    val += Math.random() * 10 - 5
    data.push(Math.max(0, val))
  }
  return data
}

export function ChartsShowcase() {
  const [data, setData] = useState(() => generateRandomData(30))
  const [barData, setBarData] = useState(() => [
    Math.round(Math.random() * 100),
    Math.round(Math.random() * 100),
    Math.round(Math.random() * 100),
    Math.round(Math.random() * 100),
    Math.round(Math.random() * 100),
  ])

  const refresh = () => {
    setData(generateRandomData(30))
    setBarData([
      Math.round(Math.random() * 100),
      Math.round(Math.random() * 100),
      Math.round(Math.random() * 100),
      Math.round(Math.random() * 100),
      Math.round(Math.random() * 100),
    ])
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
      <section className="section">
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}>
          <h2 className="section-title" style={{ margin: 0 }}>
            Charts
          </h2>
          <IrisButton size="sm" variant="outline" onClick={refresh}>
            Regenerate Data
          </IrisButton>
        </div>
        <p style={{ color: 'var(--iris-muted)', fontSize: 14, margin: '0 0 16px' }}>
          Zero-dependency, token-themed SVG charts from <code>@iris-ui-kit/plugin-charts</code>.
          Charts inherit the active theme via CSS variables — try switching skins above.
        </p>

        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))',
            gap: 16,
          }}
        >
          <IrisCard style={{ padding: 16 }}>
            <div style={{ fontWeight: 600, fontSize: 14, marginBottom: 8 }}>Line Chart</div>
            <IrisLineChart data={data} width={320} height={150} area />
          </IrisCard>

          <IrisCard style={{ padding: 16 }}>
            <div style={{ fontWeight: 600, fontSize: 14, marginBottom: 8 }}>Bar Chart</div>
            <IrisBarChart data={barData} width={320} height={150} />
          </IrisCard>

          <IrisCard style={{ padding: 16 }}>
            <div style={{ fontWeight: 600, fontSize: 14, marginBottom: 8 }}>Sparkline</div>
            <div style={{ fontSize: 24, fontWeight: 700, fontVariantNumeric: 'tabular-nums' }}>
              {data[data.length - 1]?.toFixed(1)}
              <span style={{ fontSize: 14, color: 'var(--iris-muted)', marginInlineStart: 8 }}>
                {data[data.length - 1]! > data[0]! ? '▲' : '▼'}
              </span>
            </div>
            <IrisSparkline data={data} width={320} height={50} />
          </IrisCard>

          <IrisCard style={{ padding: 16 }}>
            <div style={{ fontWeight: 600, fontSize: 14, marginBottom: 8 }}>Line (no fill)</div>
            <IrisLineChart data={data.slice(-15)} width={320} height={120} />
          </IrisCard>
        </div>
      </section>
    </div>
  )
}
