// packages/react/src/primitives/badge/Badge.tsx
import * as React from 'react'

export type IrisBadgeVariant = 'solid' | 'outline' | 'subtle'
export type IrisBadgeTone = 'primary' | 'success' | 'warning' | 'danger' | 'neutral'
export type IrisBadgeSize = 'sm' | 'md'

const TONE_TO_VAR: Record<IrisBadgeTone, string> = {
  primary: '--iris-primary',
  success: '--iris-success',
  warning: '--iris-warning',
  danger: '--iris-danger',
  neutral: '--iris-muted',
}

function badgeStyle(
  variant: IrisBadgeVariant,
  tone: IrisBadgeTone,
  size: IrisBadgeSize,
): React.CSSProperties {
  const v = `var(${TONE_TO_VAR[tone]})`
  const base: React.CSSProperties = {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    borderRadius: 'var(--iris-radius-sm, 4px)',
    fontFamily: 'var(--iris-font-family, inherit)',
    fontWeight: 500,
    lineHeight: 1,
    whiteSpace: 'nowrap',
    fontSize: size === 'sm' ? '11px' : '12px',
    padding: size === 'sm' ? '2px 6px' : '3px 8px',
  }
  switch (variant) {
    case 'solid':
      return {
        ...base,
        background: v,
        color: 'var(--iris-primary-foreground, #fff)',
        border: '1px solid transparent',
      }
    case 'outline':
      return { ...base, background: 'transparent', color: v, border: `1px solid ${v}` }
    case 'subtle':
      return {
        ...base,
        // Precomputed fallback first; color-mix shorthand overrides on modern engines.
        backgroundColor: `var(${TONE_TO_VAR[tone]}-subtle)`,
        background: `color-mix(in srgb, ${v} 12%, transparent)`,
        color: v,
        border: '1px solid transparent',
      }
  }
}

export interface IrisBadgeProps extends Omit<React.HTMLAttributes<HTMLSpanElement>, 'children'> {
  variant?: IrisBadgeVariant
  tone?: IrisBadgeTone
  size?: IrisBadgeSize
  children?: React.ReactNode
}

/**
 * React port of {@link import('@iris-ui/vue').IrisBadge}. Same visual model.
 *
 * @example
 *   <IrisBadge tone="success" variant="subtle">Active</IrisBadge>
 */
export function IrisBadge({
  variant = 'subtle',
  tone = 'primary',
  size = 'md',
  style,
  children,
  ...rest
}: IrisBadgeProps): React.ReactElement {
  return (
    <span
      {...rest}
      data-iris-badge=""
      data-iris-badge-variant={variant}
      data-iris-badge-tone={tone}
      data-iris-badge-size={size}
      style={{ ...badgeStyle(variant, tone, size), ...style }}
    >
      {children}
    </span>
  )
}

// packages/solid/src/primitives/badge/Badge.tsx
import { mergeProps, splitProps, type JSX } from 'solid-js'

export type IrisBadgeVariant = 'solid' | 'outline' | 'subtle'
export type IrisBadgeTone = 'primary' | 'success' | 'warning' | 'danger' | 'neutral'
export type IrisBadgeSize = 'sm' | 'md'

const TONE_TO_VAR: Record<IrisBadgeTone, string> = {
  primary: '--iris-primary',
  success: '--iris-success',
  warning: '--iris-warning',
  danger: '--iris-danger',
  neutral: '--iris-muted',
}

function badgeStyle(
  variant: IrisBadgeVariant,
  tone: IrisBadgeTone,
  size: IrisBadgeSize,
): JSX.CSSProperties {
  const v = `var(${TONE_TO_VAR[tone]})`
  const base: JSX.CSSProperties = {
    display: 'inline-flex',
    'align-items': 'center',
    gap: '4px',
    'border-radius': 'var(--iris-radius-sm, 4px)',
    'font-family': 'var(--iris-font-family, inherit)',
    'font-weight': 500,
    'line-height': 1,
    'white-space': 'nowrap',
    'font-size': size === 'sm' ? '11px' : '12px',
    padding: size === 'sm' ? '2px 6px' : '3px 8px',
  }
  if (variant === 'solid')
    return {
      ...base,
      background: v,
      color: 'var(--iris-primary-foreground, #fff)',
      border: '1px solid transparent',
    }
  if (variant === 'outline')
    return { ...base, background: 'transparent', color: v, border: `1px solid ${v}` }
  return {
    ...base,
    background: `color-mix(in srgb, ${v} 12%, transparent)`,
    color: v,
    border: '1px solid transparent',
  }
}

export interface IrisBadgeProps extends Omit<JSX.HTMLAttributes<HTMLSpanElement>, 'children'> {
  variant?: IrisBadgeVariant
  tone?: IrisBadgeTone
  size?: IrisBadgeSize
  children?: JSX.Element
}

/** Solid port of the React/Vue IrisBadge. Same visual model. */
export function IrisBadge(props: IrisBadgeProps): JSX.Element {
  const merged = mergeProps(
    {
      variant: 'subtle' as IrisBadgeVariant,
      tone: 'primary' as IrisBadgeTone,
      size: 'md' as IrisBadgeSize,
    },
    props,
  )
  const [local, others] = splitProps(merged, ['variant', 'tone', 'size', 'style', 'children'])
  return (
    <span
      {...others}
      data-iris-badge=""
      data-iris-badge-variant={local.variant}
      data-iris-badge-tone={local.tone}
      data-iris-badge-size={local.size}
      style={{
        ...badgeStyle(local.variant, local.tone, local.size),
        ...((local.style as JSX.CSSProperties) ?? {}),
      }}
    >
      {local.children}
    </span>
  )
}
