// packages/react/src/primitives/menu/context.ts
import * as React from 'react'
import type { Placement } from '@iris-ui-kit/core'

export interface MenuContextValue {
  open: boolean
  setOpen: (next: boolean) => void
  triggerRef: React.MutableRefObject<HTMLElement | null>
  contentRef: React.MutableRefObject<HTMLElement | null>
  contentId: string
  /** Root menu's unique id — shared by every nested submenu surface. */
  treeId: string
  placement: Placement
  offset: number
  /** Close the *root* menu — propagates to nested submenus. */
  closeRoot: () => void
}

export const MenuContext = React.createContext<MenuContextValue | null>(null)

export function useMenuContext(componentName: string): MenuContextValue {
  const ctx = React.useContext(MenuContext)
  if (!ctx) {
    throw new Error(`[iris-ui] ${componentName} must be a descendant of <IrisMenu>`)
  }
  return ctx
}

// packages/solid/src/primitives/menu/context.ts
import { createContext, useContext, type Accessor } from 'solid-js'
import type { Placement } from '@iris-ui-kit/core'

export interface MenuContext {
  open: Accessor<boolean>
  setOpen: (value: boolean) => void
  trigger: Accessor<HTMLElement | undefined>
  setTrigger: (el: HTMLElement) => void
  content: Accessor<HTMLElement | undefined>
  setContent: (el: HTMLElement) => void
  contentId: string
  /** Root menu's unique id — shared by every nested submenu surface. */
  treeId: string
  readonly placement: Placement
  readonly offset: number
  closeRoot: () => void
}

export const MenuContext = createContext<MenuContext | null>(null)

export function useMenuContext(componentName: string): MenuContext {
  const ctx = useContext(MenuContext)
  if (!ctx) {
    throw new Error(`[iris-ui] ${componentName} must be used inside <IrisMenu>`)
  }
  return ctx
}
