// packages/react/src/grid/useGridSorting.ts
import * as React from 'react'
import {
  createTableMultiSortComparator,
  createTableSortComparator,
  resolveTableColumnValue,
  sortTableRows,
} from '@iris-ui-kit/core'
import {
  createGridSortingFeature,
  type GridCore,
  type GridSortingModel,
  type SortState,
} from '@iris-ui-kit/core/grid'
import { useStore } from '../useStore'
import { useGridFeature } from './useGridFeature'

export interface GridSortColumn<Row> {
  key: string
  dataIndex?: keyof Row | string
  formula?: string
  sortable?: boolean
  sorter?: (a: Row, b: Row) => number
  sortBy?: string
  sortType?: 'number' | 'string' | 'auto'
}

export interface UseGridSortingOptions<Row> {
  leafColumns: GridSortColumn<Row>[]
  sort?: SortState | null
  defaultSort?: SortState | null
  onSortChange?: (next: SortState | null) => void
  multiSort?: boolean
  multiSortState?: SortState[]
  defaultMultiSort?: SortState[]
  onMultiSortChange?: (next: SortState[]) => void
  formulaTables?: Record<string, Row[]>
}

export interface UseGridSortingResult<Row> {
  core: GridCore
  model: GridSortingModel
  sortState: SortState | null
  cycleSort: (column: GridSortColumn<Row>) => void
  setSort: (next: SortState | null) => void
  sortComparator: ((a: Row, b: Row) => number) | null
  sortedData: Row[]
  multiSortState: SortState[]
  cycleMultiSort: (column: GridSortColumn<Row>) => void
  setMultiSort: (next: SortState[]) => void
  multiSortComparator: ((a: Row, b: Row) => number) | null
}

function cloneSort(sort: SortState | null): SortState | null {
  return sort ? { ...sort } : null
}

function cloneSorts(sorts: readonly SortState[]): SortState[] {
  return sorts.map((sort) => ({ ...sort }))
}

/** Installs sorting state in Grid Core and derives React column comparators. */
export function useGridSorting<Row extends Record<string, unknown> = Record<string, unknown>>(
  core: GridCore<Row>,
  data: Row[],
  options: UseGridSortingOptions<Row>,
): UseGridSortingResult<Row> {
  const latest = React.useRef(options)
  latest.current = options

  const model = useGridFeature<Row, GridSortingModel>(core, 'sorting', 'getSortingModel', () =>
    createGridSortingFeature<Row>({
      mode: options.multiSort ? 'multiple' : 'single',
      defaultSort: options.sort !== undefined ? options.sort : options.defaultSort,
      defaultMultiSort:
        options.multiSortState !== undefined ? options.multiSortState : options.defaultMultiSort,
      onSortChange: (next) => latest.current.onSortChange?.(next),
      onMultiSortChange: (next) => latest.current.onMultiSortChange?.(next),
    }),
  )
  const internalState = useStore(model.store)
  const sortControlled = options.sort !== undefined
  const multiControlled = options.multiSortState !== undefined
  // React dependency checks cannot observe mutations made through a stable prop
  // reference. Recompute these signatures on every render so controlled sync
  // remains content-sensitive without changing the Core model contract.
  const sortSignature = JSON.stringify(options.sort)
  const multiSortSignature = JSON.stringify(options.multiSortState)
  const wasSortControlled = React.useRef(sortControlled)
  const uncontrolledSort = React.useRef<SortState | null>(null)
  const hasUncontrolledSort = React.useRef(!sortControlled)
  const lastControlledSort = React.useRef<SortState | null>(cloneSort(options.sort ?? null))
  const wasMultiSortControlled = React.useRef(multiControlled)
  const uncontrolledMultiSort = React.useRef<SortState[]>([])
  const hasUncontrolledMultiSort = React.useRef(!multiControlled)
  const lastControlledMultiSort = React.useRef<SortState[]>(
    cloneSorts(options.multiSortState ?? []),
  )
  const leavingSortControlled = wasSortControlled.current && !sortControlled
  const leavingMultiSortControlled = wasMultiSortControlled.current && !multiControlled
  const enteringSortControlled = sortControlled && !wasSortControlled.current
  const enteringMultiSortControlled = multiControlled && !wasMultiSortControlled.current

  // Capture only genuine uncontrolled state. A rejected controlled proposal may
  // be ahead of the prop in the model, so it must not become the handoff value.
  if (enteringSortControlled || enteringMultiSortControlled) {
    // Read once before either controlled effect can synchronize its channel.
    const liveState = model.store.getState()
    if (enteringSortControlled) {
      uncontrolledSort.current = cloneSort(liveState.sort)
      hasUncontrolledSort.current = true
    }
    if (enteringMultiSortControlled) {
      uncontrolledMultiSort.current = cloneSorts(liveState.multiSort)
      hasUncontrolledMultiSort.current = true
    }
  }
  if (!sortControlled && !leavingSortControlled) {
    uncontrolledSort.current = cloneSort(internalState.sort)
    hasUncontrolledSort.current = true
  }
  if (!multiControlled && !leavingMultiSortControlled) {
    uncontrolledMultiSort.current = cloneSorts(internalState.multiSort)
    hasUncontrolledMultiSort.current = true
  }
  if (sortControlled) lastControlledSort.current = cloneSort(options.sort ?? null)
  if (multiControlled) {
    lastControlledMultiSort.current = cloneSorts(options.multiSortState ?? [])
  }

  const sortState = sortControlled
    ? cloneSort(options.sort ?? null)
    : cloneSort(
        leavingSortControlled
          ? hasUncontrolledSort.current
            ? uncontrolledSort.current
            : lastControlledSort.current
          : internalState.sort,
      )
  const multiSortState = multiControlled
    ? cloneSorts(options.multiSortState ?? [])
    : cloneSorts(
        leavingMultiSortControlled
          ? hasUncontrolledMultiSort.current
            ? uncontrolledMultiSort.current
            : lastControlledMultiSort.current
          : internalState.multiSort,
      )

  React.useEffect(() => {
    if (sortControlled) {
      const next = options.sort ?? null
      lastControlledSort.current = cloneSort(next)
      model.syncSort(next)
    } else if (wasSortControlled.current) {
      const restore = hasUncontrolledSort.current
        ? uncontrolledSort.current
        : lastControlledSort.current
      if (!hasUncontrolledSort.current) {
        uncontrolledSort.current = cloneSort(restore)
        hasUncontrolledSort.current = true
      }
      model.syncSort(restore)
    }
    wasSortControlled.current = sortControlled
  }, [model, options.sort, sortControlled, sortSignature])

  React.useEffect(() => {
    if (multiControlled) {
      const next = cloneSorts(options.multiSortState ?? [])
      lastControlledMultiSort.current = cloneSorts(next)
      model.syncMultiSort(next)
    } else if (wasMultiSortControlled.current) {
      const restore = hasUncontrolledMultiSort.current
        ? uncontrolledMultiSort.current
        : lastControlledMultiSort.current
      // Preserve the handoff value as the next uncontrolled baseline even if
      // Core was already equal and therefore emitted no store notification.
      uncontrolledMultiSort.current = cloneSorts(restore)
      hasUncontrolledMultiSort.current = true
      model.syncMultiSort(restore)
    }
    wasMultiSortControlled.current = multiControlled
  }, [model, multiControlled, options.multiSortState, multiSortSignature])

  const setSort = React.useCallback(
    (next: SortState | null) => {
      if (latest.current.sort !== undefined) model.syncSort(latest.current.sort ?? null)
      model.setSort(next)
    },
    [model],
  )
  const cycleSort = React.useCallback(
    (column: GridSortColumn<Row>) => {
      if (!column.sortable) return
      if (latest.current.sort !== undefined) model.syncSort(latest.current.sort ?? null)
      model.cycleSort(column.key)
    },
    [model],
  )
  const setMultiSort = React.useCallback(
    (next: SortState[]) => {
      if (latest.current.multiSortState !== undefined) {
        model.syncMultiSort(latest.current.multiSortState)
      }
      model.setMultiSort(next)
    },
    [model],
  )
  const cycleMultiSort = React.useCallback(
    (column: GridSortColumn<Row>) => {
      if (!column.sortable) return
      if (latest.current.multiSortState !== undefined) {
        model.syncMultiSort(latest.current.multiSortState)
      }
      model.cycleMultiSort(column.key)
    },
    [model],
  )

  const getValue = React.useCallback(
    (row: Row, column: GridSortColumn<Row>): unknown => {
      if (column.sortBy !== undefined) return row[column.sortBy as keyof Row]
      return resolveTableColumnValue(row, column, options.formulaTables)
    },
    [options.formulaTables],
  )

  const sortComparator = React.useMemo(
    () => createTableSortComparator(sortState, options.leafColumns, getValue),
    [getValue, options.leafColumns, sortState],
  )

  const multiSortComparator = React.useMemo(
    () => createTableMultiSortComparator(multiSortState, options.leafColumns, getValue),
    [getValue, options.leafColumns, multiSortState],
  )

  const sortedData = React.useMemo(
    () =>
      sortTableRows(data, options.leafColumns, {
        mode: options.multiSort ? 'multiple' : 'single',
        sort: sortState,
        multiSort: multiSortState,
        getValue,
      }),
    [data, getValue, multiSortState, options.leafColumns, options.multiSort, sortState],
  )

  return {
    core,
    model,
    sortState,
    cycleSort,
    setSort,
    sortComparator,
    sortedData,
    multiSortState,
    cycleMultiSort,
    setMultiSort,
    multiSortComparator,
  }
}

// packages/solid/src/grid/useGridSorting.ts
import { createEffect, type Accessor } from 'solid-js'
import {
  createGridSortingFeature,
  type GridCore,
  type GridSortingModel,
  type SortState,
} from '@iris-ui-kit/core/grid'
import { useStore } from '../useStore'
import { useGridFeature } from './useGridFeature'

export interface UseGridSortingOptions {
  mode?: 'single' | 'multiple'
  sort?: SortState | null
  defaultSort?: SortState | null
  onSortChange?: (sort: SortState | null) => void
  multiSortState?: SortState[]
  defaultMultiSort?: SortState[]
  onMultiSortChange?: (sorts: SortState[]) => void
}

function cloneSort(sort: SortState | null): SortState | null {
  return sort ? { ...sort } : null
}

function cloneSorts(sorts: readonly SortState[]): SortState[] {
  return sorts.map((sort) => ({ ...sort }))
}

export function useGridSorting<Row extends Record<string, unknown> = Record<string, unknown>>(
  core: GridCore<Row>,
  options: UseGridSortingOptions = {},
): {
  model: GridSortingModel
  sort: Accessor<SortState | null>
  multiSort: Accessor<SortState[]>
  cycleSort(key: string): void
  setSort(sort: SortState | null): void
  cycleMultiSort(key: string): void
  setMultiSort(sorts: SortState[]): void
} {
  const latest = options
  const model = useGridFeature<Row, GridSortingModel>(core, 'sorting', 'getSortingModel', () =>
    createGridSortingFeature<Row>({
      mode: options.mode,
      defaultSort: options.sort !== undefined ? options.sort : options.defaultSort,
      defaultMultiSort:
        options.multiSortState !== undefined ? options.multiSortState : options.defaultMultiSort,
      onSortChange: (v) => latest.onSortChange?.(v),
      onMultiSortChange: (v) => latest.onMultiSortChange?.(v),
    }),
  )
  const state = useStore(model.store)
  let wasSortControlled = options.sort !== undefined
  let hasUncontrolledSort = !wasSortControlled
  let uncontrolledSort = cloneSort(state().sort)
  let lastControlledSort = cloneSort(options.sort ?? null)
  let wasMultiSortControlled = options.multiSortState !== undefined
  let hasUncontrolledMultiSort = !wasMultiSortControlled
  let uncontrolledMultiSort = cloneSorts(state().multiSort)
  let lastControlledMultiSort = cloneSorts(options.multiSortState ?? [])

  createEffect(() => {
    const sort = options.sort
    const multiSortState = options.multiSortState
    const sortControlled = sort !== undefined
    const multiSortControlled = multiSortState !== undefined
    // Read nested fields so reactive prop proxies also observe in-place changes.
    void JSON.stringify(sort)
    void JSON.stringify(multiSortState)

    // Capture both sorting channels from the live Core state before either
    // controlled sync runs; the Solid store mirror may still be pre-batch.
    if (
      (sortControlled && !wasSortControlled) ||
      (multiSortControlled && !wasMultiSortControlled)
    ) {
      const current = model.store.getState()
      if (sortControlled && !wasSortControlled) {
        uncontrolledSort = cloneSort(current.sort)
        hasUncontrolledSort = true
      }
      if (multiSortControlled && !wasMultiSortControlled) {
        uncontrolledMultiSort = cloneSorts(current.multiSort)
        hasUncontrolledMultiSort = true
      }
    }

    if (sortControlled) {
      lastControlledSort = cloneSort(sort ?? null)
      model.syncSort(sort)
    } else if (wasSortControlled) {
      const restore = hasUncontrolledSort ? uncontrolledSort : lastControlledSort
      if (!hasUncontrolledSort) {
        uncontrolledSort = cloneSort(restore)
        hasUncontrolledSort = true
      }
      model.syncSort(restore)
    }
    if (multiSortControlled) {
      lastControlledMultiSort = cloneSorts(multiSortState)
      model.syncMultiSort(multiSortState)
    } else if (wasMultiSortControlled) {
      const restore = hasUncontrolledMultiSort ? uncontrolledMultiSort : lastControlledMultiSort
      // A no-op Core sync still establishes the restored value as the next
      // uncontrolled baseline for a later controlled detour.
      uncontrolledMultiSort = cloneSorts(restore)
      hasUncontrolledMultiSort = true
      model.syncMultiSort(restore)
    }
    wasSortControlled = sortControlled
    wasMultiSortControlled = multiSortControlled
  })
  createEffect(() => {
    const current = state()
    if (!wasSortControlled) {
      uncontrolledSort = cloneSort(current.sort)
      hasUncontrolledSort = true
    }
    if (!wasMultiSortControlled) {
      uncontrolledMultiSort = cloneSorts(current.multiSort)
      hasUncontrolledMultiSort = true
    }
  })
  return {
    model,
    sort: () => {
      // Read the store unconditionally so every consumer computation keeps its
      // subscription across a controlled -> uncontrolled handoff; the value is
      // only used in the uncontrolled branch.
      const current = state()
      const sort = options.sort
      if (sort !== undefined) return cloneSort(sort)
      return cloneSort(
        wasSortControlled
          ? hasUncontrolledSort
            ? uncontrolledSort
            : lastControlledSort
          : current.sort,
      )
    },
    multiSort: () => {
      const current = state()
      const multiSortState = options.multiSortState
      if (multiSortState !== undefined) return cloneSorts(multiSortState)
      return cloneSorts(
        wasMultiSortControlled
          ? hasUncontrolledMultiSort
            ? uncontrolledMultiSort
            : lastControlledMultiSort
          : current.multiSort,
      )
    },
    cycleSort: (key) => {
      const sort = options.sort
      if (sort !== undefined) model.syncSort(sort)
      model.cycleSort(key)
    },
    setSort: (v) => model.setSort(v),
    cycleMultiSort: (key) => {
      const multiSortState = options.multiSortState
      if (multiSortState !== undefined) model.syncMultiSort(multiSortState)
      model.cycleMultiSort(key)
    },
    setMultiSort: (v) => model.setMultiSort(v),
  }
}
