// packages/svelte/src/primitives/select/SelectOptions.svelte
<script lang="ts">
  import type { VirtualizerState } from '@iris-ui-kit/core'

  export interface IrisSelectItem {
    label?: string
    value: unknown
    disabled?: boolean
  }

  interface Props {
    items: IrisSelectItem[]
    currentValue: unknown
    multiple: boolean
    selectedValues: string[]
    virtual: boolean
    virtualizerReady: boolean
    vstate: VirtualizerState
    rowHeight: number
    fontSize: string
    emptyLabel: string
    selectItem: (item: IrisSelectItem) => void
  }

  let {
    items,
    currentValue,
    multiple,
    selectedValues,
    virtual,
    virtualizerReady,
    vstate,
    rowHeight,
    fontSize,
    emptyLabel,
    selectItem,
  }: Props = $props()
</script>

{#if items.length === 0}
  <li
    data-iris-select-empty=""
    style="padding: var(--iris-space-xs, 8px) var(--iris-padding-sm, 6px); color: var(--iris-muted); font-size: var(--iris-font-size-sm, 13px); text-align: center; list-style: none"
  >
    {emptyLabel}
  </li>
{:else if virtual && virtualizerReady}
  <li
    role="presentation"
    aria-hidden="true"
    data-iris-select-spacer
    data-iris-select-spacer-type="top"
    style="height: {vstate.offsetBefore}px"
  ></li>
  {#each vstate.items as windowItem (windowItem.key)}
    {@const item = items[windowItem.index]}
    {#if item}
      <li
        role="option"
        aria-selected={multiple
          ? selectedValues.includes(item.value as string)
          : item.value === currentValue
            ? 'true'
            : 'false'}
        aria-disabled={item.disabled ? 'true' : undefined}
        aria-setsize={items.length}
        aria-posinset={windowItem.index + 1}
        data-iris-select-option
        data-iris-select-option-index={windowItem.index}
        onclick={() => selectItem(item)}
        onkeydown={(event) => {
          if (event.key === 'Enter' || event.key === ' ') {
            event.preventDefault()
            selectItem(item)
          }
        }}
        tabindex={item.disabled ? -1 : 0}
        style="display: flex; align-items: center; gap: var(--iris-gap-sm, 6px); padding: var(--iris-space-xs, 8px) var(--iris-space-sm, 12px); font-size: {fontSize}; border-radius: var(--iris-radius-sm, 4px); cursor: {item.disabled
          ? 'not-allowed'
          : 'pointer'}; color: {item.disabled
          ? 'var(--iris-muted)'
          : 'var(--iris-foreground)'}; background: {item.value === currentValue
          ? 'var(--iris-surface-selected, rgba(99, 102, 241, 0.12))'
          : 'transparent'}; font-weight: {item.value === currentValue ? '600' : '400'}"
      >
        <span style="flex: 1; min-width: 0">{item.label ?? String(item.value)}</span>
        {#if item.value === currentValue}
          <svg
            aria-hidden="true"
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="var(--iris-primary)"
            stroke-width="2.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path d="M20 6 9 17l-5-5" />
          </svg>
        {/if}
      </li>
    {/if}
  {/each}
  <li
    role="presentation"
    aria-hidden="true"
    data-iris-select-spacer
    data-iris-select-spacer-type="bottom"
    style="height: {vstate.totalSize - vstate.offsetBefore - vstate.items.length * rowHeight}px"
  ></li>
{:else}
  {#each items as item}
    <li
      role="option"
      aria-selected={item.value === currentValue ? 'true' : 'false'}
      aria-disabled={item.disabled ? 'true' : undefined}
      data-iris-select-option
      onclick={() => selectItem(item)}
      onkeydown={(event) => {
        if (event.key === 'Enter' || event.key === ' ') {
          event.preventDefault()
          selectItem(item)
        }
      }}
      tabindex={item.disabled ? -1 : 0}
      style="display: flex; align-items: center; gap: var(--iris-gap-sm, 6px); padding: var(--iris-space-xs, 8px) var(--iris-space-sm, 12px); font-size: {fontSize}; border-radius: var(--iris-radius-sm, 4px); cursor: {item.disabled
        ? 'not-allowed'
        : 'pointer'}; color: {item.disabled
        ? 'var(--iris-muted)'
        : 'var(--iris-foreground)'}; background: {item.value === currentValue
        ? 'var(--iris-surface-selected, rgba(99, 102, 241, 0.12))'
        : 'transparent'}; font-weight: {item.value === currentValue ? '600' : '400'}"
    >
      <span style="flex: 1; min-width: 0">{item.label ?? String(item.value)}</span>
      {#if item.value === currentValue}
        <svg
          aria-hidden="true"
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="var(--iris-primary)"
          stroke-width="2.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <path d="M20 6 9 17l-5-5" />
        </svg>
      {/if}
    </li>
  {/each}
{/if}

// packages/solid/src/primitives/select/SelectOptions.tsx
import { For, Show, type Accessor, type JSX } from 'solid-js'
import type { VirtualizerState } from '@iris-ui-kit/core'
import { SelectOption } from './SelectOption'
import type { IrisSelectItem } from './IrisSelect'

export interface SelectWindowItem<T> {
  opt: IrisSelectItem<T>
  index: number
  key: string | number
}

export interface SelectOptionsProps<T> {
  items: Accessor<IrisSelectItem<T>[]>
  multiple: boolean
  currentValue: Accessor<T | undefined>
  selectedValues: Accessor<T[]>
  activeIndex: Accessor<number>
  fontSize: Accessor<string>
  virtual: Accessor<boolean>
  virtualState: Accessor<VirtualizerState>
  windowed: Accessor<SelectWindowItem<T>[]>
  rowHeight: number
  emptyLabel: string
  onFocus(index: number): void
  onSelect(item: IrisSelectItem<T>): void
}

/** Shared option window for the virtual and full Solid select paths. */
export function SelectOptions<T>(props: SelectOptionsProps<T>): JSX.Element {
  return (
    <>
      <Show when={props.items().length === 0}>
        <div
          data-iris-select-empty=""
          style={{
            padding: 'var(--iris-space-xs, 8px) var(--iris-padding-sm, 6px)',
            color: 'var(--iris-muted)',
            'font-size': 'var(--iris-font-size-sm, 13px)',
            'text-align': 'center',
          }}
        >
          {props.emptyLabel}
        </div>
      </Show>
      <Show
        when={props.virtual() && props.items().length > 0}
        fallback={
          <For each={props.items()}>
            {(item, index) => (
              <SelectOption
                item={item}
                index={index()}
                active={() => index() === props.activeIndex()}
                selected={() =>
                  props.multiple
                    ? props.selectedValues().includes(item.value)
                    : item.value === props.currentValue()
                }
                fontSize={props.fontSize}
                onFocus={() => props.onFocus(index())}
                onSelect={() => props.onSelect(item)}
              />
            )}
          </For>
        }
      >
        <div
          role="presentation"
          aria-hidden="true"
          data-iris-select-spacer=""
          data-iris-select-spacer-type="top"
          style={{ height: `${props.virtualState().offsetBefore}px` }}
        />
        <For each={props.windowed()}>
          {(item) => (
            <SelectOption
              item={item.opt}
              index={item.index}
              active={() => item.index === props.activeIndex()}
              selected={() => item.opt.value === props.currentValue()}
              fontSize={props.fontSize}
              itemCount={() => props.items().length}
              onFocus={() => props.onFocus(item.index)}
              onSelect={() => props.onSelect(item.opt)}
            />
          )}
        </For>
        <div
          role="presentation"
          aria-hidden="true"
          data-iris-select-spacer=""
          data-iris-select-spacer-type="bottom"
          style={{
            height: `${
              props.virtualState().totalSize -
              props.virtualState().offsetBefore -
              props.virtualState().items.length * props.rowHeight
            }px`,
          }}
        />
      </Show>
    </>
  )
}
