// apps/cms-react/src/App.tsx
import { SkinProvider, IrisProvider } from '@iris-ui/react'
import { notificationsPlugin } from '@iris-ui/plugin-notifications/react'
import { skinEngine } from './skin'
import { AuthProvider, useAuth } from './auth'
import { Shell } from './Shell'
import { LoginPage } from './pages/LoginPage'

/** Auth gate: unauthenticated → Login screen; authenticated → the CMS shell. */
function Gate() {
  const { session } = useAuth()
  return session ? <Shell /> : <LoginPage />
}

export function App() {
  return (
    <SkinProvider engine={skinEngine}>
      <IrisProvider plugins={[notificationsPlugin]}>
        <AuthProvider>
          <Gate />
        </AuthProvider>
      </IrisProvider>
    </SkinProvider>
  )
}

// apps/cms/src/App.vue
<script setup lang="ts">
import { SkinProvider, IrisProvider } from '@iris-ui/vue'
import { notificationsPlugin } from '@iris-ui/plugin-notifications/vue'
import { skinEngine } from './skin'
import Shell from './Shell.vue'
import LoginPage from './pages/LoginPage.vue'
import { authStore } from './auth'
</script>

<template>
  <SkinProvider :engine="skinEngine">
    <IrisProvider :plugins="[notificationsPlugin]">
      <LoginPage v-if="!authStore.getState().session" />
      <Shell v-else />
    </IrisProvider>
  </SkinProvider>
</template>
