// packages/react/src/primitives/breadcrumb/Breadcrumb.tsx
import * as React from 'react'
import { useI18n } from '../../i18n'

export interface IrisBreadcrumbProps extends React.HTMLAttributes<HTMLElement> {
  /** String separator between crumbs. Default `/`. */
  separator?: React.ReactNode
  children?: React.ReactNode
}

/**
 * Container for breadcrumb navigation. Renders a `<nav>` with an `<ol>` per
 * WAI-ARIA. Inserts `separator` between items and tags the last child with
 * `isCurrent` so it renders as plain text + `aria-current="page"`.
 */
export const IrisBreadcrumb = React.forwardRef<HTMLElement, IrisBreadcrumbProps>(
  function IrisBreadcrumb({ separator = '/', children, ...rest }, ref) {
    const { t } = useI18n()
    const flat = React.Children.toArray(children).filter((c) =>
      React.isValidElement(c),
    ) as React.ReactElement[]
    const total = flat.length

    return (
      <nav
        {...rest}
        ref={ref as React.Ref<HTMLElement>}
        aria-label={t('breadcrumb.label')}
        data-iris-breadcrumb=""
      >
        <ol
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 'var(--iris-space-xs, 8px)',
            margin: 0,
            padding: 0,
            listStyle: 'none',
            fontSize: 'var(--iris-font-size-md, 14px)',
          }}
        >
          {flat.map((child, i) => {
            const isLast = i === total - 1
            const itemNode = (
              <li
                key={`item-${i}`}
                data-iris-breadcrumb-item=""
                data-iris-breadcrumb-last={isLast ? 'true' : undefined}
                style={{ display: 'inline-flex', alignItems: 'center' }}
              >
                {React.cloneElement(child, {
                  isCurrent: isLast,
                } as Partial<unknown> as React.Attributes)}
              </li>
            )
            const sepNode = !isLast ? (
              <li
                key={`sep-${i}`}
                data-iris-breadcrumb-separator=""
                aria-hidden="true"
                style={{ color: 'var(--iris-muted)', display: 'inline-flex', alignItems: 'center' }}
              >
                {separator}
              </li>
            ) : null
            return (
              <React.Fragment key={`pair-${i}`}>
                {itemNode}
                {sepNode}
              </React.Fragment>
            )
          })}
        </ol>
      </nav>
    )
  },
)

// packages/solid/src/primitives/breadcrumb/Breadcrumb.tsx
import { children, For, mergeProps, Show, type JSX } from 'solid-js'
import { useI18n } from '../../i18n'

export interface IrisBreadcrumbProps {
  /** Separator between crumbs. Default `/`. */
  separator?: JSX.Element
  class?: string
  style?: JSX.CSSProperties
  children?: JSX.Element
}

/**
 * Container for breadcrumb navigation — `<nav><ol>` per WAI-ARIA, with a
 * separator inserted between items. Children should be `IrisBreadcrumbItem`s;
 * the last one should set `current` (the data-driven `IrisAdminBreadcrumb` does
 * this for you). Solid has no `cloneElement`, so unlike React/Vue the last
 * crumb is not auto-marked — set `current` explicitly.
 */
export function IrisBreadcrumb(props: IrisBreadcrumbProps): JSX.Element {
  const merged = mergeProps({ separator: '/' as JSX.Element }, props)
  const resolved = children(() => props.children)
  const items = (): unknown[] => resolved.toArray()
  const { t } = useI18n()

  return (
    <nav
      aria-label={t('breadcrumb.label')}
      data-iris-breadcrumb=""
      class={merged.class}
      style={merged.style}
    >
      <ol
        style={{
          display: 'inline-flex',
          'align-items': 'center',
          gap: 'var(--iris-space-xs, 8px)',
          margin: 0,
          padding: 0,
          'list-style': 'none',
          'font-size': 'var(--iris-font-size-md, 14px)',
        }}
      >
        <For each={items()}>
          {(item, i) => (
            <>
              <li
                data-iris-breadcrumb-item=""
                data-iris-breadcrumb-last={i() === items().length - 1 ? 'true' : undefined}
                style={{ display: 'inline-flex', 'align-items': 'center' }}
              >
                {item as JSX.Element}
              </li>
              <Show when={i() !== items().length - 1}>
                <li
                  data-iris-breadcrumb-separator=""
                  aria-hidden="true"
                  style={{
                    color: 'var(--iris-muted)',
                    display: 'inline-flex',
                    'align-items': 'center',
                  }}
                >
                  {merged.separator}
                </li>
              </Show>
            </>
          )}
        </For>
      </ol>
    </nav>
  )
}
