// packages/react/src/behaviors/LongPress.tsx
/**
 * Behavior wrapper: detects a press-and-hold gesture on the wrapped element.
 * Fires `onLongPress` when the pointer is held down for `holdDelay` ms.
 * Wraps children in a `display: contents` span so event bubbling works.
 *
 * Composable: stack with `IrisMovable` / `IrisResizable` / `IrisSortable` /
 * `IrisHotkey` for richer interactions.
 *
 * @example
 *   <IrisLongPress holdDelay={500} onLongPress={() => setOpen(true)}>
 *     <img src="thumbnail.jpg" alt="Hold to preview" />
 *   </IrisLongPress>
 */
import * as React from 'react'
import { createLongPress } from '@iris-ui-kit/core'

export interface IrisLongPressProps {
  /** Time in ms the pointer must be held before `onLongPress` fires. */
  holdDelay?: number
  /** Called once when the hold reaches `holdDelay`. */
  onLongPress: () => void
  disabled?: boolean
  children?: React.ReactNode
}

export function IrisLongPress({
  holdDelay = 500,
  onLongPress,
  disabled = false,
  children,
}: IrisLongPressProps): React.ReactElement {
  const handlerRef = React.useRef(onLongPress)
  handlerRef.current = onLongPress

  const ctrl = React.useMemo(
    () =>
      createLongPress({
        holdDelay,
        onLongPress: () => handlerRef.current(),
      }),
    [holdDelay],
  )

  const onPointerDown_ = (_e: React.PointerEvent) => {
    if (disabled) return
    ctrl.press()
  }

  const onPointerUp_ = () => {
    ctrl.release()
  }

  const onPointerLeave_ = () => {
    ctrl.cancel()
  }

  return (
    <span
      data-iris-long-press=""
      onPointerDown={onPointerDown_}
      onPointerUp={onPointerUp_}
      onPointerLeave={onPointerLeave_}
      style={{ display: 'contents' }}
    >
      {children}
    </span>
  )
}

// packages/solid/src/behaviors/LongPress.tsx
import { mergeProps, splitProps, type JSX } from 'solid-js'
import { createLongPress } from '@iris-ui-kit/core'

export interface IrisLongPressProps {
  /** Time the pointer must be held before `onLongPress` fires, in ms. Defaults to 500. */
  holdDelay?: number
  /** Called once when the hold reaches `holdDelay` without an intervening release. */
  onLongPress: () => void
  disabled?: boolean
  children?: JSX.Element
}

/**
 * IrisLongPress (Solid) — Behavior wrapper for press-and-hold gestures.
 * Wraps the framework-agnostic `createLongPress` from `@iris-ui-kit/core`. Renders
 * a `<span data-iris-long-press>` with `display: contents` so it doesn't
 * affect layout.
 */
export function IrisLongPress(props: IrisLongPressProps): JSX.Element {
  const merged = mergeProps({ holdDelay: 500, disabled: false }, props)
  const [local] = splitProps(merged, ['holdDelay', 'onLongPress', 'disabled', 'children'])

  // Solid components only run their setup body once, so this mirrors the
  // React reference's `useMemo(..., [holdDelay])` — the controller is created
  // once for the component's lifetime. `onLongPress` is read from `local`
  // (a reactive getter) at fire-time rather than captured here, so a
  // changing callback identity is always honored without recreating the
  // controller.
  const ctrl = createLongPress({
    holdDelay: local.holdDelay,
    onLongPress: () => local.onLongPress(),
  })

  const onPointerDown = () => {
    if (local.disabled) return
    ctrl.press()
  }
  const onPointerUp = () => ctrl.release()
  const onPointerLeave = () => ctrl.cancel()

  return (
    <span
      data-iris-long-press=""
      onPointerDown={onPointerDown}
      onPointerUp={onPointerUp}
      onPointerLeave={onPointerLeave}
      style={{ display: 'contents' }}
    >
      {local.children}
    </span>
  )
}
