// packages/solid/src/primitives/segmented/IrisSegmented.tsx
import { createSignal, For, mergeProps, splitProps, type JSX } from 'solid-js'

export type IrisSegmentedSize = 'sm' | 'md' | 'lg'

export interface IrisSegmentedOption {
  label: string
  value: string
  disabled?: boolean
}

const SIZE_MAP: Record<IrisSegmentedSize, { padding: string; fontSize: string; height: string }> = {
  sm: { padding: '2px 8px', fontSize: '12px', height: '24px' },
  md: { padding: '4px 12px', fontSize: '14px', height: '30px' },
  lg: { padding: '6px 16px', fontSize: '16px', height: '36px' },
}

function normalize(options: Array<IrisSegmentedOption | string>): IrisSegmentedOption[] {
  return options.map((o) => (typeof o === 'string' ? { label: o, value: o } : o))
}

export interface IrisSegmentedProps {
  options: Array<IrisSegmentedOption | string>
  value?: string
  defaultValue?: string
  size?: IrisSegmentedSize
  disabled?: boolean
  block?: boolean
  ariaLabel?: string
  onChange?: (value: string) => void
  style?: JSX.CSSProperties | string
  class?: string
}

/**
 * Segmented control. Solid port of the Vue/React IrisSegmented.
 */
export function IrisSegmented(props: IrisSegmentedProps): JSX.Element {
  const merged = mergeProps(
    {
      options: [] as Array<IrisSegmentedOption | string>,
      defaultValue: '',
      size: 'md' as IrisSegmentedSize,
      disabled: false,
      block: false,
    },
    props,
  )
  const [local, rest] = splitProps(merged, [
    'options',
    'value',
    'defaultValue',
    'size',
    'disabled',
    'block',
    'ariaLabel',
    'onChange',
  ])

  const isControlled = (): boolean => local.value !== undefined
  const [internal, setInternal] = createSignal(local.defaultValue ?? '')

  const currentValue = (): string => (isControlled() ? (local.value as string) : internal())

  const norm = (): IrisSegmentedOption[] => normalize(local.options)

  const btns: (HTMLButtonElement | null)[] = []

  const select = (options: IrisSegmentedOption[], i: number): void => {
    const opt = options[i]
    if (!opt || opt.disabled || local.disabled) return
    if (!isControlled()) setInternal(opt.value)
    local.onChange?.(opt.value)
    btns[i]?.focus()
  }

  const move = (options: IrisSegmentedOption[], from: number, dir: 1 | -1): void => {
    if (local.disabled) return
    let i = from
    for (let s = 0; s < options.length; s++) {
      i = (i + dir + options.length) % options.length
      const opt = options[i]
      if (opt && !opt.disabled) {
        select(options, i)
        return
      }
    }
  }

  const sz = (): { padding: string; fontSize: string; height: string } => SIZE_MAP[local.size]

  return (
    <div
      {...rest}
      role="radiogroup"
      aria-label={local.ariaLabel}
      data-iris-segmented=""
      data-iris-segmented-size={local.size}
      data-disabled={local.disabled ? 'true' : undefined}
      style={{
        display: local.block ? 'flex' : 'inline-flex',
        width: local.block ? '100%' : undefined,
        gap: '2px',
        padding: '2px',
        background: 'var(--iris-surface, var(--iris-muted, #f4f4f4))',
        'border-radius': 'var(--iris-radius-md, 6px)',
        opacity: local.disabled ? 0.6 : 1,
        ...((rest.style as JSX.CSSProperties) ?? {}),
      }}
    >
      <For each={norm()}>
        {(opt, i) => {
          const selected = (): boolean => opt.value === currentValue()
          const options = norm()
          const selectedIndex = (): number => options.findIndex((o) => o.value === currentValue())
          const firstEnabled = (): number => options.findIndex((o) => !o.disabled)
          const rovingIndex = (): number => {
            const si = selectedIndex()
            return si >= 0 ? si : firstEnabled()
          }

          return (
            <button
              ref={(el) => {
                btns[i()] = el
              }}
              type="button"
              role="radio"
              aria-checked={selected() ? 'true' : 'false'}
              disabled={local.disabled || opt.disabled}
              tabindex={i() === rovingIndex() ? 0 : -1}
              data-iris-segmented-item=""
              data-value={opt.value}
              data-selected={selected() ? 'true' : undefined}
              onClick={() => select(norm(), i())}
              onKeyDown={(e) => {
                const n = norm()
                if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
                  e.preventDefault()
                  move(n, i(), 1)
                } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
                  e.preventDefault()
                  move(n, i(), -1)
                } else if (e.key === 'Home') {
                  e.preventDefault()
                  const fe = n.findIndex((o) => !o.disabled)
                  if (fe >= 0) select(n, fe)
                } else if (e.key === 'End') {
                  e.preventDefault()
                  for (let j = n.length - 1; j >= 0; j--) {
                    if (!n[j]?.disabled) {
                      select(n, j)
                      break
                    }
                  }
                }
              }}
              style={{
                flex: local.block ? '1' : undefined,
                padding: sz().padding,
                'min-height': sz().height,
                'font-size': sz().fontSize,
                'font-family': 'inherit',
                border: 'none',
                'border-radius': 'var(--iris-radius-sm, 4px)',
                cursor: local.disabled || opt.disabled ? 'not-allowed' : 'pointer',
                background: selected() ? 'var(--iris-background)' : 'transparent',
                color: selected() ? 'var(--iris-foreground)' : 'var(--iris-muted)',
                'box-shadow': selected() ? '0 1px 3px rgba(0,0,0,0.12)' : 'none',
                'font-weight': selected() ? '600' : '400',
                transition: 'background-color 120ms ease, color 120ms ease',
                'white-space': 'nowrap',
              }}
            >
              {opt.label}
            </button>
          )
        }}
      </For>
    </div>
  )
}

// packages/svelte/src/primitives/segmented/IrisSegmented.svelte
<script lang="ts">
  import type { IrisSegmentedOption } from './types'

  type SegmentedSize = 'sm' | 'md' | 'lg'

  const SIZE_MAP: Record<SegmentedSize, { padding: string; fontSize: string; height: string }> = {
    sm: { padding: '2px 8px', fontSize: '12px', height: '24px' },
    md: { padding: '4px 12px', fontSize: '14px', height: '30px' },
    lg: { padding: '6px 16px', fontSize: '16px', height: '36px' },
  }

  function normalize(options: Array<IrisSegmentedOption | string>): IrisSegmentedOption[] {
    return options.map((o) => (typeof o === 'string' ? { label: o, value: o } : o))
  }

  let {
    options = [],
    value = '',
    size = 'md',
    disabled = false,
    block = false,
    ariaLabel,
    onchange,
    style,
    ...rest
  }: {
    options?: Array<IrisSegmentedOption | string>
    value?: string
    size?: SegmentedSize
    disabled?: boolean
    block?: boolean
    ariaLabel?: string
    onchange?: (value: string) => void
    style?: string
    [key: string]: unknown
  } = $props()

  let btnRefs = $state<(HTMLButtonElement | null)[]>([])

  const norm = $derived(normalize(options))
  const sz = $derived(SIZE_MAP[size])
  const selectedIndex = $derived(norm.findIndex((o) => o.value === value))
  const firstEnabled = $derived(norm.findIndex((o) => !o.disabled))
  const rovingIndex = $derived(selectedIndex >= 0 ? selectedIndex : firstEnabled)

  function select(i: number): void {
    const opt = norm[i]
    if (!opt || opt.disabled || disabled) return
    onchange?.(opt.value)
    btnRefs[i]?.focus()
  }

  function move(from: number, dir: 1 | -1): void {
    if (disabled) return
    let i = from
    for (let s = 0; s < norm.length; s++) {
      i = (i + dir + norm.length) % norm.length
      const opt = norm[i]
      if (opt && !opt.disabled) {
        select(i)
        return
      }
    }
  }

  function onKeyDown(event: KeyboardEvent, i: number): void {
    if (event.key === 'ArrowRight' || event.key === 'ArrowDown') {
      event.preventDefault()
      move(i, 1)
    } else if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') {
      event.preventDefault()
      move(i, -1)
    } else if (event.key === 'Home') {
      event.preventDefault()
      if (firstEnabled >= 0) select(firstEnabled)
    } else if (event.key === 'End') {
      event.preventDefault()
      for (let j = norm.length - 1; j >= 0; j--) {
        const o = norm[j]
        if (o && !o.disabled) {
          select(j)
          break
        }
      }
    }
  }
</script>

<div
  {...rest}
  role="radiogroup"
  aria-label={ariaLabel}
  data-iris-segmented
  data-iris-segmented-size={size}
  data-disabled={disabled ? 'true' : undefined}
  style="display:{block ? 'flex' : 'inline-flex'}; {block ? 'width:100%;' : ''} gap:2px; padding:2px; background:var(--iris-surface); border-radius:var(--iris-radius-md,6px); opacity:{disabled ? '0.6' : '1'};{style ? ' ' + style : ''}"
>
  {#each norm as opt, i (opt.value)}
    {@const selected = opt.value === value}
    <button
      bind:this={btnRefs[i]}
      type="button"
      role="radio"
      aria-checked={selected ? 'true' : 'false'}
      disabled={disabled || opt.disabled || undefined}
      tabindex={i === rovingIndex ? 0 : -1}
      data-iris-segmented-item
      data-value={opt.value}
      data-selected={selected ? 'true' : undefined}
      onclick={() => select(i)}
      onkeydown={(e) => onKeyDown(e, i)}
      style="flex:{block ? '1' : undefined}; padding:{sz.padding}; min-height:{sz.height}; font-size:{sz.fontSize}; font-family:inherit; border:none; border-radius:var(--iris-radius-sm,4px); cursor:{disabled || opt.disabled ? 'not-allowed' : 'pointer'}; background:{selected ? 'var(--iris-background)' : 'transparent'}; color:{selected ? 'var(--iris-foreground)' : 'var(--iris-muted)'}; box-shadow:{selected ? '0 1px 3px rgba(0,0,0,0.12)' : 'none'}; font-weight:{selected ? '600' : '400'}; transition:background-color 120ms ease,color 120ms ease; white-space:nowrap;"
    >
      {opt.label}
    </button>
  {/each}
</div>
