// packages/react/src/useStore.ts
import * as React from 'react'
import { useSyncExternalStore } from 'react'
import type { ReadonlyStore, Store } from '@iris-ui-kit/core'

/**
 * Bridge a framework-agnostic `@iris-ui-kit/core` store into React reactivity.
 * Uses React 18's `useSyncExternalStore` — the contract is identical to the
 * one Vue uses via `ref + onMounted` and Solid uses via `createSignal`. The
 * **same** store can power Button, Popover, Dialog, etc. on any framework.
 */
export function useStore<T>(store: ReadonlyStore<T>): T {
  return useSyncExternalStore(
    store.subscribe,
    store.getState,
    store.getState, // SSR fallback — same as client snapshot in our case.
  )
}

/**
 * Subscribe to a DERIVED slice of a core store — the component re-renders only
 * when `selector(state)` changes per `isEqual` (default `Object.is`), not on
 * every store emission. Built on {@link Store.subscribeWith}. Inline closures
 * for `selector`/`isEqual` are fine (captured via refs; the subscription is not
 * re-created between renders).
 */
export function useStoreSelector<T, U>(
  store: Store<T>,
  selector: (state: T) => U,
  isEqual?: (a: U, b: U) => boolean,
): U {
  const [slice, setSlice] = React.useState(() => selector(store.getState()))
  const selRef = React.useRef(selector)
  selRef.current = selector
  const eqRef = React.useRef(isEqual)
  eqRef.current = isEqual
  React.useEffect(() => {
    const read = (s: T): U => selRef.current(s)
    const eq = (a: U, b: U): boolean => (eqRef.current ?? Object.is)(a, b)
    // Re-sync in case the store moved between render and this effect.
    setSlice((prev) => {
      const next = read(store.getState())
      return eq(prev, next) ? prev : next
    })
    return store.subscribeWith(read, setSlice, eq)
  }, [store])
  return slice
}

// packages/solid/src/useStore.ts
import { createSignal, onCleanup, type Accessor } from 'solid-js'
import type { ReadonlyStore, Store } from '@iris-ui-kit/core'

/**
 * Bridge a framework-agnostic `@iris-ui-kit/core` store into Solid reactivity.
 * Returns an accessor `() => T` that updates on every store emission — the
 * same contract React covers via `useSyncExternalStore` and Vue via
 * `ref + subscribe`. The **same** store powers Button/Popover/Dialog etc. on
 * every framework; only this thin bridge differs.
 *
 * Preferred over Solid's built-in `from(store)` because it has a synchronous
 * initial value (no `undefined` flash) and is SSR-safe.
 */
export function useStore<T>(store: ReadonlyStore<T>): Accessor<T> {
  const [state, setState] = createSignal(store.getState())
  // A signal setter treats a function argument as an updater, so wrap the
  // value in a thunk in case T is itself a function/object.
  const unsubscribe = store.subscribe((next) => setState(() => next))
  onCleanup(unsubscribe)
  return state
}

/**
 * Subscribe to a DERIVED slice of a core store — the accessor updates only when
 * `selector(state)` changes per `equals` (default `Object.is`), not on every
 * store emission. Built on {@link Store.subscribeWith}.
 */
export function useStoreSelector<T, U>(
  store: Store<T>,
  selector: (state: T) => U,
  equals?: (a: U, b: U) => boolean,
): Accessor<U> {
  const [slice, setSlice] = createSignal(selector(store.getState()))
  const unsubscribe = store.subscribeWith(selector, (v) => setSlice(() => v), equals)
  onCleanup(unsubscribe)
  return slice
}
