// packages/react/src/layouts/Stack.tsx
import * as React from 'react'

export type IrisStackDirection = 'row' | 'column'
export type IrisStackAlign = 'start' | 'center' | 'end' | 'stretch'
export type IrisStackJustify = 'start' | 'center' | 'end' | 'between' | 'around'

const ALIGN_MAP: Record<IrisStackAlign, string> = {
  start: 'flex-start',
  center: 'center',
  end: 'flex-end',
  stretch: 'stretch',
}

const JUSTIFY_MAP: Record<IrisStackJustify, string> = {
  start: 'flex-start',
  center: 'center',
  end: 'flex-end',
  between: 'space-between',
  around: 'space-around',
}

function toCssSpacing(spacing: string | number): string {
  if (typeof spacing === 'number') return `${spacing}px`
  if (spacing === 'sm' || spacing === 'md' || spacing === 'lg') {
    return `var(--iris-gap-${spacing})`
  }
  return spacing
}

export interface IrisStackProps extends React.HTMLAttributes<HTMLDivElement> {
  direction?: IrisStackDirection
  spacing?: string | number
  align?: IrisStackAlign
  justify?: IrisStackJustify
  wrap?: boolean
  /** When true, renders as `inline-flex`. */
  inline?: boolean
}

/**
 * Flex container with token-driven spacing. The lightest possible layout
 * primitive — saves hand-writing `display: flex` everywhere.
 */
export const IrisStack = React.forwardRef<HTMLDivElement, IrisStackProps>(function IrisStack(
  {
    direction = 'column',
    spacing = 'md',
    align = 'stretch',
    justify = 'start',
    wrap = false,
    inline = false,
    style,
    children,
    ...rest
  },
  ref,
) {
  return (
    <div
      {...rest}
      ref={ref}
      data-iris-stack=""
      data-iris-stack-direction={direction}
      style={{
        display: inline ? 'inline-flex' : 'flex',
        flexDirection: direction,
        gap: toCssSpacing(spacing),
        alignItems: ALIGN_MAP[align],
        justifyContent: JUSTIFY_MAP[justify],
        flexWrap: wrap ? 'wrap' : 'nowrap',
        ...style,
      }}
    >
      {children}
    </div>
  )
})

// packages/solid/src/layouts/Stack.tsx
import { mergeProps, splitProps, type JSX } from 'solid-js'

export type IrisStackDirection = 'row' | 'column'
export type IrisStackAlign = 'start' | 'center' | 'end' | 'stretch'
export type IrisStackJustify = 'start' | 'center' | 'end' | 'between' | 'around'

const ALIGN_MAP: Record<IrisStackAlign, string> = {
  start: 'flex-start',
  center: 'center',
  end: 'flex-end',
  stretch: 'stretch',
}
const JUSTIFY_MAP: Record<IrisStackJustify, string> = {
  start: 'flex-start',
  center: 'center',
  end: 'flex-end',
  between: 'space-between',
  around: 'space-around',
}

function toCssSpacing(spacing: string | number): string {
  if (typeof spacing === 'number') return `${spacing}px`
  if (spacing === 'sm' || spacing === 'md' || spacing === 'lg') return `var(--iris-gap-${spacing})`
  return spacing
}

export interface IrisStackProps extends JSX.HTMLAttributes<HTMLDivElement> {
  direction?: IrisStackDirection
  spacing?: string | number
  align?: IrisStackAlign
  justify?: IrisStackJustify
  wrap?: boolean
  inline?: boolean
}

/** Flex container with token-driven spacing. Solid port of the React/Vue IrisStack. */
export function IrisStack(props: IrisStackProps): JSX.Element {
  const merged = mergeProps(
    {
      direction: 'column' as IrisStackDirection,
      spacing: 'md' as string | number,
      align: 'stretch' as IrisStackAlign,
      justify: 'start' as IrisStackJustify,
      wrap: false,
      inline: false,
    },
    props,
  )
  const [local, others] = splitProps(merged, [
    'direction',
    'spacing',
    'align',
    'justify',
    'wrap',
    'inline',
    'style',
    'children',
  ])
  return (
    <div
      {...others}
      data-iris-stack=""
      data-iris-stack-direction={local.direction}
      style={{
        display: local.inline ? 'inline-flex' : 'flex',
        'flex-direction': local.direction,
        gap: toCssSpacing(local.spacing),
        'align-items': ALIGN_MAP[local.align],
        'justify-content': JUSTIFY_MAP[local.justify],
        'flex-wrap': local.wrap ? 'wrap' : 'nowrap',
        ...((local.style as JSX.CSSProperties) ?? {}),
      }}
    >
      {local.children}
    </div>
  )
}
