// registry/templates/admin-layout/solid/AdminLayout.tsx
import type { JSX } from 'solid-js'
import {
  IrisAdminLayout,
  useAdminPreferences,
  type AdminPreferences,
  type NavNode,
  type TabsNav,
} from '@iris-ui-kit/solid/admin'

export interface AdminLayoutProps {
  menus: NavNode[]
  activeKey: string
  onNavigate: (key: string) => void
  preferences: AdminPreferences
  tabs?: TabsNav
  appTitle?: string
  logo?: JSX.Element | ((state: { collapsed: boolean }) => JSX.Element)
  toolbar?: JSX.Element
  footer?: JSX.Element
  children?: JSX.Element | ((state: { activeKey: string }) => JSX.Element)
}

/** Stable admin shell; runtime changes only declarative preferences/data. */
export function AdminLayout(props: AdminLayoutProps): JSX.Element {
  const preferences = useAdminPreferences(props.preferences)
  const state = preferences.state
  return (
    <div data-admin-layout="" data-density={state().density}>
      <IrisAdminLayout
        menus={props.menus}
        activeKey={props.activeKey}
        onActiveKeyChange={props.onNavigate}
        collapsed={state().collapsed}
        onCollapsedChange={(value) => preferences.set('collapsed', value)}
        mode={state().navigationMode}
        menuAlign={state().menuAlign}
        contentWidth={state().contentWidth}
        contentHeight={state().contentHeight}
        showTabs={state().showTabs}
        showBreadcrumb={state().showBreadcrumb}
        stickyHeader={state().stickyHeader}
        stickyTabs={state().stickyTabs}
        tabs={props.tabs}
        appTitle={props.appTitle ?? 'Admin'}
        logo={props.logo}
        toolbar={props.toolbar}
        footer={props.footer}
      >
        {props.children}
      </IrisAdminLayout>
    </div>
  )
}

// registry/templates/admin-layout/svelte/AdminLayout.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import {
    IrisAdminLayout,
    useAdminPreferences,
    type AdminPreferences,
    type NavNode,
    type TabsNav,
  } from '@iris-ui-kit/svelte/admin'

  interface Props {
    menus: NavNode[]
    activeKey: string
    onNavigate: (key: string) => void
    preferences: AdminPreferences
    tabs?: TabsNav
    appTitle?: string
    logo?: Snippet<[{ collapsed: boolean }]>
    toolbar?: Snippet
    footer?: Snippet
    children?: Snippet<[{ activeKey: string }]>
  }

  let {
    menus,
    activeKey,
    onNavigate,
    preferences: controller,
    tabs,
    appTitle = 'Admin',
    logo,
    toolbar,
    footer,
    children,
  }: Props = $props()
  // svelte-ignore state_referenced_locally — controller identity is stable for the shell lifetime.
  const preferences = useAdminPreferences(controller)
  const { state } = preferences
</script>

<!-- Stable shell: pages remain statically imported and render through children. -->
<div data-admin-layout data-density={$state.density}>
  <IrisAdminLayout
    {menus}
    {activeKey}
    onActiveKeyChange={onNavigate}
    collapsed={$state.collapsed}
    onCollapsedChange={(value) => preferences.set('collapsed', value)}
    mode={$state.navigationMode}
    menuAlign={$state.menuAlign}
    contentWidth={$state.contentWidth}
    contentHeight={$state.contentHeight}
    showTabs={$state.showTabs}
    showBreadcrumb={$state.showBreadcrumb}
    stickyHeader={$state.stickyHeader}
    stickyTabs={$state.stickyTabs}
    {tabs}
    {appTitle}
    {logo}
    {toolbar}
    {footer}
    {children}
  />
</div>
