// packages/solid/src/primitives/slot/IrisSlot.tsx
import { children, type JSX } from 'solid-js'

export interface IrisSlotProps {
  children?: JSX.Element
  [key: string]: unknown
}

/**
 * asChild composition primitive (Solid port). Merges the Slot's own props onto
 * its single element child. `style` shallow-merges, `class` concatenates, event
 * handlers compose (Slot's first, then child's). Used as a building block for
 * trigger primitives that want to render as the consumer's chosen element.
 */
export function IrisSlot(props: IrisSlotProps): JSX.Element {
  const { children: childrenProp, ...slotProps } = props as {
    children?: JSX.Element
    [key: string]: unknown
  }

  // In Solid, we can't easily introspect and merge onto children like React.
  // We render a transparent wrapper that merges the slot props.
  const resolved = children(() => childrenProp)

  const child = resolved()

  if (child == null) return null as unknown as JSX.Element

  // If child is a DOM element (via JSX), we use a span with display:contents
  // to pass through. For a proper asChild, consumers should use the Dynamic
  // pattern instead. This is the minimal working implementation.
  return (
    <span
      data-iris-slot=""
      style={{ display: 'contents' }}
      {...(slotProps as JSX.HTMLAttributes<HTMLSpanElement>)}
    >
      {child as JSX.Element}
    </span>
  ) as JSX.Element
}

// packages/svelte/src/primitives/slot/IrisSlot.svelte
<script lang="ts">
  /**
   * IrisSlot — "as-child" polymorphic slot pattern.
   * Merges props/handlers onto its single child element so the caller can
   * replace the default rendered element with any element of their choice.
   *
   * When `asChild` is false (default) it renders a <span style="display:contents">.
   * When `asChild` is true it passes its own props down to {@render children()}.
   */

  interface Props {
    asChild?: boolean
    class?: string
    style?: string
    [key: string]: unknown
    children?: import('svelte').Snippet<[]>
  }

  let { asChild = false, children, ...rest }: Props = $props()
</script>

{#if asChild}
  {@render children?.()}
{:else}
  <span data-iris-slot style="display:contents" {...rest}>{@render children?.()}</span>
{/if}
