// packages/svelte/src/theme/ThemeProvider.svelte
<script lang="ts">
  import { setContext } from 'svelte'
  import { readonly, writable } from 'svelte/store'
  import { applyDirection, applyTheme, injectGlobalStyles } from '@iris-ui/theme'
  // (Direction is inferred from the `dir` prop via ThemeProviderProps.)
  import { toStore } from '../useStore'
  import { THEME_KEY, type IrisThemeContextValue, type ThemeProviderProps } from './context'

  let { store, target = null, dir = 'ltr', children }: ThemeProviderProps = $props()

  // Bridge the framework-agnostic theme store into a Svelte readable, exactly
  // like the React `useSyncExternalStore` / Vue `ref + subscribe` / Solid
  // `useStore` bridges. Zero business logic — `applyTheme` lives in @iris-ui/theme.
  // svelte-ignore state_referenced_locally — `store` is a stable instance, read once.
  const current = toStore(store.store)
  const theme = $derived($current)

  // Mirror the `dir` prop into a store so `useDirection()` consumers stay reactive.
  // svelte-ignore state_referenced_locally — initial value; kept in sync below.
  const dirStore = writable(dir)
  $effect(() => {
    dirStore.set(dir)
  })

  // svelte-ignore state_referenced_locally — `store` is a stable instance.
  setContext<IrisThemeContextValue>(THEME_KEY, {
    store,
    current,
    dir: readonly(dirStore),
  })

  // Apply CSS variables + writing direction to the target; revert on
  // change/unmount via the $effect teardown (mirrors Solid's onCleanup).
  $effect(() => {
    injectGlobalStyles()
    const el = target ?? document.documentElement
    const appliedTheme = applyTheme(theme, el)
    const appliedDir = applyDirection(dir, el)
    return () => {
      appliedTheme.revert()
      appliedDir.revert()
    }
  })
</script>

{@render children?.()}

// packages/solid/src/theme/ThemeProvider.tsx
import {
  createContext,
  createEffect,
  onCleanup,
  useContext,
  type Accessor,
  type JSX,
} from 'solid-js'
import {
  applyDirection,
  applyTheme,
  injectGlobalStyles,
  type Direction,
  type ThemeStore,
} from '@iris-ui/theme'
import type { IrisTheme } from '@iris-ui/tokens'
import { useStore } from '../useStore'

interface IrisThemeContextValue {
  store: ThemeStore
  current: Accessor<IrisTheme>
  dir: Accessor<Direction>
}

const IrisThemeContext = createContext<IrisThemeContextValue>()

export interface ThemeProviderProps {
  store: ThemeStore
  target?: HTMLElement | null
  /** Writing direction; sets `dir` on the target for RTL. Default `'ltr'`. */
  dir?: Direction
  children?: JSX.Element
}

/**
 * Renderless provider mirroring the React/Vue `ThemeProvider`: subscribes to the
 * theme store, applies CSS variables to `target` (or `document.documentElement`)
 * via a `createEffect`, and reverts on change/unmount through `onCleanup`.
 * **Zero business logic** — `applyTheme` / `createThemeStore` come from
 * `@iris-ui/theme`; this is just the thin Solid bridge.
 */
export function ThemeProvider(props: ThemeProviderProps): JSX.Element {
  const current = useStore(props.store.store)
  const dir = (): Direction => props.dir ?? 'ltr'

  createEffect(() => {
    injectGlobalStyles()
    const el = props.target ?? document.documentElement
    const appliedTheme = applyTheme(current(), el)
    const appliedDir = applyDirection(dir(), el)
    onCleanup(() => {
      appliedTheme.revert()
      appliedDir.revert()
    })
  })

  return (
    <IrisThemeContext.Provider value={{ store: props.store, current, dir }}>
      {props.children}
    </IrisThemeContext.Provider>
  )
}

export function useThemeContext(): IrisThemeContextValue {
  const ctx = useContext(IrisThemeContext)
  if (!ctx) throw new Error('[iris-ui] useTheme(): no <ThemeProvider> ancestor found')
  return ctx
}

/** Non-throwing read for theme-aware primitives that may render standalone. */
export function useThemeOptional(): Accessor<IrisTheme> | undefined {
  return useContext(IrisThemeContext)?.current
}

/** Current writing direction accessor (`'ltr'` when there is no provider). */
export function useDirection(): Accessor<Direction> {
  const ctx = useContext(IrisThemeContext)
  return ctx ? ctx.dir : () => 'ltr'
}
