// apps/desktop-os-svelte/src/Taskbar.svelte
<script lang="ts">
  import { wm, useWmState } from './wm.svelte'
  import { getApp } from './apps'

  interface Props {
    launcherOpen: boolean
    onToggleLauncher: () => void
  }

  let { launcherOpen, onToggleLauncher }: Props = $props()

  const wmState = useWmState()
  const windows = $derived(wmState.value.windows)

  // Live clock.
  let now = $state(new Date())
  $effect(() => {
    const t = setInterval(() => (now = new Date()), 1000 * 30)
    return () => clearInterval(t)
  })
  const time = $derived(now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }))
  const date = $derived(
    now.toLocaleDateString([], { month: 'numeric', day: 'numeric', year: 'numeric' }),
  )

  function onTask(id: string) {
    const win = windows.find((x) => x.id === id)
    if (!win) return
    if (win.focused && win.state !== 'minimized') wm.minimize(id)
    else wm.focus(id)
  }
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="taskbar" onpointerdown={(e) => e.stopPropagation()}>
  <div style="display:flex;align-items:center;gap:4px">
    <button
      type="button"
      aria-label="Start"
      aria-pressed={launcherOpen}
      class="task-btn task-btn--start"
      style="font-size:18px"
      onpointerdown={(e) => {
        e.stopPropagation()
        onToggleLauncher()
      }}>⊞</button
    >
    {#each windows as w (w.id)}
      {@const active = w.focused && w.state !== 'minimized'}
      <button
        type="button"
        title={w.title}
        class="task-btn{active ? ' task-btn--active' : ''}"
        onpointerdown={(e) => {
          e.stopPropagation()
          onTask(w.id)
        }}
      >
        <span style="font-size:18px">{getApp(w.appId)?.icon}</span>
      </button>
    {/each}
  </div>
  <div class="clock">
    <div>{time}</div>
    <div>{date}</div>
  </div>
</div>

<style>
  .taskbar {
    position: absolute;
    left: 0;
    right: 0;
    bottom: 0;
    height: var(--os-bar-h);
    display: flex;
    align-items: center;
    justify-content: center;
    color: var(--os-bar-fg);
    background: var(--os-bar-bg);
    backdrop-filter: var(--os-blur);
    -webkit-backdrop-filter: var(--os-blur);
    border-top: 1px solid rgba(255, 255, 255, 0.18);
  }
  .clock {
    position: absolute;
    right: 0;
    top: 0;
    bottom: 0;
    display: flex;
    flex-direction: column;
    align-items: flex-end;
    justify-content: center;
    text-align: right;
    font-size: 12px;
    line-height: 1.25;
    padding: 0 14px;
  }
</style>

// apps/desktop-os-solid/src/Taskbar.tsx
import { For, createSignal, onCleanup, type JSX } from 'solid-js'
import { getApp } from './apps'
import { useWm, useWmState } from './wm'

function Clock(): JSX.Element {
  const [now, setNow] = createSignal(new Date())
  const t = setInterval(() => setNow(new Date()), 1000 * 30)
  onCleanup(() => clearInterval(t))
  return (
    <div
      style={{ 'text-align': 'right', 'font-size': '12px', 'line-height': 1.25, padding: '0 14px' }}
    >
      <div>{now().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</div>
      <div>
        {now().toLocaleDateString([], { month: 'numeric', day: 'numeric', year: 'numeric' })}
      </div>
    </div>
  )
}

/** Windows 11 taskbar: centered Start + running apps; clock pinned right. */
export function Taskbar(props: {
  launcherOpen: boolean
  onToggleLauncher: () => void
}): JSX.Element {
  const wm = useWm()
  const state = useWmState()

  const onTask = (id: string): void => {
    const w = state().windows.find((x) => x.id === id)
    if (!w) return
    if (w.focused && w.state !== 'minimized') wm.minimize(id)
    else wm.focus(id)
  }

  return (
    <div
      class="taskbar"
      onPointerDown={(e) => e.stopPropagation()}
      style={{
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        height: 'var(--os-bar-h)',
        display: 'flex',
        'align-items': 'center',
        'justify-content': 'center',
        color: 'var(--os-bar-fg)',
        background: 'var(--os-bar-bg)',
        'backdrop-filter': 'var(--os-blur)',
        '-webkit-backdrop-filter': 'var(--os-blur)',
        'border-top': '1px solid rgba(255,255,255,0.18)',
      }}
    >
      <div style={{ display: 'flex', 'align-items': 'center', gap: '4px' }}>
        <button
          type="button"
          aria-label="Start"
          aria-pressed={props.launcherOpen}
          class="task-btn task-btn--start"
          onPointerDown={(e) => {
            e.stopPropagation()
            props.onToggleLauncher()
          }}
          style={{ 'font-size': '18px' }}
        >
          ⊞
        </button>
        <For each={state().windows}>
          {(w) => {
            const active = (): boolean => w.focused && w.state !== 'minimized'
            return (
              <button
                type="button"
                title={w.title}
                class={`task-btn${active() ? ' task-btn--active' : ''}`}
                onPointerDown={(e) => {
                  e.stopPropagation()
                  onTask(w.id)
                }}
              >
                <span style={{ 'font-size': '18px' }}>{getApp(w.appId)?.icon}</span>
              </button>
            )
          }}
        </For>
      </div>
      <div
        style={{
          position: 'absolute',
          right: 0,
          top: 0,
          bottom: 0,
          display: 'flex',
          'align-items': 'center',
        }}
      >
        <Clock />
      </div>
    </div>
  )
}
