// packages/svelte/src/primitives/popover/IrisPopoverTrigger.svelte
<script lang="ts">
  import { getPopoverContext } from './context'

  interface Props {
    onclick?: (e: MouseEvent) => void
    children?: import('svelte').Snippet
    [key: string]: unknown
  }

  let { onclick, children, ...rest }: Props = $props()
  const ctx = getPopoverContext('IrisPopoverTrigger')

  function setTriggerRef(node: HTMLElement): { destroy: () => void } {
    ctx.setTrigger(node)
    return { destroy: () => ctx.setTrigger(undefined) }
  }

  function handleClick(e: MouseEvent): void {
    onclick?.(e)
    ctx.setOpen(!ctx.open)
  }
</script>

<button
  type="button"
  {...rest}
  use:setTriggerRef
  aria-haspopup="dialog"
  aria-expanded={ctx.open}
  aria-controls={ctx.contentId}
  data-state={ctx.open ? 'open' : 'closed'}
  onclick={handleClick}
>
  {@render children?.()}
</button>

// packages/solid/src/primitives/popover/IrisPopoverTrigger.tsx
import { splitProps, type JSX } from 'solid-js'
import { usePopoverContext } from './context'

export interface IrisPopoverTriggerProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
  children?: JSX.Element
}

/**
 * Popover trigger button. Toggles the popover on click.
 * Solid port of the Vue IrisPopoverTrigger.
 */
export function IrisPopoverTrigger(props: IrisPopoverTriggerProps): JSX.Element {
  const ctx = usePopoverContext('IrisPopoverTrigger')
  const [local, others] = splitProps(props, ['onClick', 'children'])

  const handleClick: JSX.EventHandler<HTMLButtonElement, MouseEvent> = (e) => {
    if (typeof local.onClick === 'function') local.onClick(e)
    ctx.setOpen(!ctx.open())
  }

  return (
    <button
      type="button"
      {...others}
      ref={ctx.setTrigger}
      aria-haspopup="dialog"
      aria-expanded={ctx.open()}
      aria-controls={ctx.contentId}
      data-state={ctx.open() ? 'open' : 'closed'}
      onClick={handleClick}
    >
      {local.children}
    </button>
  )
}
