// packages/svelte/src/primitives/carousel/IrisCarousel.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { useI18n } from '../../i18n'

  interface Props {
    value?: number
    loop?: boolean
    autoplay?: boolean
    interval?: number
    pauseOnHover?: boolean
    showArrows?: boolean
    showIndicators?: boolean
    ariaLabel?: string
    onValueChange?: (index: number) => void
    slides?: Snippet
    children?: Snippet
    style?: string
    class?: string
    slideCount?: number
  }

  let {
    value = 0,
    loop = true,
    autoplay = false,
    interval = 4000,
    pauseOnHover = true,
    showArrows = true,
    showIndicators = true,
    ariaLabel,
    onValueChange,
    slides,
    children,
    style,
    class: className,
    slideCount = 0,
    ...rest
  }: Props = $props()

  const { t } = useI18n()

  let hovered = $state(false)
  let focusedWithin = $state(false)
  let timerRef = $state<ReturnType<typeof setInterval> | undefined>(undefined)
  let liveText = $state('')

  function prefersReducedMotion(): boolean {
    return (
      typeof window !== 'undefined' &&
      typeof window.matchMedia === 'function' &&
      window.matchMedia('(prefers-reduced-motion: reduce)').matches
    )
  }

  function canAutoplay(): boolean {
    return autoplay && !prefersReducedMotion()
  }

  function stopTimer() {
    if (timerRef) clearInterval(timerRef)
    timerRef = undefined
  }

  function startTimer() {
    stopTimer()
    if (!canAutoplay()) return
    timerRef = setInterval(() => {
      if (!(pauseOnHover && hovered) && !focusedWithin) advance(1)
    }, interval)
  }

  $effect(() => {
    if (canAutoplay()) startTimer()
    else stopTimer()
    return () => stopTimer()
  })

  function advance(delta: number) {
    const count = slideCount || 1
    let next = value + delta
    if (loop) {
      next = ((next % count) + count) % count
    } else {
      next = Math.max(0, Math.min(count - 1, next))
    }
    if (next !== value) {
      onValueChange?.(next)
      liveText = t('carousel.slide', { index: next + 1, total: count })
    }
  }

  function goTo(idx: number) {
    if (idx !== value) {
      onValueChange?.(idx)
      liveText = t('carousel.slide', { index: idx + 1, total: slideCount })
    }
  }

  function onKeyDown(e: KeyboardEvent) {
    if (e.key === 'ArrowLeft') { e.preventDefault(); advance(-1) }
    else if (e.key === 'ArrowRight') { e.preventDefault(); advance(1) }
  }

  const canPrev = $derived(loop || value > 0)
  const canNext = $derived(loop || value < (slideCount - 1))
</script>

<div
  data-iris-carousel
  role="region"
  aria-roledescription="carousel"
  aria-label={ariaLabel ?? t('carousel.label')}
  onkeydown={onKeyDown}
  onmouseenter={() => { hovered = true }}
  onmouseleave={() => { hovered = false }}
  onfocusin={() => { focusedWithin = true }}
  onfocusout={() => { focusedWithin = false }}
  style:position="relative"
  style:overflow="hidden"
  style:display="flex"
  style:flex-direction="column"
  style={style}
  class={className}
  {...rest}
>
  <!-- Slides viewport -->
  <div
    data-iris-carousel-viewport
    style:position="relative"
    style:overflow="hidden"
    style:flex="1"
  >
    {#if slides}
      {@render slides()}
    {:else if children}
      {@render children()}
    {/if}
  </div>

  <!-- Arrows -->
  {#if showArrows}
    <button
      type="button"
      aria-label={t('carousel.previous')}
      data-iris-carousel-prev
      disabled={!canPrev}
      onclick={() => advance(-1)}
      style:position="absolute"
      style:left="8px"
      style:top="50%"
      style:transform="translateY(-50%)"
      style:z-index="2"
      style:width="32px"
      style:height="32px"
      style:border-radius="50%"
      style:border="1px solid var(--iris-border)"
      style:background="var(--iris-background)"
      style:color="var(--iris-foreground)"
      style:cursor={!canPrev ? 'not-allowed' : 'pointer'}
      style:opacity={!canPrev ? '0.4' : '1'}
      style:font-size="18px"
      style:display="inline-flex"
      style:align-items="center"
      style:justify-content="center"
    >‹</button>

    <button
      type="button"
      aria-label={t('carousel.next')}
      data-iris-carousel-next
      disabled={!canNext}
      onclick={() => advance(1)}
      style:position="absolute"
      style:right="8px"
      style:top="50%"
      style:transform="translateY(-50%)"
      style:z-index="2"
      style:width="32px"
      style:height="32px"
      style:border-radius="50%"
      style:border="1px solid var(--iris-border)"
      style:background="var(--iris-background)"
      style:color="var(--iris-foreground)"
      style:cursor={!canNext ? 'not-allowed' : 'pointer'}
      style:opacity={!canNext ? '0.4' : '1'}
      style:font-size="18px"
      style:display="inline-flex"
      style:align-items="center"
      style:justify-content="center"
    >›</button>
  {/if}

  <!-- Indicators -->
  {#if showIndicators && slideCount > 0}
    <div
      data-iris-carousel-indicators
      aria-hidden="true"
      style:display="flex"
      style:justify-content="center"
      style:gap="6px"
      style:padding="8px 0 4px"
    >
      {#each Array.from({ length: slideCount }, (_, i) => i) as i (i)}
        <button
          type="button"
          aria-label={t('carousel.goTo', { index: i + 1 })}
          data-state={i === value ? 'active' : 'idle'}
          onclick={() => goTo(i)}
          style:width={i === value ? '20px' : '8px'}
          style:height="8px"
          style:border-radius="4px"
          style:border="none"
          style:padding="0"
          style:cursor="pointer"
          style:background={i === value ? 'var(--iris-primary)' : 'var(--iris-border)'}
          style:transition="width 0.2s, background 0.2s"
        ></button>
      {/each}
    </div>
  {/if}

  <!-- ARIA live region -->
  <div aria-live="polite" aria-atomic="true" class="visually-hidden" style:position="absolute" style:width="1px" style:height="1px" style:overflow="hidden" style:clip="rect(0,0,0,0)">{liveText}</div>
</div>

// packages/solid/src/primitives/carousel/IrisCarousel.tsx
import {
  createSignal,
  createEffect,
  mergeProps,
  splitProps,
  Show,
  For,
  children,
  onCleanup,
  type JSX,
} from 'solid-js'
import { useI18n } from '../../i18n'

export interface IrisCarouselProps {
  index?: number
  defaultIndex?: number
  loop?: boolean
  autoplay?: boolean
  interval?: number
  pauseOnHover?: boolean
  showArrows?: boolean
  showIndicators?: boolean
  ariaLabel?: string
  onChange?: (index: number) => void
  children?: JSX.Element
}

/**
 * Slide carousel: shows one child at a time with prev/next controls, dots, and
 * keyboard (←/→) navigation. Solid port of the Vue IrisCarousel.
 */
export function IrisCarousel(props: IrisCarouselProps): JSX.Element {
  const merged = mergeProps(
    {
      defaultIndex: 0,
      loop: true,
      autoplay: false,
      interval: 4000,
      pauseOnHover: true,
      showArrows: true,
      showIndicators: true,
    },
    props,
  )
  const [local] = splitProps(merged, [
    'index',
    'defaultIndex',
    'loop',
    'autoplay',
    'interval',
    'pauseOnHover',
    'showArrows',
    'showIndicators',
    'ariaLabel',
    'onChange',
    'children',
  ])

  const { t } = useI18n()

  const [internalIndex, setInternalIndex] = createSignal(local.defaultIndex)
  const [paused, setPaused] = createSignal(false)
  const [focusedWithin, setFocusedWithin] = createSignal(false)

  // True when the user prefers reduced motion (SSR / jsdom safe). Autoplay is
  // disabled in that case, matching React/Vue/Svelte.
  const reducedMotion = (): boolean =>
    typeof window !== 'undefined' &&
    typeof window.matchMedia === 'function' &&
    window.matchMedia('(prefers-reduced-motion: reduce)').matches

  const currentIndex = () => (local.index !== undefined ? local.index : internalIndex())

  const resolved = children(() => local.children)
  const slides = (): JSX.Element[] => {
    const c = resolved.toArray()
    return c as JSX.Element[]
  }
  const count = () => slides().length

  const goTo = (idx: number) => {
    let next = idx
    if (local.loop) {
      next = ((idx % count()) + count()) % count()
    } else {
      next = Math.max(0, Math.min(count() - 1, idx))
    }
    if (next === currentIndex()) return
    if (local.index === undefined) setInternalIndex(next)
    local.onChange?.(next)
  }

  const prev = () => goTo(currentIndex() - 1)
  const next = () => goTo(currentIndex() + 1)

  // Autoplay — paused on hover/focus and when the user prefers reduced motion
  // (matches React/Vue/Svelte).
  createEffect(() => {
    if (!local.autoplay || paused() || focusedWithin() || count() <= 1 || reducedMotion()) return
    const id = setInterval(() => {
      goTo(currentIndex() + 1)
    }, local.interval)
    onCleanup(() => clearInterval(id))
  })

  const arrowBtnStyle: JSX.CSSProperties = {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    'z-index': '2',
    display: 'inline-flex',
    'align-items': 'center',
    'justify-content': 'center',
    width: '32px',
    height: '32px',
    'border-radius': '50%',
    border: '1px solid var(--iris-border)',
    background: 'var(--iris-background)',
    color: 'var(--iris-foreground)',
    cursor: 'pointer',
    'font-size': '18px',
  }

  return (
    <div
      data-iris-carousel=""
      role="region"
      aria-roledescription="carousel"
      aria-label={local.ariaLabel ?? t('carousel.label')}
      onKeyDown={(e) => {
        if (e.key === 'ArrowLeft') {
          e.preventDefault()
          prev()
        } else if (e.key === 'ArrowRight') {
          e.preventDefault()
          next()
        }
      }}
      onMouseEnter={() => local.pauseOnHover && setPaused(true)}
      onMouseLeave={() => setPaused(false)}
      onFocusIn={() => setFocusedWithin(true)}
      onFocusOut={() => setFocusedWithin(false)}
      tabIndex={0}
      style={{
        position: 'relative',
        overflow: 'hidden',
        outline: 'none',
        'user-select': 'none',
      }}
    >
      {/* Slides container */}
      <div
        data-iris-carousel-track=""
        aria-live="polite"
        style={{
          display: 'flex',
          transition: 'transform 300ms ease',
          transform: `translateX(-${currentIndex() * 100}%)`,
          width: `${count() * 100}%`,
        }}
      >
        <For each={slides()}>
          {(slide, i) => (
            <div
              data-iris-carousel-slide={i()}
              role="group"
              aria-roledescription="slide"
              aria-label={t('carousel.slide', { index: i() + 1, total: count() })}
              aria-hidden={i() !== currentIndex()}
              style={{ width: `${100 / count()}%`, 'flex-shrink': '0' }}
            >
              {slide}
            </div>
          )}
        </For>
      </div>

      {/* Arrows */}
      <Show when={local.showArrows && count() > 1}>
        <button
          type="button"
          data-iris-carousel-prev=""
          aria-label={t('carousel.previous')}
          onClick={prev}
          disabled={!local.loop && currentIndex() === 0 ? true : undefined}
          style={{ ...arrowBtnStyle, left: '8px' }}
        >
          ‹
        </button>
        <button
          type="button"
          data-iris-carousel-next=""
          aria-label={t('carousel.next')}
          onClick={next}
          disabled={!local.loop && currentIndex() === count() - 1 ? true : undefined}
          style={{ ...arrowBtnStyle, right: '8px' }}
        >
          ›
        </button>
      </Show>

      {/* Indicators */}
      <Show when={local.showIndicators && count() > 1}>
        <div
          data-iris-carousel-indicators=""
          role="tablist"
          aria-label={t('carousel.slides')}
          style={{
            position: 'absolute',
            bottom: '10px',
            left: '50%',
            transform: 'translateX(-50%)',
            display: 'flex',
            gap: '6px',
            'z-index': '2',
          }}
        >
          <For each={slides()}>
            {(_, i) => (
              <button
                type="button"
                role="tab"
                aria-selected={i() === currentIndex()}
                aria-label={t('carousel.goTo', { index: i() + 1 })}
                data-iris-carousel-indicator={i()}
                onClick={() => goTo(i())}
                style={{
                  width: '8px',
                  height: '8px',
                  padding: '0',
                  'border-radius': '50%',
                  border: 'none',
                  cursor: 'pointer',
                  background:
                    i() === currentIndex() ? 'var(--iris-primary)' : 'rgba(255,255,255,0.5)',
                  transition: 'background 200ms',
                }}
              />
            )}
          </For>
        </div>
      </Show>
    </div>
  )
}
