// packages/svelte/src/primitives/calendar/IrisCalendar.svelte
<script lang="ts">
  import {
    addDays,
    addMonths,
    buildMonthMatrix,
    clampDate,
    endOfMonth,
    formatLocalISO,
    formatMonthYear,
    getWeekdayNames,
    isOutOfRange,
    isSameDay,
    isSameMonth,
    startOfDay,
    startOfMonth,
  } from './dateUtils'
  import { useI18n } from '../../i18n'

  const { t } = useI18n()

  interface Props {
    value?: Date | null
    defaultMonth?: Date | null
    min?: Date
    max?: Date
    /** 0–6, 0 = Sunday */
    weekStartsOn?: number
    locale?: string
    disabled?: boolean
    onValueChange?: (date: Date | null) => void
    style?: string
    class?: string
  }

  let {
    value = null,
    defaultMonth = null,
    min,
    max,
    weekStartsOn = 0,
    locale,
    disabled = false,
    onValueChange,
    style,
    class: className,
    ...rest
  }: Props = $props()

  // svelte-ignore state_referenced_locally
  let visibleMonth = $state(startOfMonth(defaultMonth ?? value ?? new Date()))
  // svelte-ignore state_referenced_locally
  let focusDate = $state(clampDate(value ?? new Date(), min, max))

  $effect(() => {
    if (value && !isSameMonth(value, visibleMonth)) {
      visibleMonth = startOfMonth(value)
      focusDate = clampDate(value, min, max)
    }
  })

  const matrix = $derived(buildMonthMatrix(visibleMonth, weekStartsOn))
  const weekdays = $derived(getWeekdayNames(weekStartsOn, locale))
  const title = $derived(formatMonthYear(visibleMonth, locale))
  // One memoized formatter for the full-date cell label (e.g. "Monday, June 9,
  // 2026") so screen readers announce the whole date, not just the day number.
  const dayLabelFmt = $derived(
    new Intl.DateTimeFormat(locale, {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    }),
  )

  const prevDisabled = $derived(min ? startOfMonth(visibleMonth) <= startOfMonth(min) : false)
  const nextDisabled = $derived(max ? startOfMonth(endOfMonth(visibleMonth)) >= startOfMonth(max) : false)

  const today = startOfDay(new Date())

  function goPrevMonth() {
    visibleMonth = addMonths(visibleMonth, -1)
  }

  function goNextMonth() {
    visibleMonth = addMonths(visibleMonth, 1)
  }

  function moveFocus(delta: number) {
    const next = clampDate(addDays(focusDate, delta), min, max)
    focusDate = next
    if (!isSameMonth(next, visibleMonth)) {
      visibleMonth = startOfMonth(next)
    }
  }

  function selectDate(date: Date) {
    if (disabled) return
    if (isOutOfRange(date, min, max)) return
    onValueChange?.(startOfDay(date))
  }

  function onGridKeyDown(event: KeyboardEvent) {
    switch (event.key) {
      case 'ArrowLeft':
        event.preventDefault()
        moveFocus(-1)
        break
      case 'ArrowRight':
        event.preventDefault()
        moveFocus(1)
        break
      case 'ArrowUp':
        event.preventDefault()
        moveFocus(-7)
        break
      case 'ArrowDown':
        event.preventDefault()
        moveFocus(7)
        break
      case 'Home': {
        event.preventDefault()
        const offset = focusDate.getDay() - weekStartsOn
        moveFocus(-((offset + 7) % 7))
        break
      }
      case 'End': {
        event.preventDefault()
        const offset = (focusDate.getDay() - weekStartsOn + 7) % 7
        moveFocus(6 - offset)
        break
      }
      case 'PageUp':
        event.preventDefault()
        visibleMonth = addMonths(visibleMonth, -1)
        focusDate = clampDate(addMonths(focusDate, -1), min, max)
        break
      case 'PageDown':
        event.preventDefault()
        visibleMonth = addMonths(visibleMonth, 1)
        focusDate = clampDate(addMonths(focusDate, 1), min, max)
        break
      case 'Enter':
      case ' ':
        event.preventDefault()
        selectDate(focusDate)
        break
    }
  }
</script>

<div
  data-iris-calendar
  data-disabled={disabled ? '' : undefined}
  style:display="inline-flex"
  style:flex-direction="column"
  style:gap="8px"
  style:padding="var(--iris-padding-md, 12px)"
  style:background="var(--iris-surface)"
  style:color="var(--iris-foreground)"
  style:border="1px solid var(--iris-border)"
  style:border-radius="var(--iris-radius-md, 6px)"
  style:min-width="260px"
  style={style}
  class={className}
  {...rest}
>
  <!-- Header -->
  <div
    data-iris-calendar-header
    style:display="flex"
    style:align-items="center"
    style:justify-content="space-between"
    style:gap="4px"
  >
    <button
      type="button"
      aria-label={t('calendar.previousMonth')}
      data-iris-calendar-prev
      disabled={prevDisabled || undefined}
      onclick={goPrevMonth}
      style:width="28px"
      style:height="28px"
      style:display="inline-flex"
      style:align-items="center"
      style:justify-content="center"
      style:background="transparent"
      style:border="none"
      style:color="var(--iris-foreground)"
      style:cursor={prevDisabled ? 'not-allowed' : 'pointer'}
      style:border-radius="var(--iris-radius-sm, 4px)"
      style:font="inherit"
      style:opacity={prevDisabled ? '0.4' : '1'}
    >&#8249;</button>

    <div
      data-iris-calendar-title
      aria-live="polite"
      style:font-weight="600"
      style:font-size="14px"
    >{title}</div>

    <button
      type="button"
      aria-label={t('calendar.nextMonth')}
      data-iris-calendar-next
      disabled={nextDisabled || undefined}
      onclick={goNextMonth}
      style:width="28px"
      style:height="28px"
      style:display="inline-flex"
      style:align-items="center"
      style:justify-content="center"
      style:background="transparent"
      style:border="none"
      style:color="var(--iris-foreground)"
      style:cursor={nextDisabled ? 'not-allowed' : 'pointer'}
      style:border-radius="var(--iris-radius-sm, 4px)"
      style:font="inherit"
      style:opacity={nextDisabled ? '0.4' : '1'}
    >&#8250;</button>
  </div>

  <!-- Weekday names -->
  <div
    data-iris-calendar-weekdays
    role="row"
    style:display="grid"
    style:grid-template-columns="repeat(7, minmax(0, 1fr))"
    style:gap="2px"
    style:font-size="12px"
    style:color="var(--iris-muted)"
    style:text-align="center"
  >
    {#each weekdays as name (name)}
      <div role="columnheader" style:padding="2px 0">{name}</div>
    {/each}
  </div>

  <!-- Day grid -->
  <div
    data-iris-calendar-grid
    role="grid"
    aria-label={title}
    onkeydown={onGridKeyDown}
    style:display="grid"
    style:grid-template-columns="repeat(7, minmax(0, 1fr))"
    style:gap="2px"
  >
    {#each matrix as week}
      <!--
        `display: contents` keeps the row in the accessibility tree (a valid
        grid → row → gridcell structure) while letting its day cells participate
        directly in the parent's 7-column CSS grid layout.
      -->
      <div role="row" style:display="contents">
        {#each week as date (date.toISOString())}
          {@const inMonth = isSameMonth(date, visibleMonth)}
          {@const selected = value ? isSameDay(date, value) : false}
          {@const focused = isSameDay(date, focusDate)}
          {@const isToday = isSameDay(date, today)}
          {@const oof = isOutOfRange(date, min, max)}
          {@const isDisabled = disabled || oof}
          <button
            type="button"
            role="gridcell"
            aria-label={dayLabelFmt.format(date)}
            tabindex={focused ? 0 : -1}
            aria-selected={selected ? 'true' : 'false'}
            aria-disabled={isDisabled ? 'true' : undefined}
            aria-current={isToday ? 'date' : undefined}
            data-iris-calendar-day
            data-iris-calendar-day-iso={formatLocalISO(date)}
            data-state={selected ? 'selected' : focused ? 'focused' : isToday ? 'today' : 'idle'}
            data-outside-month={!inMonth ? 'true' : undefined}
            disabled={isDisabled || undefined}
            onclick={() => {
              focusDate = date
              selectDate(date)
            }}
            onfocus={() => { focusDate = date }}
            style:height="32px"
            style:display="inline-flex"
            style:align-items="center"
            style:justify-content="center"
            style:background={selected ? 'var(--iris-primary)' : isToday ? 'var(--iris-surface-hover)' : 'transparent'}
            style:color={selected ? 'var(--iris-primary-foreground, #fff)' : inMonth ? 'var(--iris-foreground)' : 'var(--iris-muted)'}
            style:border="none"
            style:border-radius="var(--iris-radius-sm, 4px)"
            style:cursor={isDisabled ? 'not-allowed' : 'pointer'}
            style:opacity={isDisabled ? '0.45' : '1'}
            style:font-size="13px"
            style:font-family="inherit"
            style:outline="none"
          >{date.getDate()}</button>
        {/each}
      </div>
    {/each}
  </div>
</div>

// packages/solid/src/primitives/calendar/IrisCalendar.tsx
import {
  createMemo,
  createSignal,
  createEffect,
  For,
  mergeProps,
  splitProps,
  type JSX,
} from 'solid-js'
import {
  addDays,
  addMonths,
  buildMonthMatrix,
  clampDate,
  endOfMonth,
  formatLocalISO,
  formatMonthYear,
  getWeekdayNames,
  isOutOfRange,
  isSameDay,
  isSameMonth,
  startOfDay,
  startOfMonth,
} from './dateUtils'
import { useI18n } from '../../i18n'

export interface IrisCalendarProps {
  value?: Date | null
  defaultValue?: Date | null
  defaultMonth?: Date | null
  min?: Date
  max?: Date
  weekStartsOn?: number
  locale?: string
  disabled?: boolean
  onChange?: (date: Date | null) => void
}

/**
 * Month-view calendar. Single date selection. Keyboard navigable.
 * Solid port of the Vue IrisCalendar.
 */
export function IrisCalendar(props: IrisCalendarProps): JSX.Element {
  const merged = mergeProps(
    {
      defaultValue: null as Date | null,
      defaultMonth: null as Date | null,
      weekStartsOn: 0,
      disabled: false,
    },
    props,
  )
  const [local] = splitProps(merged, [
    'value',
    'defaultValue',
    'defaultMonth',
    'min',
    'max',
    'weekStartsOn',
    'locale',
    'disabled',
    'onChange',
  ])

  const { t } = useI18n()

  const initialMonth = local.defaultMonth ?? local.defaultValue ?? local.value ?? new Date()
  const [visibleMonth, setVisibleMonth] = createSignal(startOfMonth(initialMonth))
  const [focusDate, setFocusDate] = createSignal<Date>(
    clampDate(local.value ?? local.defaultValue ?? new Date(), local.min, local.max),
  )

  // Sync visible month when controlled value changes to a different month
  createEffect(() => {
    const v = local.value
    if (v && !isSameMonth(v, visibleMonth())) {
      setVisibleMonth(startOfMonth(v))
      setFocusDate(clampDate(v, local.min, local.max))
    }
  })

  const matrix = createMemo(() => buildMonthMatrix(visibleMonth(), local.weekStartsOn))
  const weekdays = createMemo(() => getWeekdayNames(local.weekStartsOn, local.locale))
  const title = createMemo(() => formatMonthYear(visibleMonth(), local.locale))
  // One memoized formatter for the full-date cell label (e.g. "Monday, June 9,
  // 2026") so screen readers announce the whole date, not just the day number.
  const dayLabelFmt = createMemo(
    () =>
      new Intl.DateTimeFormat(local.locale, {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      }),
  )
  const today = startOfDay(new Date())

  const prevDisabled = createMemo(() => {
    if (!local.min) return false
    return startOfMonth(visibleMonth()) <= startOfMonth(local.min)
  })
  const nextDisabled = createMemo(() => {
    if (!local.max) return false
    return startOfMonth(endOfMonth(visibleMonth())) >= startOfMonth(local.max)
  })

  const goPrevMonth = () => setVisibleMonth((m) => addMonths(m, -1))
  const goNextMonth = () => setVisibleMonth((m) => addMonths(m, 1))

  const moveFocus = (delta: number) => {
    const next = clampDate(addDays(focusDate(), delta), local.min, local.max)
    setFocusDate(next)
    if (!isSameMonth(next, visibleMonth())) {
      setVisibleMonth(startOfMonth(next))
    }
  }

  const selectDate = (date: Date) => {
    if (local.disabled) return
    if (isOutOfRange(date, local.min, local.max)) return
    local.onChange?.(startOfDay(date))
  }

  const onGridKeyDown = (event: KeyboardEvent) => {
    switch (event.key) {
      case 'ArrowLeft':
        event.preventDefault()
        moveFocus(-1)
        break
      case 'ArrowRight':
        event.preventDefault()
        moveFocus(1)
        break
      case 'ArrowUp':
        event.preventDefault()
        moveFocus(-7)
        break
      case 'ArrowDown':
        event.preventDefault()
        moveFocus(7)
        break
      case 'Home': {
        event.preventDefault()
        const offset = focusDate().getDay() - local.weekStartsOn
        moveFocus(-((offset + 7) % 7))
        break
      }
      case 'End': {
        event.preventDefault()
        const offset = (focusDate().getDay() - local.weekStartsOn + 7) % 7
        moveFocus(6 - offset)
        break
      }
      case 'PageUp':
        event.preventDefault()
        setVisibleMonth((m) => addMonths(m, -1))
        setFocusDate((d) => clampDate(addMonths(d, -1), local.min, local.max))
        break
      case 'PageDown':
        event.preventDefault()
        setVisibleMonth((m) => addMonths(m, 1))
        setFocusDate((d) => clampDate(addMonths(d, 1), local.min, local.max))
        break
      case 'Enter':
      case ' ':
        event.preventDefault()
        selectDate(focusDate())
        break
    }
  }

  const navBtnStyle: JSX.CSSProperties = {
    width: '28px',
    height: '28px',
    display: 'inline-flex',
    'align-items': 'center',
    'justify-content': 'center',
    background: 'transparent',
    border: 'none',
    color: 'var(--iris-foreground)',
    cursor: 'pointer',
    'border-radius': 'var(--iris-radius-sm, 4px)',
    font: 'inherit',
  }

  return (
    <div
      data-iris-calendar=""
      data-disabled={local.disabled ? '' : undefined}
      style={{
        display: 'inline-flex',
        'flex-direction': 'column',
        gap: '8px',
        padding: 'var(--iris-padding-md, 12px)',
        background: 'var(--iris-surface)',
        color: 'var(--iris-foreground)',
        border: '1px solid var(--iris-border)',
        'border-radius': 'var(--iris-radius-md, 6px)',
        'min-width': '260px',
      }}
    >
      {/* Header */}
      <div
        data-iris-calendar-header=""
        style={{
          display: 'flex',
          'align-items': 'center',
          'justify-content': 'space-between',
          gap: '4px',
        }}
      >
        <button
          type="button"
          aria-label={t('calendar.previousMonth')}
          data-iris-calendar-prev=""
          disabled={prevDisabled() || undefined}
          onClick={goPrevMonth}
          style={{
            ...navBtnStyle,
            opacity: prevDisabled() ? '0.4' : '1',
            cursor: prevDisabled() ? 'not-allowed' : 'pointer',
          }}
        >
          ‹
        </button>
        <div
          data-iris-calendar-title=""
          aria-live="polite"
          style={{ 'font-weight': '600', 'font-size': '14px' }}
        >
          {title()}
        </div>
        <button
          type="button"
          aria-label={t('calendar.nextMonth')}
          data-iris-calendar-next=""
          disabled={nextDisabled() || undefined}
          onClick={goNextMonth}
          style={{
            ...navBtnStyle,
            opacity: nextDisabled() ? '0.4' : '1',
            cursor: nextDisabled() ? 'not-allowed' : 'pointer',
          }}
        >
          ›
        </button>
      </div>

      {/* Weekday headers */}
      <div
        data-iris-calendar-weekdays=""
        role="row"
        style={{
          display: 'grid',
          'grid-template-columns': 'repeat(7, minmax(0, 1fr))',
          gap: '2px',
          'font-size': '12px',
          color: 'var(--iris-muted)',
          'text-align': 'center',
        }}
      >
        <For each={weekdays()}>
          {(name) => (
            <div role="columnheader" style={{ padding: '2px 0' }}>
              {name}
            </div>
          )}
        </For>
      </div>

      {/* Day grid */}
      <div
        data-iris-calendar-grid=""
        role="grid"
        aria-label={title()}
        onKeyDown={onGridKeyDown}
        style={{
          display: 'grid',
          'grid-template-columns': 'repeat(7, minmax(0, 1fr))',
          gap: '2px',
        }}
      >
        <For each={matrix()}>
          {(row) => (
            // `display: contents` keeps the row in the accessibility tree (a
            // valid grid → row → gridcell structure) while letting its day cells
            // participate directly in the parent's 7-column CSS grid layout.
            <div role="row" style={{ display: 'contents' }}>
              <For each={row}>
                {(date) => {
                  const inMonth = () => isSameMonth(date, visibleMonth())
                  const selected = () => (local.value ? isSameDay(date, local.value) : false)
                  const focused = () => isSameDay(date, focusDate())
                  const isToday = () => isSameDay(date, today)
                  const oof = () => isOutOfRange(date, local.min, local.max)
                  const isDisabled = () => local.disabled || oof()

                  return (
                    <button
                      type="button"
                      role="gridcell"
                      aria-label={dayLabelFmt().format(date)}
                      tabIndex={focused() ? 0 : -1}
                      aria-selected={selected() ? 'true' : 'false'}
                      aria-disabled={isDisabled() ? 'true' : undefined}
                      aria-current={isToday() ? 'date' : undefined}
                      data-iris-calendar-day=""
                      data-iris-calendar-day-iso={formatLocalISO(date)}
                      data-state={
                        selected()
                          ? 'selected'
                          : focused()
                            ? 'focused'
                            : isToday()
                              ? 'today'
                              : 'idle'
                      }
                      data-outside-month={!inMonth() ? 'true' : undefined}
                      disabled={isDisabled() || undefined}
                      onClick={() => {
                        setFocusDate(date)
                        selectDate(date)
                      }}
                      onFocus={() => setFocusDate(date)}
                      style={{
                        height: '32px',
                        display: 'inline-flex',
                        'align-items': 'center',
                        'justify-content': 'center',
                        background: selected()
                          ? 'var(--iris-primary)'
                          : isToday()
                            ? 'var(--iris-surface-hover)'
                            : 'transparent',
                        color: selected()
                          ? 'var(--iris-primary-foreground, #fff)'
                          : inMonth()
                            ? 'var(--iris-foreground)'
                            : 'var(--iris-muted)',
                        border: 'none',
                        'border-radius': 'var(--iris-radius-sm, 4px)',
                        cursor: isDisabled() ? 'not-allowed' : 'pointer',
                        opacity: isDisabled() ? '0.45' : '1',
                        'font-size': '13px',
                        'font-family': 'inherit',
                        outline: 'none',
                      }}
                    >
                      {String(date.getDate())}
                    </button>
                  )
                }}
              </For>
            </div>
          )}
        </For>
      </div>
    </div>
  )
}
