// packages/solid/src/primitives/tree-select/IrisTreeSelect.tsx
import {
  createSignal,
  createMemo,
  mergeProps,
  onCleanup,
  onMount,
  splitProps,
  Show,
  type JSX,
} from 'solid-js'
import { IrisTree, type IrisTreeNode, type IrisTreeSelectionMode } from '../tree/IrisTree'
import { useI18n } from '../../i18n'

function findNode(nodes: IrisTreeNode[], id: string): IrisTreeNode | undefined {
  for (const node of nodes) {
    if (node.id === id) return node
    if (node.children) {
      const found = findNode(node.children, id)
      if (found) return found
    }
  }
  return undefined
}

export interface IrisTreeSelectProps {
  nodes?: IrisTreeNode[]
  value?: string[]
  defaultValue?: string[]
  selectionMode?: IrisTreeSelectionMode
  placeholder?: string
  disabled?: boolean
  invalid?: boolean
  onChange?: (ids: string[]) => void
  id?: string
}

/**
 * TreeSelect: an IrisTree embedded in a floating Select panel.
 * Solid port of the Vue IrisTreeSelect.
 */
export function IrisTreeSelect(props: IrisTreeSelectProps): JSX.Element {
  const { t } = useI18n()
  const merged = mergeProps(
    {
      nodes: [] as IrisTreeNode[],
      defaultValue: [] as string[],
      selectionMode: 'single' as IrisTreeSelectionMode,
      disabled: false,
      invalid: false,
    },
    props,
  )
  const [local] = splitProps(merged, [
    'nodes',
    'value',
    'defaultValue',
    'selectionMode',
    'placeholder',
    'disabled',
    'invalid',
    'onChange',
    'id',
  ])

  const [internalValue, setInternalValue] = createSignal<string[]>(local.defaultValue)
  const [open, setOpen] = createSignal(false)

  const currentValue = () => (local.value !== undefined ? local.value : internalValue())

  const displayLabel = createMemo(() => {
    const ids = currentValue()
    if (ids.length === 0) return ''
    const labels = ids.map((id) => findNode(local.nodes, id)?.label ?? id)
    return labels.join(', ')
  })

  const onSelect = (ids: string[]) => {
    if (local.value === undefined) setInternalValue(ids)
    local.onChange?.(ids)
    if (local.selectionMode === 'single' && ids.length > 0) {
      setOpen(false)
    }
  }

  let rootEl: HTMLDivElement | undefined
  // Close on outside click (mirrors React/Vue/Svelte).
  onMount(() => {
    const onDown = (e: MouseEvent): void => {
      if (open() && rootEl && !rootEl.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', onDown)
    onCleanup(() => document.removeEventListener('mousedown', onDown))
  })

  return (
    <div
      ref={rootEl}
      data-iris-tree-select=""
      style={{ position: 'relative', display: 'inline-block' }}
    >
      <button
        id={local.id}
        type="button"
        data-iris-tree-select-trigger=""
        data-state={open() ? 'open' : 'closed'}
        disabled={local.disabled || undefined}
        aria-invalid={local.invalid ? 'true' : undefined}
        aria-expanded={open()}
        aria-haspopup="tree"
        onClick={() => !local.disabled && setOpen((v) => !v)}
        onKeyDown={(e: KeyboardEvent) => {
          if (e.key === 'Escape' && open()) {
            e.preventDefault()
            setOpen(false)
          } else if ((e.key === 'ArrowDown' || e.key === 'Enter') && !open()) {
            e.preventDefault()
            if (!local.disabled) setOpen(true)
          }
        }}
        style={{
          display: 'inline-flex',
          'align-items': 'center',
          gap: '8px',
          padding: '6px 12px',
          background: 'var(--iris-surface)',
          border: `1px solid ${local.invalid ? 'var(--iris-danger)' : 'var(--iris-border)'}`,
          'border-radius': 'var(--iris-radius-md, 6px)',
          color: displayLabel() ? 'var(--iris-foreground)' : 'var(--iris-muted)',
          'font-size': '14px',
          'font-family': 'inherit',
          cursor: local.disabled ? 'not-allowed' : 'pointer',
          'min-width': '160px',
        }}
      >
        <span style={{ flex: '1', 'text-align': 'start' }}>
          {displayLabel() || local.placeholder || t('select.placeholder')}
        </span>
        <span aria-hidden="true">▾</span>
      </button>

      <Show when={open()}>
        <div
          data-iris-tree-select-panel=""
          style={{
            position: 'absolute',
            top: '100%',
            left: '0',
            'z-index': '100',
            'margin-top': '4px',
            background: 'var(--iris-surface)',
            border: '1px solid var(--iris-border)',
            'border-radius': 'var(--iris-radius-md, 6px)',
            'box-shadow': '0 4px 16px rgba(0,0,0,0.12)',
            padding: '8px',
            'min-width': '200px',
            'max-height': '300px',
            'overflow-y': 'auto',
          }}
          onMouseDown={(e) => e.preventDefault()}
        >
          <IrisTree
            nodes={local.nodes}
            selectedIds={currentValue()}
            selectionMode={local.selectionMode}
            onSelect={onSelect}
          />
        </div>
      </Show>
    </div>
  )
}

// packages/svelte/src/primitives/tree-select/IrisTreeSelect.svelte
<script lang="ts">
  import IrisTree from '../tree/IrisTree.svelte'
  import { useI18n } from '../../i18n'
  import type { IrisTreeNode, IrisTreeSelectionMode } from '../tree/types'

  interface Props {
    nodes?: IrisTreeNode[]
    value?: string[]
    placeholder?: string
    disabled?: boolean
    invalid?: boolean
    selectionMode?: IrisTreeSelectionMode
    onValueChange?: (ids: string[]) => void
    style?: string
    class?: string
  }

  let {
    nodes = [],
    value = [],
    placeholder,
    disabled = false,
    invalid = false,
    selectionMode = 'single',
    onValueChange,
    style,
    class: className,
    ...rest
  }: Props = $props()

  const { t } = useI18n()

  let open = $state(false)
  let containerEl = $state<HTMLElement | undefined>(undefined)

  function findLabels(nodeList: IrisTreeNode[], ids: string[]): string[] {
    const found: string[] = []
    function traverse(nodes: IrisTreeNode[]) {
      for (const n of nodes) {
        if (ids.includes(n.id)) found.push(n.label)
        if (n.children) traverse(n.children)
      }
    }
    traverse(nodeList)
    return found
  }

  const display = $derived(findLabels(nodes, value).join(', '))

  function toggle() {
    if (disabled) return
    open = !open
  }

  // Trigger keyboard: Escape closes; ArrowDown/Enter open (mirrors React/Vue).
  function onTriggerKeyDown(e: KeyboardEvent) {
    if (e.key === 'Escape' && open) {
      e.preventDefault()
      open = false
    } else if ((e.key === 'ArrowDown' || e.key === 'Enter') && !open) {
      e.preventDefault()
      if (!disabled) open = true
    }
  }

  function onSelect(ids: string[]) {
    onValueChange?.(ids)
    if (selectionMode === 'single') open = false
  }

  function onDocDown(e: MouseEvent) {
    if (open && containerEl && !containerEl.contains(e.target as Node)) open = false
  }

  $effect(() => {
    if (open) document.addEventListener('mousedown', onDocDown)
    else document.removeEventListener('mousedown', onDocDown)
    return () => document.removeEventListener('mousedown', onDocDown)
  })
</script>

<div
  bind:this={containerEl}
  data-iris-tree-select
  style:position="relative"
  style:display="inline-flex"
  style={style}
  class={className}
  {...rest}
>
  <button
    type="button"
    {disabled}
    aria-invalid={invalid ? 'true' : undefined}
    aria-expanded={open}
    aria-haspopup="tree"
    data-iris-tree-select-trigger
    data-state={open ? 'open' : 'closed'}
    onclick={toggle}
    onkeydown={onTriggerKeyDown}
    style:display="inline-flex"
    style:align-items="center"
    style:justify-content="space-between"
    style:gap="6px"
    style:padding="6px 12px"
    style:min-height="34px"
    style:min-width="180px"
    style:background="var(--iris-background)"
    style:color={value.length > 0 ? 'var(--iris-foreground)' : 'var(--iris-muted)'}
    style:border={`1px solid ${invalid ? 'var(--iris-danger)' : 'var(--iris-border)'}`}
    style:border-radius="var(--iris-radius-md, 6px)"
    style:cursor={disabled ? 'not-allowed' : 'pointer'}
    style:font-size="14px"
    style:font-family="inherit"
    style:text-align="start"
  >
    <span style:flex="1">{display || (placeholder ?? t('select.placeholder'))}</span>
    <span aria-hidden="true" style:font-size="10px">{open ? '▲' : '▼'}</span>
  </button>

  {#if open}
    <div
      data-iris-tree-select-panel
      role="dialog"
      style:position="absolute"
      style:top="calc(100% + 4px)"
      style:left="0"
      style:z-index="50"
      style:min-width="240px"
      style:max-height="320px"
      style:overflow-y="auto"
      style:background="var(--iris-background)"
      style:border="1px solid var(--iris-border)"
      style:border-radius="var(--iris-radius-md, 6px)"
      style:box-shadow="0 8px 24px rgba(0,0,0,0.12)"
      style:padding="4px"
    >
      <IrisTree
        {nodes}
        selected={value}
        {selectionMode}
        onSelectedChange={onSelect}
        style="min-width: 200px;"
      />
    </div>
  {/if}
</div>
